### ISSUE TITLE
unit test cannot pass 

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx-tensorrt#10]
check out version f1b74d522fc9498cd5a6a81384aa22b298d3acf3
build it in docker
go to docker 
root@tempfix:/workspace# python onnx_backend_test.py

----------------------------------------------------------------------        
Ran 540 tests in 370.619s                                                     
 FAILED (failures=2, errors=46, skipped=355)

**Comment by kevinch-nv** [comment]
Thanks for the report. We are actively improving our operator coverage, see the master branch for the most up to date support matrix of ONNX operators in TensorRT.
