### ISSUE TITLE
make failed (undefined reference)

### ISSUE THREAD

**Issue by Eddiesyn** [onnx/onnx-tensorrt#118]
make failed. Information after cmake is:

-- ******** Summary ********
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -Wall -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx2trt_onnx
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx2trt_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf includes     : /usr/local/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : OFF
-- Found TensorRT headers at /home/mllab/tensorrt/TensorRT-5.0.2.6/include
-- Find TensorRT libs at /home/mllab/tensorrt/TensorRT-5.0.2.6/lib/libnvinfer.so;/home/mllab/tensorrt/TensorRT-5.0.2.6/lib/libnvinfer_plugin.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mllab/onnx-tensorrt/build

Failed error is:
`CMakeFiles/getSupportedAPITest.dir/getSupportedAPITest.cpp.o: In function `common::ParseFromFile_WAR(google::protobuf::Message*, char const*)':
getSupportedAPITest.cpp:(.text+0x1158): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
libnvonnxparser_static.a(ModelImporter.cpp.o): In function `onnx2trt::deserialize_onnx_model(void const*, unsigned long, bool, onnx2trt_onnx::ModelProto*)':
ModelImporter.cpp:(.text+0x348): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
libnvonnxparser_static.a(ModelImporter.cpp.o): In function `onnx2trt::deserialize_onnx_model(int, bool, onnx2trt_onnx::ModelProto*)':
ModelImporter.cpp:(.text+0x8f89): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
libnvonnxparser_static.a(OnnxAttrs.cpp.o): In function `google::protobuf::RepeatedField<float>::Reserve(int)':
OnnxAttrs.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIfE7ReserveEi]+0x63): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned long)'
OnnxAttrs.cpp:(.text._ZN6google8protobuf13RepeatedFieldIfE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIfE7ReserveEi]+0xde): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
libnvonnxparser_static.a(OnnxAttrs.cpp.o): In function `google::protobuf::RepeatedField<long>::Reserve(int)':
OnnxAttrs.cpp:(.text._ZN6google8protobuf13RepeatedFieldIlE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIlE7ReserveEi]+0x60): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned long)'
OnnxAttrs.cpp:(.text._ZN6google8protobuf13RepeatedFieldIlE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIlE7ReserveEi]+0xde): undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto::ByteSizeLong() const':
onnx_onnx2trt_onnx.pb.cc:(.text+0x155e): undefined reference to `google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x15a7): undefined reference to `google::protobuf::internal::WireFormatLite::Int32Size(google::protobuf::RepeatedField<int> const&)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x1622): undefined reference to `google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x169a): undefined reference to `google::protobuf::internal::WireFormatLite::UInt64Size(google::protobuf::RepeatedField<unsigned long> const&)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::AttributeProto::ByteSizeLong() const':
onnx_onnx2trt_onnx.pb.cc:(.text+0x1807): undefined reference to `google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
onnx_onnx2trt_onnx.pb.cc:(.text+0x2ecb): undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloatArray(float const*, int, google::protobuf::io::CodedOutputStream*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3176): undefined reference to `google::protobuf::internal::WireFormatLite::WriteDoubleArray(double const*, int, google::protobuf::io::CodedOutputStream*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3294): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x32a4): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x32b4): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3351): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x335e): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3370): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3394): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x33a6): undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o):onnx_onnx2trt_onnx.pb.cc:(.text+0x33b6): more undefined references to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)' follow
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.227]':
onnx_onnx2trt_onnx.pb.cc:(.text+0x33f6): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `protobuf_onnx_2fonnx_5fonnx2trt_5fonnx_2eproto::InitDefaults()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x34d9): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x34f1): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3511): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3531): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x3551): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o):onnx_onnx2trt_onnx.pb.cc:(.text+0x3571): more undefined references to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)' follow
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `protobuf_onnx_2fonnx_5fonnx2trt_5fonnx_2eproto::protobuf_AssignDescriptors()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3a5e): undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::AttributeProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3b73): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::AttributeProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3bfd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ValueInfoProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3c33): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ValueInfoProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3c8d): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::NodeProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3cb3): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::NodeProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3cda): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::NodeProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3dcd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ModelProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3e03): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ModelProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3e6d): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::StringStringEntryProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3e93): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::StringStringEntryProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3eaa): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::StringStringEntryProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3fbd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::GraphProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x3fe3): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::GraphProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x400a): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::GraphProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x40bd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto_Segment::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x41bd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x41f3): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4235): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x44cd): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto_Dimension::InitAsDefaultInstance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x44ea): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto_Dimension::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4503): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto_Dimension::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x455d): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto_Dimension::clear_value()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4597): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto_Dimension::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x45e0): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TensorShapeProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x481d): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TypeProto_Tensor::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x495d): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TypeProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4993): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TypeProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x49ed): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::TypeProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4aa0): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ValueInfoProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4b65): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ModelProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4ee5): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::AttributeProto::SharedDtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x4fe5): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::OperatorSetIdProto::SharedCtor()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x5453): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o):onnx_onnx2trt_onnx.pb.cc:(.text+0x5478): more undefined references to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]' follow
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::OperatorSetIdProto::default_instance()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x56ed): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ValueInfoProto::ValueInfoProto()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x5751): undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `protobuf_onnx_2fonnx_5fonnx2trt_5fonnx_2eproto::InitDefaultsValueInfoProto()':
onnx_onnx2trt_onnx.pb.cc:(.text+0x5799): undefined reference to `google::protobuf::internal::DestroyMessage(void const*)'
onnx_onnx2trt_onnx.pb.cc:(.text+0x57a1): undefined reference to `google::protobuf::internal::OnShutdownRun(void (*)(void const*), void const*)'
third_party/onnx/libonnx_proto.a(onnx_onnx2trt_onnx.pb.cc.o): In function `onnx2trt_onnx::ValueInfoProto* google::protobuf::Arena::CreateMaybeMessage<onnx2trt_onnx::ValueInfoProto>(google::protobuf::Arena*)':
onnx_onnx2trt_onnx.pb.cc:(.text+0x57d5): undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'`

There are more but i won't list them all to make it more readable. All of them are due to undefined reference seems like my protobuf library is not linked.
But the cmake information gives correct result. 
**My protocol version is 3.6.1**

**Comment by Eddiesyn** [comment]
The workaround is to use protocol version 3.7.0, which is the latest version. Then the make succeeds.

**Comment by shuangyichen** [comment]
> The workaround is to use protocol version 3.7.0, which is the latest version. Then the make succeeds.

protobuf？
