### ISSUE TITLE
Build onnx2trt errors

### ISSUE THREAD

**Issue by cherryxiongyw** [onnx/onnx-tensorrt#12]
When I build onnx2trt, I had some errors like:

 5 errors detected in the compilation of "/tmp/tmpxft_00004c43_00000000-7_Split.cpp1.ii".
-- Removing /home/amax/Codes/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o
/usr/bin/cmake -E remove /home/amax/Codes/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o
CMake Error at nvonnxparser_plugin_generated_Split.cu.o.cmake:266 (message):
  Error generating file
  /home/amax/Codes/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o

CMakeFiles/nvonnxparser_plugin.dir/build.make:77: recipe for target CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_Split.cu.o failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_Split.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs..

so what's wrong ?

**Comment by yinghai** [comment]
Could you attach what version of cmake, cuda did you use? And if you can do
`make VERBOSE=1`
It will give more detailed error log.

**Comment by cherryxiongyw** [comment]
@yinghai  I use Cmake=3.5.1 and cuda8

**Comment by cherryxiongyw** [comment]
The more detailed error log as:

/usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
/home/amax/Codes/onnx-tensorrt/Split.cu(39): here

/usr/include/c++/5/bits/stl_iterator_base_types.h(155): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
/home/amax/Codes/onnx-tensorrt/Split.cu(39): here

**Comment by yinghai** [comment]
Which compiler version are you using? Could you add the full log? 

Try changing Split.cu Line 39 from 
```
std::vector<int> segment_offsets(1, 0);
```
to 
```
std::vector<int> segment_offsets = {0};
```

**Comment by varunarora** [comment]
I have the same issue and that didn't work @yinghai :(

**Comment by yinghai** [comment]
@varunarora Can you do `make VERBOSE=1` and print the actual command that is being run?

**Comment by varunarora** [comment]
Nvm, I think I was lying to myself. The CUDA version is 7.5, will upgrade..
