### ISSUE TITLE
how self define plugin layers and be used by TensorRT5

### ISSUE THREAD

**Issue by lixuefeng810** [onnx/onnx-tensorrt#121]
I have implemented a plugin layer and build successfully, I wander how the library can be used by TensorRT, replace the *.so and *.a or more operations?

**Comment by kevinch-nv** [comment]
Please see this [sample ](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/samplePlugin) for an explanation on how to add and run your plugin layer in TensorRT.
