### ISSUE TITLE
UpSampling2D and LeakyRelu with Tensorrt 4

### ISSUE THREAD

**Issue by MohamedAfifii** [onnx/onnx-tensorrt#122]
Hello, 
I get segmentation fault when deserializing the trt engine if I use UpSampling2D or LeakyRelu.  
Here is the model:  
```
from keras.layers import LeakyReLU, BatchNormalization, UpSampling2D, Conv2D
import onnxmltools

inputs = Input(shape=(224,224,3))
outputs = Conv2D(64, (3,3), strides=(2,2))(inputs)
outputs = UpSampling2D(2)(outputs)
model = Model(inputs, outputs)

onnx_model = onnxmltools.convert_keras(model)
onnxmltools.utils.save_model(onnx_model, 'dark.onnx')
```

I then convert the onnx model to trt:  
```
----------------------------------------------------------------
Input filename:   dark.onnx
ONNX IR version:  0.0.4
Opset version:    7
Producer name:    OnnxMLTools
Producer version: 1.3.1
Domain:           onnxml
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
Parsing model
Building TensorRT engine, FP16 available:1
    Max batch size:     32
    Max workspace size: 1024 MiB
Writing TensorRT engine to mini_yolo3.trt
All done
```  
When I deserialize this trt file I get segmentation fault.  
However when I remove the UpSampling2D layer and put any other layer (except for LeakyRelu), the engine is loaded successfully.  

Please let me know if I am asking in the wrong place. Also if there is any workaround (other than upgrading the tensorrt version) please tell me.  
I am using Jetson TX2 with Jetpack 3.3

**Comment by kevinch-nv** [comment]
Hi @MohamedAfifii, we've dropped support for TRT 4, so please consider upgrading your TensorRT version.

In addition, we recommend using the shipped `trtexec` binary over `onnx2trt` to create serialized engine files, as the latter will be deprecated in a later release.
