### ISSUE TITLE
Does onnx-tensorrt support TensorRT 3?

### ISSUE THREAD

**Issue by irnwritshin** [onnx/onnx-tensorrt#135]
I see that in README, TensorRT 3+ is supported. However, when I try to install the project, it seems to be using api only defined since TensorRT4.

Is there a way (a switch or something) for the project to support TensorRT 3 or the project do not support TensorRT 3 at all?

Thanks,

**Comment by kevinch-nv** [comment]
No, TensorRT 3 support is available and not planned.
