### ISSUE TITLE
[8] No importer registered for op: PRelu

### ISSUE THREAD

**Issue by deimsdeutsch** [onnx/onnx-tensorrt#136]
ONNX IR version:  0.0.3
Opset version:    8
Producer name:    
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
While parsing node number 6 [PRelu -> "relu0"]:
ERROR: /opt/github4/onnx-tensorrt/ModelImporter.cpp:142 In function importNode:
[8] No importer registered for op: PRelu

**Comment by deimsdeutsch** [comment]
Can we integrate this into the solution:

https://github.com/Goingqs/TensorRT-Prelu

**Comment by Jerry3062** [comment]
I come cross this problem too.no PRelu layer，How Can I solve this problem?

**Comment by ibrahimsherdil** [comment]
@deimsdeutsch we'll need to change the implementation, since how mxnet performs PReLU is different from Caffe. Parameters for mxnet PReLU will be different from caffe's implementation of PReLU.

**Comment by veepersgit** [comment]
Same problem while converting model from onnx( model from pytorch ) to trt.

**Comment by coolbei** [comment]
same problem.  with op ATen.  actually it's a torch.max call.

**Comment by ibrahimsherdil** [comment]
Try changing the implementation of PReLU in onnx, which currently supports scalar values.

**Comment by deimsdeutsch** [comment]
Eagerly waiting for the solution....

**Comment by leiyu1980** [comment]
Eagerly waiting for the solution....

**Comment by YaminSAIC** [comment]
@coolbei  Hi, I have the same problem with ATen, do you have a solution now?

**Comment by jamessmith90** [comment]
@ibrahimsherdil 

3 months and still waiting for the solution....

**Comment by LovExtreme** [comment]
So I find a workaround for the PReLU problem if you stuck with this. You have to create an intermediate model which replace the PReLU with the original implementation of the PReLU:

PReLU = ReLU(x) - prelu_weight * ReLU(-x)

In that:
- prelu_weight is the weight you get from the PReLU module.

It will be a lot of work. So stay strong!!!

**Comment by hadeson** [comment]
```
class PseudoPReLu(Module):
    def __init__(self, num_parameters=1, init=0.25, inplace=True):
        self.num_parameters = num_parameters
        super(PseudoPReLu, self).__init__()
        self.weight = Parameter(torch.Tensor(num_parameters).fill_(init))
        self.inplace = inplace

    def forward(self, input):
        res = F.relu(input, inplace=self.inplace)
        min_res = F.relu(-input, inplace=self.inplace)
        weight_broadcast = self.weight.reshape(1, self.weight.shape[0], 1, 1)       
        return res - weight_broadcast * min_res

    def extra_repr(self):
        return 'num_parameters={}'.format(self.num_parameters)
```
I take @LovExtreme advice and reimplement PReLU with ReLU. Parsing with no problem.

**Comment by deimsdeutsch** [comment]
Go to hell Nvidia.

**Comment by ashuezy** [comment]
Parsing model
While parsing node number 6 [PRelu -> "relu0"]:
ERROR: /opt/github/onnx-tensorrt-5.1/ModelImporter.cpp:143 In function importNode:
[8] No importer registered for op: PRelu

9 Months and no support...

**Comment by seovchinnikov** [comment]
I was putting hacks like this to replace unsupported operations since 2018...

**Comment by kevinch-nv** [comment]
PRelu has been supported since TensorRT 6.0. Closing this issue.
