### ISSUE TITLE
About the ONNX 2 TRT

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [onnx/onnx-tensorrt#144]
I get alexnet onnx model for the link：
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb
using code：
import torch.onnx
import torchvision
dummy_input = torch.randn(1, 3, 224, 224)
model = torchvision.models.alexnet(pretrained=True)
torch.onnx.export(model, dummy_input, "alexnet.onnx")

And running :
auto parser = nvonnxparser::createParser(*network, gLogger);
parser->parseFromFile(locateFile(modelFile, directories).c_str(), verbosity);

It is wrong and saying:
----------------------------------------------------------------
Input filename:   ../../data/models/alexnet.onnx
ONNX IR version:  0.0.3
Opset version:    9
Producer name:    pytorch
Producer version: 0.4
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
While parsing node number 15 [Gather -> "32"]:
ERROR: C:\p4sw\sw\gpgpu\MachineLearning\DIT\release\5.0\parsers\onnxOpenSource\ModelImporter.cpp:142 In function importNode:
[8] No importer registered for op: Gather

What's wrong?

**Comment by MenGuangwen-CN-0411** [comment]
I have got the reason ,thanks...

**Comment by xiaozhuka** [comment]
Have you solved this problem？

**Comment by DJMeng** [comment]
@MenGuangwen-CN-0411  hi guys how do you solve it? i also meet this problem. please help, thanks first!
