### ISSUE TITLE
Example for custom layers

### ISSUE THREAD

**Issue by IdoZach** [onnx/onnx-tensorrt#145]
Hi,
I'd like to implement custom layers so that ONNX layers that are currently unsupported by TRT will be converted. Can you please add an example or provide documentation?

Thanks.

**Comment by ibrahimsherdil** [comment]
Anyone who has implemented a custom layer with ONNX, who can share a small example?

**Comment by wangshankun** [comment]
wait to complete ！！！

**Comment by wangshankun** [comment]
> Hi,
> I'd like to implement custom layers so that ONNX layers that are currently unsupported by TRT will be converted. Can you please add an example or provide documentation?
> 
> Thanks.

using  sample: builtin_plugins.cpp
REGISTER_BUILTIN_PLUGIN("InstanceNormalization", InstanceNormalizationPlugin);

but i want use PluginFactory.cpp for serialize

**Comment by kevinch-nv** [comment]
See https://github.com/onnx/onnx-tensorrt/blob/master/docs/faq.md#custom-layer-support on instructions for adding custom layers through plugins in ONNX-TensorRT.
