### ISSUE TITLE
Build failed for TensorRT 4.0

### ISSUE THREAD

**Issue by BeamOfLight** [onnx/onnx-tensorrt#147]
TensorRT 4.0.1.6
CUDA 9.0.252
cuDNN 7.0.5.15

/home/beamoflight/ar13.thirdparty/prj.thirdparty/onnx-tensorrt/builtin_op_importers.cpp:629:5: **error: ‘IIdentityLayer’ is not a member of ‘nvinfer1’**
     nvinfer1::IIdentityLayer* layer = ctx->network()->addIdentity(inputs.at(0).tensor());
     ^
/home/beamoflight/ar13.thirdparty/prj.thirdparty/onnx-tensorrt/builtin_op_importers.cpp:629:31: **error: ‘layer’ was not declared in this scope**
     nvinfer1::IIdentityLayer* layer = ctx->network()->addIdentity(inputs.at(0).tensor());
                               ^
/home/beamoflight/ar13.thirdparty/prj.thirdparty/onnx-tensorrt/builtin_op_importers.cpp:629:55: **error: ‘class nvinfer1::INetworkDefinition’ has no member named ‘addIdentity’**
     nvinfer1::IIdentityLayer* layer = ctx->network()->addIdentity(inputs.at(0).tensor());

**Comment by Jongchan** [comment]
Same here. Failed with the same error message using the tensorrt container `nvcr.io/nvidia/tensorrt:18.08-py3` which has TensorRT 4.0.1.
Succeeded with the tensorrt container `nvcr.io/nvidia/tensorrt:19.03-py3` which has TensorRT 5.0.2.

**Comment by BeamOfLight** [comment]
Build succeeded for CUDA 10.1 + cuDNN 7,5 + TensorRT 5.1.2.1

**Comment by liuchang8am** [comment]
same error here, any updates?

**Comment by lawrencekiba** [comment]
Experienced this same error. Have you been able to solve it?

**Comment by kevinch-nv** [comment]
TensorRT 4 is no longer supported, please try building with the latest TensorRT version. Feel free to reopen this issue if you are still having trouble.
