### ISSUE TITLE
create_plugin_factory support in tensorrt5/py 

### ISSUE THREAD

**Issue by windyrobin** [onnx/onnx-tensorrt#159]
the code now in backend.py dosn't support `create_plugin_factory` in tensorrt5,  
i try to  call it directly  but I got a  'segment fault' when  `deserialize`
how to solve it ?
any suggestion was pleased.

```
    def _serialize_deserialize(self, trt_engine):
        if USE_PYBIND:
            self.runtime = trt.Runtime(TRT_LOGGER)
        else:
            self.runtime = trt.infer.create_infer_runtime(self._logger)
            self.plugin_factory = parser_runtime.create_plugin_factory(self._logger)

        serialized_engine = trt_engine.serialize()
        del self.parser # Parser no longer needed for ownership of plugins

        if USE_PYBIND:
            trt_engine = self.runtime.deserialize_cuda_engine(
                serialized_engine)
        else:
            trt_engine = self.runtime.deserialize_cuda_engine(
                serialized_engine, self.plugin_factory)
```

**Comment by windyrobin** [comment]
@goldgeisser

**Comment by mengzhibin** [comment]
Same error, anyone?

**Comment by kevinch-nv** [comment]
We are not supporting TensorRT 5 anymore, so I'm closing this issue.

In later TensorRT versions we are no longer using the plugin factory and have moved to the updated plugin registry, so this issue should no longer occur. If you encounter this in the latest TRT version, feel free to open another issue.
