### ISSUE TITLE
aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’

### ISSUE THREAD

**Issue by kalenforn** [onnx/onnx-tensorrt#162]
I compile onnx_tensorrt on my JESTON NANO development board, but after it is compiled, when I run  `python setup.py install`  it expect this error,could someone try the same result? How to solve this error?

This is running result:

`nano@nano-desktop:~/code/onnx-tensorrt$ sudo python setup.py build

running build

running build_py

running build_ext

building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension

swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp

swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ytvI67
/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c nv_onnx_parser_bindings_wrap.cpp -o build/temp.linux-aarch64-2.7
/nv_onnx_parser_bindings_wrap.o -std=c++11 -DUNIX -D__UNIX -m64 -fPIC -O2 -w -fmessage-length=0 -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -Wall -DSWIG

aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’

error: command 'aarch64-linux-gnu-gcc' failed with exit status 1`

**Comment by veepersgit** [comment]
Same error on TX2

**Comment by hgnan** [comment]
Same error on Jetson Nano

**Comment by kalenforn** [comment]
> Same error on Jetson Nano. But I try edit setup.py and delete line 37 （ '-m64'，） , the error no longer appears.
> 
> `jetson-nano:~/nas/onnx-tensorrt$ python3 setup.py build running build running build_py running build_ext building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c nv_onnx_parser_bindings_wrap.cpp -o build/temp.linux-aarch64-3.6/nv_onnx_parser_bindings_wrap.o -std=c++11 -DUNIX -D__UNIX -fPIC -O2 -w -fmessage-length=0 -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -Wall -DSWIG aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-aarch64-3.6/nv_onnx_parser_bindings_wrap.o build/libnvonnxparser.so -o build/lib.linux-aarch64-3.6/onnx_tensorrt/parser/_nv_onnx_parser_bindings.cpython-36m-aarch64-linux-gnu.so building 'onnx_tensorrt.runtime._nv_onnx_runtime_bindings' extension swigging nv_onnx_runtime_bindings.i to nv_onnx_runtime_bindings_wrap.cpp swig -python -c++ -modern -builtin -o nv_onnx_runtime_bindings_wrap.cpp nv_onnx_runtime_bindings.i NvOnnxParserRuntime.h:35: Warning 401: Nothing known about base class 'nvinfer1::IPluginFactory'. Ignored. aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c nv_onnx_runtime_bindings_wrap.cpp -o build/temp.linux-aarch64-3.6/nv_onnx_runtime_bindings_wrap.o -std=c++11 -DUNIX -D__UNIX -fPIC -O2 -w -fmessage-length=0 -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -Wall -DSWIG aarch64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-aarch64-3.6/nv_onnx_runtime_bindings_wrap.o build/libnvonnxparser_runtime.so -o build/lib.linux-aarch64-3.6/onnx_tensorrt/runtime/_nv_onnx_runtime_bindings.cpython-36m-aarch64-linux-gnu.so`

Thanks!

**Comment by prnvjb** [comment]
Hey @kalenforn ,
How did you compile onnx_tensorrt on jetson nano?
But every time I tried I'm getting No CMAKE_CUDA_COMPILER could be found. Could you give a short tutorial?
Thanks!
