### ISSUE TITLE
About the Pytorch2ONNX2trt

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [onnx/onnx-tensorrt#174]
I try to use my model from pytorch 2 onnx,then 2 trt and it works well.
but ,when I try to save onnx as '.engin' in c++ trt and load , I got some err like this:
getPluginCreator could not find plugin ResizeNearest version 001 namespace 
Cannot deserialize plugin ResizeNearest
Some one says this because Somehow the ResizeNearest plugin is implemented in tensorrt onnx parser.
I get the .onnx as follow:
from onnx import helper
helper.make_node(
'Upsample',
mode='nearest',
scales=[1.0, 1.0, 2, 2],
inputs=inputs,
outputs=[layer_name],
name=layer_name,
)...
and I got :
onnx::Upsample[mode = 'nearest', scales = [1, 1, 2, 2]]....
How to slove this problem

**Comment by qingzhouzhen** [comment]
I meet this proble, Did you solved it?

**Comment by kolyanchik** [comment]
> I meet this proble, Did you solved it?

Use TensorRT 6, Added ResizeBilinear and ResizeNearest ops.
[https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html](url)
