### ISSUE TITLE
about cmake error:CUDA_nppi_LIBRARY (ADVANCED)

### ISSUE THREAD

**Issue by xiaoxiaotao** [onnx/onnx-tensorrt#178]
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.0 (found version "9.0") 
-- Found Protobuf: /usr/lib/aarch64-linux-gnu/libprotobuf.so  
-- Build type not set - defaulting to Release
-- 
-- ******** Summary ********
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -Wall -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx2trt_onnx
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.3.0
--   ONNX NAMESPACE        : onnx2trt_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf includes     : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/aarch64-linux-gnu/libprotobuf.so;debug;/usr/lib/aarch64-linux-gnu/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : OFF
-- GPU_ARCH defined as 61. Generating CUDA code for SM 61
-- Found CUDNN: /usr/include  
-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so
-- Found TENSORRT: /usr/include/aarch64-linux-gnu  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_nppi_LIBRARY (ADVANCED)
    linked by target "getSupportedAPITest" in directory /home/nvidia/onnx-tensorrt
    linked by target "nvonnxparser_plugin" in directory /home/nvidia/onnx-tensorrt
    linked by target "trt_onnxify" in directory /home/nvidia/onnx-tensorrt
    linked by target "onnx2trt" in directory /home/nvidia/onnx-tensorrt

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/onnx-tensorrt/build/CMakeFiles/CMakeError.log".

**Comment by xiaoxiaotao** [comment]
how to solve it?

**Comment by leijuzi** [comment]
i met too

**Comment by xiaoxiaotao** [comment]
@leijuzi  when you run cmake ,you can add "-DCUDA_nppi_LIBRARY=true".

**Comment by Tranks27** [comment]
I used that command in my cmake for installing opencv3.2 but it was just a quick fix to get over cmake command. It fails when i ran "make -j8'

**Comment by Tranks27** [comment]
> @leijuzi when you run cmake ,you can add "-DCUDA_nppi_LIBRARY=true".

I used that command in my cmake for installing opencv3.2 but it was just a quick fix to get over cmake command. It fails when i ran "make -j8'

**Comment by LorenzoLamberti94** [comment]
same for me. Fails at the next step
