### ISSUE TITLE
How do I use the .trt file to test inference

### ISSUE THREAD

**Issue by wangshankun** [onnx/onnx-tensorrt#182]
**How do I use the .trt file to test inference**

**Using onnx2trt  get trt file，but I can't find sample to load and run.**

onnx2trt ../example_centernet_dla34/centernet_dla34.onnx -o ../example_centernet_dla34/centernet_dla34.trt -d 16

Input filename:   ../example_centernet_dla34/centernet_dla34.onnx
ONNX IR version:  0.0.3
Opset version:    9
Producer name:    pytorch
Producer version: 0.4
Domain:
Model version:    0
Doc string:

Parsing model
Building TensorRT engine, FP16 available:1
    Max batch size:     32
    Max workspace size: 1024 MiB
Writing TensorRT engine to ../example_centernet_dla34/centernet_dla34.trt
All done

**Comment by laggui** [comment]
Not sure if you're still looking for this, but take a look at my latest comment on issue #180 .
I posted a quick code sample to do so.

**Comment by anuar12** [comment]
@laggui Thank you for the help.
I manage to run it, however it seems like it runs with any input shape provided (even 2d tensor instead of 4 tensor that pytorch model was trained in)... Does it keep the same shape order as in pytorch? (N, C, H, W)?

**Comment by fused-byte** [comment]
@anuar12  Can you share the code? I am also looking for it and I could not find it.

**Comment by kevinch-nv** [comment]
I would recommend using `trtexec` to build and load engine files to test inference over `onnx2trt` as we plan on deprecating the latter. You can find more information in the open source documentation of `trtexec` [here](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec). Closing this issue, if you are having troubles with using `trtexec` feel free to reopen.
