### ISSUE TITLE
WARNING: ONNX model has a newer ir_version (0.0.5) than this parser was built against (0.0.3).

### ISSUE THREAD

**Issue by electronicYH** [onnx/onnx-tensorrt#199]
I meet the problem:

a@a:/data/yh/onnx-tensorrt/build$ onnx2trt yh_fcn_14c_include_weights.onnx -o yh.trt -g
----------------------------------------------------------------
Input filename:   yh_fcn_14c_include_weights.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.5.0
Domain:           onnx
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.5) than this parser was built against (0.0.3).
Parsing model
While parsing node number 1 [Conv -> "convolution_output"]:
ERROR: /data/yh/onnx-tensorrt/ModelImporter.cpp:537 In function importModel:
[5] Assertion failed: tensors.count(input_name)

please help me to fix it, thank you so much!!!!!

**Comment by he44** [comment]
Hi @electronicYH  did you fix the issue? I had the same problem here. 
I tried to resolve the ir version warning by setting different target opset in keras2onnx but that didn't help. (I tried all the way form 1 to 10).
For the assertion failure, I checked the ModelImport.cpp. I assume it's because the code finds that one of the nodes have 0 input? Though I checked the graph of my model, don't think that's the case.

```
for( size_t node_idx : topological_order ) {
    _current_node = node_idx;
    ::ONNX_NAMESPACE::NodeProto const& node = graph.node(node_idx);
    std::vector<TensorOrWeights> inputs;
    for( auto const& input_name : node.input() ) {
      ASSERT(tensors.count(input_name), ErrorCode::kINVALID_GRAPH);
      inputs.push_back(tensors.at(input_name));
    }
    // ...
}
```

On a separate note, have you run the onnx checker after exporting?
```
import onnx
onnx.checker.check_model(onnx_model)
```
The checker threw a warning for me:
```
Nodes in a graph must be topologically sorted, however input 'conv2d_31_Relu_0' of node: 
input: "conv2d_31_Relu_0" output: "transpose_output7" name: "Transpose21" op_type: "Transpose" attribute { name: "perm" ints: 0 ints: 2 ints: 3 ints: 1 type: INTS } doc_string: "" domain: ""
 is not output of any previous nodes.
```

However, my onnx model can run inference fine in Python API using the code below. So I assumed this shouldn't be a big issue?
```
import onnxruntime as rt
import numpy as np
X_test = np.ones((1,h,w,1))
sess    = rt.InferenceSession("my_model.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx    = sess.run([label_name], {input_name: X_test.astype(np.float32)})[0]
```

Any insights would be greatly appreciated!

**Comment by pango99** [comment]
I ran into the same problem when I ran the DeepLabV3 onnx model converted from keras on TensorRT SDK 5.1.5, how to fix the proble?

**Comment by zjd1988** [comment]
@pango99  I modify importModel code in ModelImporter.cpp, and rcompile onnx-tensorrt(https://github.com/onnx/onnx-tensorrt)

![WXWorkCapture_15665234078763](https://user-images.githubusercontent.com/7134030/63560207-c18cd580-c587-11e9-91a3-cb7d96b62522.png)

it works for me, you can have a try.
[ModelImporter.cpp.zip](https://github.com/onnx/onnx-tensorrt/files/3532464/ModelImporter.cpp.zip)

**Comment by pango99** [comment]
- [ ] 

> 
> 
> @pango99 I modify importModel code in ModelImporter.cpp, and rcompile onnx-tensorrt(https://github.com/onnx/onnx-tensorrt v5.0)
> 
> ![WXWorkCapture_15665234078763](https://user-images.githubusercontent.com/7134030/63560207-c18cd580-c587-11e9-91a3-cb7d96b62522.png)
> 
> it works for me, you can have a try.
> [ModelImporter.cpp.zip](https://github.com/onnx/onnx-tensorrt/files/3532464/ModelImporter.cpp.zip)

Thanks zjd1988,so can I compile onnx-tensorrt on windows platform? and can I use the compiled module with nvidia tensorrt sdk directly?

**Comment by zjd1988** [comment]
I compile onnx-tensorrt on ubuntu16.04, but it might be works well on windows, refferd from https://github.com/onnx/onnx-tensorrt/issues/60 .

you need replace the old libs (in tensorrt sdk) with newly compiled, or  modify the LD_LIBRARY_PATH(add the path of onnx-tensorrt libs)

**Comment by pango99** [comment]
> 
> 
> I compile onnx-tensorrt on ubuntu16.04, but it might be works well on windows, refferd from #60 .
> 
> you need replace the old libs (in tensorrt sdk) with newly compiled, or modify the LD_LIBRARY_PATH(add the path of onnx-tensorrt libs)


OK,I'll try to compile few days later

**Comment by drormeir** [comment]
> @pango99 I modify importModel code in ModelImporter.cpp, and rcompile onnx-tensorrt(https://github.com/onnx/onnx-tensorrt v5.0)
> 
> ![WXWorkCapture_15665234078763](https://user-images.githubusercontent.com/7134030/63560207-c18cd580-c587-11e9-91a3-cb7d96b62522.png)
> 
> it works for me, you can have a try.
> [ModelImporter.cpp.zip](https://github.com/onnx/onnx-tensorrt/files/3532464/ModelImporter.cpp.zip)

I used your source code and now I get different assert error:

> While parsing node number 0 [Slice]:
3
ERROR: /home/ubuntu/projects/onnx-tensorrt/builtin_op_importers.cpp:1687 In function importSlice:
[6] Assertion failed: inputs.size() == 1


Any help would be appreciated.

**Comment by zjd1988** [comment]
Hi ＠dromeir .You can debug the onnx-tensorrt code step by step, to find out which layer assert.

After that,you can check the onnx-tensorrt suported ops from this link https://github.com/onnx/onnx-tensorrt/blob/master/operators.md

**Comment by ttdd11** [comment]
@pango99 Same issue with the parser. Ran onnx.checker.check_model(onnx_model) with no error. I'll try to build this on windows and check back. It may be the opset version that is causing this error for many.

**Comment by j-o-d-o** [comment]
As @ttdd11 said, get same error while the checker did not complain.

**Comment by j-o-d-o** [comment]
Tried using the changes from @drormeier but somehow non of my changes actually have an effect. Also the line number of the assert does not match the one of the ModelImporter.cpp I have.
That's what my cmake looks like:

```cmake
add_library(libnvonnxparser SHARED IMPORTED)
set_property(TARGET libnvonnxparser PROPERTY IMPORTED_LOCATION ${INSTALL_DIR}/onnx-tensorrt/dist/lib/libnvonnxparser.so)
add_library(libnvinfer SHARED IMPORTED)
set_property(TARGET libnvinfer PROPERTY IMPORTED_LOCATION $ENV{TRT_RELEASE}/lib/libnvinfer.so)
...
target_link_libraries(${PROJECT_NAME}
  ...
  libnvonnxparser
  libnvinfer
}
```

It seems that another ModelImporter.cpp is used than the one I am building.

**Comment by j-o-d-o** [comment]
Updating to the recent 7.0.0 release of TensorRT (including 7.0.0 onnx-tensorrt) fixed the whole thing.

**Comment by tcxia** [comment]
> * [ ]
> 
> > @pango99 I modify importModel code in ModelImporter.cpp, and rcompile onnx-tensorrt(https://github.com/onnx/onnx-tensorrt v5.0)
> > ![WXWorkCapture_15665234078763](https://user-images.githubusercontent.com/7134030/63560207-c18cd580-c587-11e9-91a3-cb7d96b62522.png)
> > it works for me, you can have a try.
> > [ModelImporter.cpp.zip](https://github.com/onnx/onnx-tensorrt/files/3532464/ModelImporter.cpp.zip)
> 
> Thanks zjd1988,so can I compile onnx-tensorrt on windows platform? and can I use the compiled module with nvidia tensorrt sdk directly?

i copy your code  and get error : ‘initializer_map’ was not declared in this scope

**Comment by zjd1988** [comment]
Hi @tcxia, which tensorrt version  you use?

**Comment by tcxia** [comment]
> Hi @tcxia, which tensorrt version you use?

tensorRT 5.1 cuda10.1

**Comment by zjd1988** [comment]
Hi @tcxia, I tested ModelImporter.cpp.zip with tensorRT5.0, I not sure ablout tensorRT5.1. could you try this with tensorRT5.0.

**Comment by Toku11** [comment]
I was facing same issue in tensor docker container, solution was sh /opt/tensorrt/install_opensource.sh

**Comment by kevinch-nv** [comment]
This issue was fixed in later TensorRT versions. If you are still having trouble with the current release version (7.1) please open another issue.

**Comment by austinmw** [comment]
@kevinch-nv Hi, I'm unable to upgrade my TRT version as I need to use CUDA 10.2. Is there any way to solve this issue with TensorRT 6.0.1? Or is it possible to upgrade beyond 6.0.1 with CUDA 10.2?

**Comment by SpongeBab** [comment]
```
Input filename:   ../data/model.onnx
ONNX IR version:  0.0.6
Opset version:    10
Producer name:    pytorch
Producer version: 1.9
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.6) than this parser was built against (0.0.3).
While parsing node number 0 [Conv]:
ERROR: ModelImporter.cpp:296 In function importModel:
[5] Assertion failed: tensors.count(input_name)
[07/02/2021-11:46:52] [E] Failed to parse onnx file
[07/02/2021-11:46:52] [E] Parsing model failed
[07/02/2021-11:46:52] [E] Engine could not be created
&&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=../data/model.onnx
```

same error.
**I think this is because pytorch version is too new.Or any producer you used is higher than tensorrt supported.**
May can try use the producer lower version.

**Comment by kevinch-nv** [comment]
This is a known issue with earlier TensorRT versions (I believe it affects up to TRT 6). Can you upgrade your TRT verison?

**Comment by seongkyun** [comment]
@tcxia , you have to change the ModelImporter.cpp file to the @zjd1988 's one.
The changed part is more.

**Comment by SBaokun** [comment]
> ```
> Input filename:   ../data/model.onnx
> ONNX IR version:  0.0.6
> Opset version:    10
> Producer name:    pytorch
> Producer version: 1.9
> Domain:
> Model version:    0
> Doc string:
> ----------------------------------------------------------------
> WARNING: ONNX model has a newer ir_version (0.0.6) than this parser was built against (0.0.3).
> While parsing node number 0 [Conv]:
> ERROR: ModelImporter.cpp:296 In function importModel:
> [5] Assertion failed: tensors.count(input_name)
> [07/02/2021-11:46:52] [E] Failed to parse onnx file
> [07/02/2021-11:46:52] [E] Parsing model failed
> [07/02/2021-11:46:52] [E] Engine could not be created
> &&&& FAILED TensorRT.trtexec # trtexec.exe --onnx=../data/model.onnx
> ```
> 
> same error. **I think this is because pytorch version is too new.Or any producer you used is higher than tensorrt supported.** May can try use the producer lower version.

I have the same problem as you, did you solve the problem?
