### ISSUE TITLE
[question] int8 mode support 

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx-tensorrt#20]
I looked the code, seems onnx-tensort int8 is not supported yet.
I am wondering which approach will work for the time being ? 

1. Use tensorrt 4.0.1 onnx parser, load the network in TRT network description, then 
   force int8 mode in builder. Will onnx-tensorrt runtime still be used here? If so, any requirement
   in runtime to support int8? 

2. convert onnx model to caffe model. Then caffe-> tensorrt int8

``` c++
} else if( model_dtype == nvinfer1::DataType::kINT8 ) {
      // TODO: Int8 support
      //trt_builder->setInt8Mode(true);
      cerr << "ERROR: Int8 mode not yet supported" << endl;
      return -5;
    }
```

**Comment by KellenSunderland** [comment]
Would love to see this worked on if there's bandwidth @cliffwoolley.  Not critical in terms of timeline, but we are doing some analysis/benchmarking and we're missing int8 perf numbers.

**Comment by MaratZakirov** [comment]
Any progress on that issue?

**Comment by kevinch-nv** [comment]
Thanks for the question. Our `trtexec` tool supports int8 optimization out of the box with parsing ONNX models(https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec). Please use this tool as we are planning to deprecated onnx2trt in the near future. If you have any issues running int8 with `trtexec`, feel free to reopen this issue.

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, we can help you solve quantization problems
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md
