### ISSUE TITLE
The problem of converting yolov3.onnx to yolov3.trt

### ISSUE THREAD

**Issue by lemonyhw** [onnx/onnx-tensorrt#213]
when i converted yolov3.onnx to yolov3.trt with onnx2trt yolov3_416.onnx -o yolov3.trt, then I met this problem.
![image](https://user-images.githubusercontent.com/20087640/61763991-224eb400-ae0a-11e9-92e4-1e5da437fa6c.png)

How to solve this problem?

**Comment by Fighting-JJ** [comment]
> when i converted yolov3.onnx to yolov3.trt with onnx2trt yolov3_416.onnx -o yolov3.trt, then I met this problem.
> ![image](https://user-images.githubusercontent.com/20087640/61763991-224eb400-ae0a-11e9-92e4-1e5da437fa6c.png)
> 
> How to solve this problem?

Have soloved it ? @lemonyhw

**Comment by jinfagang** [comment]
This is because onnx-tensorrt only supports opset up to 8, the newest one is opset10.

I logged every op inside yolov3 and maskrcnn. all ops supported in opset10, but onnx-tensorrt not update to that level.

Also, I think this repo is no longer maintained..... we'd better fork another one....

**Comment by kevinch-nv** [comment]
Closed due to inactivity. If this is still and issue, feel free the reopen.
