### ISSUE TITLE
[8] No importer registered for op: ATen

### ISSUE THREAD

**Issue by ajaysg** [onnx/onnx-tensorrt#217]
i am trying to convert a ONNX model to tensorrt. the ONNX model has **ATen** operator which the onnx parser does not support. Please do the needful.

**Comment by BeBeauty** [comment]
> i am trying to convert a ONNX model to tensorrt. the ONNX model has **ATen** operator which the onnx parser does not support. Please do the needful.

@ajaysg hi, have you soved the above problem? thx

**Comment by ajaysg** [comment]
not yet, the onnx parser which TensorRT uses does not support this operator yet.
You can check this operator support matrix by TensorRT.
https://github.com/onnx/onnx-tensorrt/blob/master/operators.md

**Comment by ajaysg** [comment]
@BeBeauty  are you using waveglow model?
