### ISSUE TITLE
build python wrapper error

### ISSUE THREAD

**Issue by ghost** [onnx/onnx-tensorrt#22]
While Build the Python wrappers and modules, I get the following error. Any ideas as to what could be the cause of this?
```
$ python setup.py build
running build
running build_py
running build_ext
building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
NvOnnxParser.h:46: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```

**Comment by granjanrak1** [comment]
Did you find the solution?

**Comment by manendranathshukla** [comment]
anyone got solution for this issue ?? please let me know

**Comment by chiehpower** [comment]
Same problem here.
```
$python3 setup.py build                 
                              
Namespace(action=['build'], build_lib=None, include_dirs=None)
running build
running build_py
running build_ext
building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
NvOnnxParser.h:213: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```
Is there any solution?
Thanks!!

**Comment by chiehpower** [comment]
> Same problem here.
> 
> ```
> $sudo python3 setup.py build                 
>                               
> Namespace(action=['build'], build_lib=None, include_dirs=None)
> running build
> running build_py
> running build_ext
> building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
> swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
> swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
> NvOnnxParser.h:213: Error: Syntax error in input(1).
> error: command 'swig' failed with exit status 1
> ```
> 
> Is there any solution?
> Thanks!!

Solved!!
Please check this issue.
#350  https://github.com/onnx/onnx-tensorrt/issues/350#issuecomment-569975247

**Comment by kevinch-nv** [comment]
This is a known issue and is being tracked in #298. Closing this issue as duplicate.
