### ISSUE TITLE
When should the parser be destroyed? 

### ISSUE THREAD

**Issue by WillBrennan** [onnx/onnx-tensorrt#222]
Hey; 

I've been using this library for sometime now in production C++ code. Its been fantastic so far, but I am getting an occasional crash. 

Could you clarify whether the lifetime of the parser should be tied with the builder/network or cuda engine / execution context? 

```cpp  

auto* builder = nvinfer1::createInferBuilder(logger);
builder->setMaxBatchSize(1);
builder->setMaxWorkspaceSize(1 << 20);

auto* network = builder->createNetwork();

auto* parser = nvonnxparser::createONNXParser(*network, gLogger);
parser->parseFromFile(onnx_filename, nvinfer1::ILogger::Severity::kWARNING);

auto* engine = builder->buildCudaEngine(*network);

// should we destroy parser here? 
parser->destroy();
network->destroy();
builder->destroy();

auto* context = engine->createExecutionContext();
context->enqueue(/* arguments */);

// or should we destroy the parser here?
context->destroy();
engine->destroy();
```

In the TensorRT documentation they say that custom layers must have a lifetime that spans their use in the engine, 

https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#extending

. It looks like in ImporterContext within ModelImporter you own the custom plugins (ResizeNearest ect) and add them to the network? So their lifetimes should be tied with the parser, which should outlive the cuda engine / execution context? 

This seems different to whats said here? 
https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#build_engine_c

Any help would be much appreciated.

**Comment by kevinch-nv** [comment]
Hi @WillBrennan, are you still experiencing crashes? In later TensorRT versions, we've moved the onnx-tensorrt specific plugins to the main TensorRT repo (see https://github.com/NVIDIA/TensorRT/). You can destroy the parser once the engine is built.

**Comment by WillBrennan** [comment]
Hi; 

Sorry; should have closed this issue some time ago! In our library that wraps tensorrt and does various bits of pre and post processing if you called components in a certain order it'd fail to call our `CudaDeviceNumberGuard` and not set the correct `cudaSetDevice`. Not related to the parser at all! 

> Hi @WillBrennan, are you still experiencing crashes? In later TensorRT versions, we've moved the onnx-tensorrt specific plugins to the main TensorRT repo (see https://github.com/NVIDIA/TensorRT/). You can destroy the parser once the engine is built.
