### ISSUE TITLE
A cmake error,failed to cmake

### ISSUE THREAD

**Issue by Zanderzt** [onnx/onnx-tensorrt#225]
_CMake Error at CMakeLists.txt:121 (add_subdirectory):
  The source directory

    /home/ab/tensorrt_tar/onnx-tensorrt/third_party/onnx

  does not contain a CMakeLists.txt file.

-- GPU_ARCH defined as 61. Generating CUDA code for SM 61
-- Found TensorRT headers at /home/ab/tensorrt_tar/TensorRT-5.1.5.0/include
-- Find TensorRT libs at /usr/lib/libnvinfer.so;/home/ab/tensorrt_tar/TensorRT-5.1.5.0/lib/libnvinfer_plugin.so
-- Configuring incomplete, errors occurred!
See also "/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeError.log"._

Hello,When I do `cmake .. -DTENSORRT_ROOT=/home/ab/tensorrt_tar/TensorRT-5.1.5.0 -DGPU_ARCHS="61"
` 
And this is the CmakeError.log
_Determining if the pthread_create exist failed with the following output:
Change Dir: /home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_66929/fast 
/usr/bin/make -f CMakeFiles/cmTC_66929.dir/build.make CMakeFiles/cmTC_66929.dir/build
make[1]: Entering directory '/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_66929.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIE   -o CMakeFiles/cmTC_66929.dir/CheckSymbolExists.c.o   -c /home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_66929
/home/ab/anaconda3/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_66929.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_66929.dir/CheckSymbolExists.c.o  -o cmTC_66929 
CMakeFiles/cmTC_66929.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text+0x1b)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_66929.dir/build.make:86: recipe for target 'cmTC_66929' failed
make[1]: *** [cmTC_66929] Error 1
make[1]: Leaving directory '/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_66929/fast' failed
make: *** [cmTC_66929/fast] Error 2

File /home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_025b8/fast 
/usr/bin/make -f CMakeFiles/cmTC_025b8.dir/build.make CMakeFiles/cmTC_025b8.dir/build
make[1]: Entering directory '/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_025b8.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE   -o CMakeFiles/cmTC_025b8.dir/CheckFunctionExists.c.o   -c /home/ab/anaconda3/lib/python3.7/site-packages/cmake/data/share/cmake-3.14/Modules/CheckFunctionExists.c
Linking C executable cmTC_025b8
/home/ab/anaconda3/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_025b8.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_025b8.dir/CheckFunctionExists.c.o  -o cmTC_025b8 -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_025b8.dir/build.make:86: recipe for target 'cmTC_025b8' failed
make[1]: *** [cmTC_025b8] Error 1
make[1]: Leaving directory '/home/ab/tensorrt_tar/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_025b8/fast' failed
make: *** [cmTC_025b8/fast] Error 2

_
This is the error,What need I do?

**Comment by Zanderzt** [comment]
I put the onnx file in the third party and it will build successfully.
onnx：https://github.com/onnx/onnx

**Comment by drormeir** [comment]
Sorry, I cannot understand how to resolve this issue. Can you please elaborate more about the solution?
