### ISSUE TITLE
can i got new layer info after convertd to tensorRT?

### ISSUE THREAD

**Issue by ryankang95** [onnx/onnx-tensorrt#226]
Hi all, Can I know which ops are merged by onnx2rt? And what optimization methods did tensorRT do?

**Comment by kevinch-nv** [comment]
You can run your model with trtexec (https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) with the verbose flag to dump out the optimizations and the layer fusions that TRT performed on your ONNX model.
