### ISSUE TITLE
make -j8 popping out the error

### ISSUE THREAD

**Issue by anish9** [onnx/onnx-tensorrt#23]
I was able to complete the first three steps:

> mkdir build
> cd build
> cmake .. -DTENSORRT_ROOT=/opt/tensorrt

in the fourth step 

> make -j8 

**I get the following error:**
____________________________________________________________________________________________________________
Error generating file
  /home/anish-fujitsu/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_FancyActivation.cu.o

CMakeFiles/nvonnxparser_plugin.dir/build.make:886: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_FancyActivation.cu.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_FancyActivation.cu.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yinghai** [comment]
Could you do `make VERBOSE=1` and paste the detailed error message that it outputs?

**Comment by anish9** [comment]
5 errors detected in the compilation of "/tmp/tmpxft_000016ac_00000000-7_Split.cpp1.ii".
-- Removing /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o
/usr/bin/cmake -E remove /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o
CMake Error at nvonnxparser_plugin_generated_Split.cu.o.cmake:266 (message):
  Error generating file
  /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_Split.cu.o


CMakeFiles/nvonnxparser_plugin.dir/build.make:1769: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_Split.cu.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_Split.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
-- Removing /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_ResizeNearest.cu.o
/usr/bin/cmake -E remove /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_ResizeNearest.cu.o
CMake Error at nvonnxparser_plugin_generated_ResizeNearest.cu.o.cmake:266 (message):
  Error generating file
  /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_ResizeNearest.cu.o


CMakeFiles/nvonnxparser_plugin.dir/build.make:1140: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_ResizeNearest.cu.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_ResizeNearest.cu.o] Error 1
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
-- Removing /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_FancyActivation.cu.o
/usr/bin/cmake -E remove /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_FancyActivation.cu.o
CMake Error at nvonnxparser_plugin_generated_FancyActivation.cu.o.cmake:266 (message):
  Error generating file
  /home/anish-macbook/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir//./nvonnxparser_plugin_generated_FancyActivation.cu.o


CMakeFiles/nvonnxparser_plugin.dir/build.make:886: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_FancyActivation.cu.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_FancyActivation.cu.o] Error 1
make[2]: Leaving directory '/home/anish-macbook/onnx-tensorrt/build'
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
make[1]: Leaving directory '/home/anish-macbook/onnx-tensorrt/build'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by anish9** [comment]
hi yinghai, can you figure out what could be the reason???

**Comment by gr8Adakron** [comment]
@yinghai Is it okay to install it with Tensorrt-4?

**Comment by yinghai** [comment]
@anish9 Installing with TensorRT-4.0 is OK as I just tried. Regarding your compilation error, I suspect your CUDA version is too old. We require at least CUDA 8.0. Here is a similar issue that has been reported: https://github.com/BVLC/caffe/issues/4046

**Comment by anish9** [comment]
@yinghai  we checked our CUDA version and its 9.0

**Comment by yinghai** [comment]
Try adding `-D_FORCE_INLINES` to `NVCCFLAGS` as suggested in BVLC/caffe#4046?

**Comment by Faldict** [comment]
I guess your `-DTENSORRT_ROOT` path is incorrect. In my case, the path is `/usr/src/tensorrt`.

**Comment by yinghai** [comment]
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2015 NVIDIA Corporation
> Built on Tue_Aug_11_14:27:32_CDT_2015
> Cuda compilation tools, release 7.5, V7.5.17

You nvcc is too old. Are you sure your CUDA 9.0 is being invoked?

**Comment by anish9** [comment]
_**we have found the solution for the above error**_
make sure you are updated to the latest CUDA and nvcc versions and not only that ensure the right nvcc is invoked on a call.

**Files we used on the fixing of the following error:**

1. libcudnn7-dev_7.1.4.18-1+cuda9.2_amd64.deb
2. libcudnn7-doc_7.1.4.18-1cuda9.2_amd64.deb
3. nv-tensorrt-repo-ubuntu1604-cuda9.2-ga-trt4.0.1.6-20180612_1-1_amd64.deb
4. cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
5. libcudnn7_7.1.4.18-1+cuda9.2_amd64.deb

**Comment by anish9** [comment]
Fixes #23
