### ISSUE TITLE
Branch for TensorRT 4.0

### ISSUE THREAD

**Issue by fferroni** [onnx/onnx-tensorrt#231]
Hello,

What branch of this repository is acceptable to be used for TensorRT4? I believe there were some API changes between 4 and 5, so I wonder whether I can just use current master, or the TRT5 branch?

Best

**Comment by kevinch-nv** [comment]
TensorRT versions < 5.0 will not be maintained on this repository. My recommendation is to use the latest version of TensorRT in order to use the latest features and get the latest bug fixes. Closing this issue.
