### ISSUE TITLE
feeding in np arrays of same shape and type, one gives an error...

### ISSUE THREAD

**Issue by paapu88** [onnx/onnx-tensorrt#237]
Dear All,
I'm running jetson nano and trying to use onnx-tensorrt as instructed in
https://github.com/onnx/onnx-tensorrt#onnx-python-backend-usage

Problem: when I feed the neural net with a random numpy array, it  produces results,
but when I feed in a real scaled image I get an error.
(both numpy arrays frame and input_data are between zero and one...)

code:
```
frame = myio.get_image_for_neural_net()
model = onnx.load(getDataFile(pars['onnxFile']))
engine = backend.prepare(model, device='CUDA:0')
input_data = np.random.random(size=(1, 3, 320, 320)).astype(np.float32)
print("input data:", input_data.shape, type(input_data), input_data.dtype)
output_data = engine.run(input_data)[0]
frame = np.moveaxis(frame, -1, 1).astype(np.float32)
print("frame",  frame.shape, type(frame), frame.dtype)
output_data = engine.run(frame)[0]
```
output 

> input data: (1, 3, 320, 320) <class 'numpy.ndarray'> float32
frame (1, 3, 320, 320) <class 'numpy.ndarray'> float32

error:
>  File "predictWithTensorRT.py", line 57, in <module>
    output_data = engine.run(frame)[0]
  File "/home/dlinano/.local/lib/python3.6/site-packages/onnx_tensorrt/backend.py", line 149, in run
    outputs = self.engine.run(inputs)
  File "/home/dlinano/.local/lib/python3.6/site-packages/onnx_tensorrt/tensorrt_engine.py", line 154, in run
    input_binding_array.set_async(input_array, self.stream)
  File "/home/dlinano/.local/lib/python3.6/site-packages/pycuda/gpuarray.py", line 263, in set_async
    return self.set(ary, async_=True, stream=stream)
  File "/home/dlinano/.local/lib/python3.6/site-packages/pycuda/gpuarray.py", line 260, in set
    _memcpy_discontig(self, ary, async_=async_, stream=stream)
  File "/home/dlinano/.local/lib/python3.6/site-packages/pycuda/gpuarray.py", line 1281, in _memcpy_discontig
    raise ValueError("src and dst must have same order")
ValueError: src and dst must have same order

I cannot make any sense of this, hope someone could help...

Terveisin, Markus

**Comment by laggui** [comment]
Sounds like the this is related to contiguous memory storage order. The arrays can either be stored in row-major (the default for numpy arrays) or column-major (see [this wiki page](https://en.wikipedia.org/wiki/Row-_and_column-major_order) for more info).

Perhaps all you need to do is this:
```python
# Convert the frame to row-major order
frame = np.array(frame, dtype=frame.dtype, order='C')
```

**Comment by paapu88** [comment]
Wov! 
I would have never figured out this by myself.
Thanks!!! It is working now.
