### ISSUE TITLE
Concat of kINT32 not supported

### ISSUE THREAD

**Issue by igolan89** [onnx/onnx-tensorrt#245]
In https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L687, there is an assertion for the input types not being `kINT32`, although it is supported by TensorRT as stated in their documentation:
https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#concatenation-layer
"All input tensors must either be non-INT32 type or all must be INT32 type".

**Comment by jinfagang** [comment]
Apart from this, Cast operation also can not cast into INT. But in some situation we really need Cast into INT.

**Comment by kevinch-nv** [comment]
This has been fixed in the latest TensorRT version (7.1). Closing.
