### ISSUE TITLE
nv_onnx_runtime_module is not defined

### ISSUE THREAD

**Issue by vlad3996** [onnx/onnx-tensorrt#246]
Failed to run `python setup.py install` from branch master.

I think you delete few extra lines in setup.py 

https://github.com/onnx/onnx-tensorrt/commit/2db2ae9ca6fb2387abb48efbd4d15d7c847e3bf9#diff-2eeaed663bd0d25b7e608891384b7298L63

**Comment by lazykyama** [comment]
I also faced the same issue. I guess `nv_onnx_runtime_module` should be removed from the line below.
https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L103

After removing the line, I succeeded building, installing and running `onnx_backend_test.py`.
