### ISSUE TITLE
onnx2trt can not convert model with F.interpolate

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#250]
I have a model which can export to onnx, when onnx2trt, everytime I enable a function like this:

```
  up3 = F.interpolate(output3, size=[output2.size(2), output2.size(3)], mode="nearest")
        output2 = output2 + up3
```

which is part of FPN. it will got error:

```
[8] Assertion failed: axis >= 0 && axis < nbDims
```

But once I comment out that function line, re export to onnx, and then onnx2trt, will convert success.

So my question is:

why this function can not work, what should I do to make it exportable with onnx2trt???

**Comment by SuJiaKuan** [comment]
According to the [comment](https://github.com/onnx/onnx-tensorrt/issues/5#issuecomment-493037938) in #5, you can try something like this:

```python
up3 = F.interpolate(output3, size=[int(output2.size(2)), int(output2.size(3))], mode="nearest")
```
