### ISSUE TITLE
onnx2trt: error while loading shared libraries: libnvinfer.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#257]
```
onnx2trt: error while loading shared libraries: libnvinfer.so.6: cannot open shared object file: No such file or directory

```

Build success, can not call `onnx2trt` on Ubuntu 18.04

**Comment by heizie** [comment]
i've also met a same problem.
just want to mark here, in case someone need it

we need to Add the absolute path to the TensorRTlib directory to the environment variable LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TensorRT-${version}/lib>
