### ISSUE TITLE
Couldn't find index page for 'tensorrt' (maybe misspelled?)

### ISSUE THREAD

**Issue by anish9** [onnx/onnx-tensorrt#26]
`python setup.py build`

- the above step is successfully completed

- but error is generated on the below file when installing the setup

`python setup.py install` 
```
Searching for tensorrt>=3.0.0
Reading https://pypi.org/simple/tensorrt/
Couldn't find index page for 'tensorrt' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for tensorrt>=3.0.0
error: Could not find suitable distribution for Requirement.parse('tensorrt>=3.0.0')
```

### we have already installed tensorrt 4.0.1 based on the nvidia's official documentation but still we face the above error.

**Comment by anish9** [comment]
@ezyang @zdevito @hmansell  anyone please help me.

**Comment by anish9** [comment]
@n8886919  the below link should help
https://github.com/onnx/onnx-tensorrt/issues/23#issuecomment-404838651

**Comment by wahajahmad** [comment]
I had the same problem and in may case, it was due to missing python binding of TensorRT
You can install it for Python2 with 
`sudo apt-get install python-libnvinfer`
