### ISSUE TITLE
When will dynamic inputs will be supported in onnx tensorrt?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#265]
Hi, Since TensorRT 6.0 already supported dynamic input.
When these model with dynamic input will be supported? Such as maskrcnn fasterrcnn etc.

**Comment by kevinch-nv** [comment]
Dynamic inputs have been supported since TensorRT 6.0, and our support has been continuously improving across releases. For support for specific models, please open specific issues for them.
