### ISSUE TITLE
When will NMS and RoiAlign will be supported?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#289]
Does there any walk around for supporting NMS and RoIAlign inside onnx-tensorrt?

the onnx optset 10 had added these 2 ops a long time ago.

**Comment by basaltzhang** [comment]
same question

**Comment by ledinhtri97** [comment]
+1

**Comment by kevinch-nv** [comment]
Closing this as a duplicate of #267
