### ISSUE TITLE
How to install onnx_tensorrt and use onnx python backend?

### ISSUE THREAD

**Issue by Hellcat1005** [onnx/onnx-tensorrt#298]
Anyone can tell me how to install onnx_tensorrt? I have installed tensorrt 6.0.1.5 and I also followed the instruction from the tensorrt master branch. But there is no onnx_tensorrt in the lib.

**Comment by felixplum** [comment]
Have you tried updating your cached libs, i.e. ran `ldconfig`?

**Comment by 22manuguns** [comment]
I ran into this issue also, I am not able to use onnx_tensorrt, which lib should I expect it to be in so I can verify it is built?

**Comment by rjknight** [comment]
looking at the docker file I think you will need to run 'python setup.py build && python setup.py install to get onnx_tensorrt to import correctly
```
RUN rm -rf build/ && \
    mkdir -p build && \
    cd build && \
    cmake -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include/ .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd .. && \
    # For python2.
    python2 setup.py build && \
    python2 setup.py install && \
    # For python3.
    python3 setup.py build && \
    python3 setup.py install && \
    rm -rf ./build/
```

**Comment by JiamingSuen** [comment]
I believe the process to build the python bindings outside a docker container should be noted in the README, or at least make it clear that it's recommended to use this repo with docker.

**Comment by sl1pkn07** [comment]
Hi

how to add `--root="${pkgdir}" `? i wnat install the python modules into "$DESTDIR/usr/foo" directory

~~~
usage: setup.py [-h] [--build-lib BUILD_LIB] [--include-dirs INCLUDE_DIRS] [action [action ...]]
setup.py: error: unrecognized arguments: --root=/tmp/makepkg/sl1-onnx-tensorrt-git/pkg/sl1-onnx-tensorrt-git
~~~

greetings

**Comment by sl1pkn07** [comment]
finally.

`python setup.py bdist` && cd foo && bsdtar -xf <sourcepath>dist/*.tar.gz`

**Comment by brianegge** [comment]
I can build the C++ libraries fine, but can't install the python bindings. 
 
```
$ python3 setup.py build
Namespace(action=['build'], build_lib=None, include_dirs=None)
running build
running build_py
running build_ext
building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
NvOnnxParser.h:213: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```

Running just swig:
```
$ swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp -v nv_onnx_parser_bindings.i
Language subdirectory: python
Search paths:
   ./
   ./swig_lib/python/
   /usr/share/swig3.0/python/
   ./swig_lib/
   /usr/share/swig3.0/
Preprocessing...
Starting language-specific parse...
NvOnnxParser.h:213: Error: Syntax error in input(1).
```

**Comment by shubhamsidhwa** [comment]
> I can build the C++ libraries fine, but can't install the python bindings.
> 
> ```
> $ python3 setup.py build
> Namespace(action=['build'], build_lib=None, include_dirs=None)
> running build
> running build_py
> running build_ext
> building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
> swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
> swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
> NvOnnxParser.h:213: Error: Syntax error in input(1).
> error: command 'swig' failed with exit status 1
> ```
> 
> Running just swig:
> 
> ```
> $ swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp -v nv_onnx_parser_bindings.i
> Language subdirectory: python
> Search paths:
>    ./
>    ./swig_lib/python/
>    /usr/share/swig3.0/python/
>    ./swig_lib/
>    /usr/share/swig3.0/
> Preprocessing...
> Starting language-specific parse...
> NvOnnxParser.h:213: Error: Syntax error in input(1).
> ```

Were you able to resolve this issue ?

**Comment by mk-nvidia** [comment]
This is a bug at our end, we're taking a look at this issue.

**Comment by kevinch-nv** [comment]
The installation instructions have been updated in #559 - see the [updated instructions](https://github.com/onnx/onnx-tensorrt#python-modules) for information on installing the python backend libraries. Closing this issue - if you are still having issues feel free to open another one.
