### ISSUE TITLE
please list supported ONNX version

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx-tensorrt#3]
Please list supported ONNX version. Or list what's not supported. I found
onnx "Shape" op is not supported.

[8] No importer registered for op: Shape

**Comment by yinghai** [comment]
Hi, which model are you running? Is it from ONNX model zoo?

**Comment by qigtang** [comment]
No. It is pytorch retinanet onnx file.
If you check out this repository,  version 1a96b1d
https://github.com/qigtang/pytorch-retinanet.git

I modified bilinear upsample to nearest so it can be exported to onnx. 
run "python retinanet.py" to save the onnx file, then run

onnx2trt retinanet.onnx -t out.txt

----------------------------------------------------------------
Input filename:   retinanet.onnx
ONNX IR version:  0.0.3
Opset version:    6
Producer name:    pytorch
Producer version: 0.3
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
Writing ONNX model (without weights) as text to out.txt
Parsing model
While parsing node number 203 [Shape -> "556"]:
ERROR: /opt/onnx2trt/ModelImporter.cpp:114 In function importNode:
[8] No importer registered for op: Shape

I am wondering whether torch.onnx._export should be enhanced to support static export. Like if the original dynamic graph has operation to query Tensor shape, do reshape etc, maybe we should replace query part with constant, potentially merge the (shape, slice, squeeze, unsqueeze, concat) operations into one constant tensor (see following picture).

![merge_shape_operation](https://user-images.githubusercontent.com/7813095/39896648-d3625136-5463-11e8-81c0-94f54fcf844e.jpg)

**Comment by yinghai** [comment]
Hmm, I don't know about shape, but we do support reshape. @houseroad, what does shape in onnx do?

**Comment by houseroad** [comment]
The `Shape` Operator outputs the shape of the input.

**Comment by Eddiesyn** [comment]
I also has the same error.. I was transferring an onnx model to tensorrt. The onnx model comes from pytorch pretrained model. I tried standard resnet50, and use The *torch.onnx.export()* function. When parsing this generated onnx model, the error is same as [:](https://github.com/onnx/onnx-tensorrt/issues/3#issue-322040821) 
[8] No importer registered for op: Shape

I have the same onnx version: 

**ONNX IR version: 0.0.3
Opset version: 6
Producer name: pytorch
Producer version: 0.3
Domain:
Model version: 0
Doc string:**

and i use tensorrt5.0, whose developer guide says: 
> The ONNX Parser shipped with TensorRT 5.0 RC supports ONNX IR (Intermediate Representation)version 0.0.3, opeset version 7.

**Comment by mgolub2** [comment]
I have the same issue as well:

Converting onnx to GIE model...
----------------------------------------------------------------
Input filename:   ../dense201.onnx
ONNX IR version:  0.0.3
Opset version:    9
Producer name:    pytorch
Producer version: 0.4
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
While parsing node number 708 [Shape -> "1918"]:
ERROR: /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.0/parsers/onnxOpenSource/ModelImporter.cpp:116 In function importNode:
[8] No importer registered for op: Shape
ERROR: failed to parse onnx file

**Comment by benbarsdell** [comment]
Can you try building onnx-tensorrt from source? There may be other problems too, but at least the shape operator is definitely implemented:
https://github.com/onnx/onnx-tensorrt/blob/2abb940eccfe50b8d0e785a2e868d7e2ba98a3db/builtin_op_importers.cpp#L1483

**Comment by mgolub2** [comment]
Oddly, the Nvidia provided onnx-tensorrt parser has different API than the current onnx-tensorrt GitHub. 

Using onnx2trt command instead of my program, I know get this error instead:
/usr/local/bin/onnx2trt ../dense201.onnx
----------------------------------------------------------------
Input filename:   ../dense201.onnx
ONNX IR version:  0.0.3
Opset version:    9
Producer name:    pytorch
Producer version: 0.4
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
Parsing model
While parsing node number 709 [Gather -> "1919"]:
ERROR: /home/vagrant/onnx-tensorrt/ModelImporter.cpp:141 In function importNode:
[8] No importer registered for op: Gather

Which someone else also ran into here I believe: https://github.com/onnx/onnx-tensorrt/issues/66

**Comment by bpinaya** [comment]
Same would go for a FCNVGG I think, on ONNX 1.3 with onnx-tensorrt built from source I get:
```
----------------------------------------------------------------
Input filename:   fcnvgg.onnx
ONNX IR version:  0.0.3
Opset version:    9
Producer name:    pytorch
Producer version: 0.4
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
While parsing node number 42 [Slice -> "81"]:
ERROR: /home/bpinaya/onnx-tensorrt/ModelImporter.cpp:141 In function importNode:
[8] No importer registered for op: Slice
```

**Comment by ligonzheng** [comment]
I get the same error : No importer registered for op: Slice ! 
Is there a solution for this ?

**Comment by bpinaya** [comment]
@ligonzheng you can merge this PR locally #82 . It works but there is no batching slice support on trt.

**Comment by ankmathur96** [comment]
Bump on this issue - it breaks Resnet50 from torchvision as well

**Comment by oftenliu** [comment]
hello, i meet it too,is solved?

**Comment by bpinaya** [comment]
@oftenliu , depends on which layer, Slice is supported.

**Comment by oftenliu** [comment]
the layer is Shape,and i update to tensorrt5.1,  the shape is supported,but i meet a new error :  Unsupported ONNX data type: INT64 (7)

**Comment by bpinaya** [comment]
@oftenliu it's been mentioned here #5 , int64 is not supported, which framework are you importing from? Depending on which model and else but probably you don't need int64.
If your DL framework is python based you can cast the int64 to `int(your_int64_variable)`

**Comment by oftenliu** [comment]
i convert my pytorch model(resnet50) to onnx, then to tensorrt

**Comment by kevinch-nv** [comment]
We've added an [operators](https://github.com/onnx/onnx-tensorrt/blob/master/operators.md) list for TensorRT's support matrix in later versions. Please refer to that for the latest up-to-date information on support.

**Comment by chandu1263** [comment]
ONNX IR version:  0.0.6
Opset version:    12
Producer name:    pytorch
Producer version: 1.7
Domain:
Model version:    0
Doc string:
 
Is this compatible with trt7.0.0?
