### ISSUE TITLE
When will Equal supported in onnx-tensorrt?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#308]
No if our model contains this operation:

```
            keep = (hmax == hm).float()
```
anywhere we want using `==` operation, it will not supported when convert to trt engine, error like:

```
Parsing model
While parsing node number 361 [Equal -> "1016"]:
ERROR: l/onnx-tensorrt/ModelImporter.cpp:143 In function importNode:
[8] No importer registered for op: Equal

```

However, this is really essential in many models. When will this op supported anyway?

**Comment by jinfagang** [comment]
@kevinch-nv Does there any plan on support Equal, Greater inside onnx-tensorrt as a plugin?

This is very useful when building a modern model.

**Comment by reymondzzzz** [comment]
U can workaround with
```

**Comment by kevinch-nv** [comment]
These boolean operators have been supported since TensorRT 7. Closing this issue.
