### ISSUE TITLE
Is onnx_tensorrt support for compile on nvidia-jetson-xavier?

### ISSUE THREAD

**Issue by SmallMunich** [onnx/onnx-tensorrt#319]
Recently, I want to compile this onnx_tensorrt library on Xavier ARM, Is it supported ?

**Comment by georgetseng1128** [comment]
@SmallMunich So onnx-tensorrt can support Xavier?

**Comment by SmallMunich** [comment]
> @SmallMunich So onnx-tensorrt can support Xavier?

yes, compile origin code passed

**Comment by georgetseng1128** [comment]
@SmallMunich Thank for your reply.
