### ISSUE TITLE
How to use FP16 ot INT8?

### ISSUE THREAD

**Issue by ChengshuLi** [onnx/onnx-tensorrt#32]
Hi,

I was trying to use FP16 and INT8. 

I understand this is how you prepare a FP32 model. 
```
model = onnx.load("/path/to/model.onnx")
engine = backend.prepare(model, device='CUDA:1')
input_data = np.random.random(size=(32, 3, 224, 224)).astype(np.float32)
```

I tried this, but it didn't work. 
```
model = onnx.load("/path/to/model.onnx")
engine = backend.prepare(model, device='CUDA:1', dtype=np.float16)
input_data = np.random.random(size=(32, 3, 224, 224)).astype(np.float16)
```

Any help will be greatly appreciated. Thanks! 

@yinghai

**Comment by yinghai** [comment]
I don't think it's fully supported right now. What's the error message?

**Comment by ChengshuLi** [comment]
I think I kind of know what the problem is.

Here is my output when I ran:
 `onnx2trt my_model.onnx -o my_engine.trt -d 16`

```
----------------------------------------------------------------
Input filename:   drn.onnx
ONNX IR version:  0.0.3
Opset version:    6
Producer name:    pytorch
Producer version: 0.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
Building TensorRT engine, FP16 available:0
    Max batch size:     32
    Max workspace size: 1024 MiB
```
The output model is the same as the Float32 one. 

I noticed that `bool fp16 = trt_builder->platformHasFastFp16();` is false for me. I am pretty new to TensorRT so this might be a stupid question. But does this depend on my GPU? I am currently using Titan X (Pascal).

**Comment by ChengshuLi** [comment]
I tried to use Titan V. Now I think FP16 is available. However, it gave me an error:
```
----------------------------------------------------------------
Input filename:   drn.onnx
ONNX IR version:  0.0.3
Opset version:    6
Producer name:    pytorch
Producer version: 0.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
Building TensorRT engine, FP16 available:1
    Max batch size:     32
    Max workspace size: 1024 MiB
[2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
[2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
fish: “onnx2trt drn.onnx -o drn_float1…” terminated by signal SIGABRT (Abort)
```

**Comment by yinghai** [comment]
Is it possible to share a minimally reproducible model with us? It doesn't necessarily need to be the real model and weights can be randomized, as long as it can help us reproduce the issue.

**Comment by ChengshuLi** [comment]
@yinghai  Thanks a lot for helping out. 

I will try to walk you through what I have done: 

The original pytorch model is [here](https://drive.google.com/file/d/1cXKoG5k0rO8UZ-cQx2U_iggS4kiBgOYg/view?usp=sharing)
The inference time for this pytorch model is **~0.17s / image** on Titan X. I tried to use TensorRT to accelerate it. 

First of all, I converted the Pytorch model to ONNX model using the code below because I didn't want to create the model definition in the TensorRT format from scratch.
```
import torch
from segment import DRNSeg

weights = 'drn-d-105_ms_cityscapes.pth'
model = DRNSeg('drn_d_105', 19, pretrained_model=None, pretrained=False)
model.load_state_dict(torch.load(weights))
dummy_input = torch.randn(1, 3, 512, 1024, requires_grad=False)
torch.onnx.export(model, dummy_input, "drn.onnx")
```
The converted ONNX model is [here](https://drive.google.com/open?id=1de1j8fyowi8RucnWM5Q4L8s8BHa0wf1U). 

Then I ran `onnx2trt drn.onnx -o drn.trt` successfully and got `drn.trt`. I followed NVIDIA's TensorRT tutorial to load the engine (i.e. drn.trt file) and to run inference on a sample image. 

The segmentation result looks correct, **which is why I believe the entire conversion process is correct (pytorch -> ONNX -> TensorRT engine trt file)**. However, the running speed is slower than before at **~0.33s / image** on Titan X. It ran even slower at **~0.42s / image** on Titan V. **I didn't quite get why TensorRT will slow things down. Do you have some ideas?** 

Therefore, I wanted to try FP16 to further speed up the model. On Titan X, the conversion `onnx2trt` went through but the model was still using FP32 because https://github.com/onnx/onnx-tensorrt/blob/f6f413852388e0eb37447b02fa170a9cdf89b0cc/main.cpp#L298 is false.

On Titan V, the conversion `onnx2trt` failed and here is the error message again.

**Comment by yinghai** [comment]
> However, the running speed is slower than before at ~0.33s / image on Titan X. It ran even slower at ~0.42s / image on Titan V. I didn't quite get why TensorRT will slow things down. Do you have some ideas?

This sounds strange. How did you run the TRT engine?

**Comment by yinghai** [comment]
Time measure doesn't seem to be correct as `enquque` is just to submit a task to CUDA stream. Is your image size always the same? If so, you can avoid allocating memory for each inference.

**Comment by ChengshuLi** [comment]
@yinghai  Thanks for your info. 

Yes the image size is always the same. What do you think is the best way to measure inference time? Any suggestion? 

Also, any idea on why FP16 conversion fails on Titan V? 

Thanks!

**Comment by yinghai** [comment]
You should measure it after `stream.synchronize()`.

**Comment by ChengshuLi** [comment]
@yinghai 

Thanks! Unfortunately the result is the same. The inference is still ~0.42s / image on Titan V whereas the original pytorch model runs at ~0.17s / image.

**Comment by Faldict** [comment]
@ChengshuLi I've got stuck in the same problem, while I used MXNet models. Here's my code to measure TensorRT's inference time.

```
ts = time.time()
stream = cuda.Stream()
cuda.memcpy_htod_async(d_input, data, stream)
context.enqueue(batch_size, bindings, stream.handle, None)
cuda.memcpy_dtoh_async(output, d_output, stream)
stream.synchronize()
te = time.time()
```
And it seems that TensorRT even retarded the inference.

**Comment by poorneshwaran** [comment]
> 
> 
> @yinghai Thanks a lot for helping out.
> 
> I will try to walk you through what I have done:
> 
> The original semantic segmentation pytorch model is [here](https://drive.google.com/file/d/1cXKoG5k0rO8UZ-cQx2U_iggS4kiBgOYg/view?usp=sharing)
> The inference time for this pytorch model is **~0.17s / image** on Titan X. I tried to use TensorRT to accelerate it.
> 
> First of all, I converted the Pytorch model to ONNX model using the code below because I didn't want to create the model definition in the TensorRT format from scratch.
> 
> ```
> import torch
> from segment import DRNSeg
> 
> weights = 'drn-d-105_ms_cityscapes.pth'
> model = DRNSeg('drn_d_105', 19, pretrained_model=None, pretrained=False)
> model.load_state_dict(torch.load(weights))
> dummy_input = torch.randn(1, 3, 512, 1024, requires_grad=False)
> torch.onnx.export(model, dummy_input, "drn.onnx")
> ```
> 
> The converted ONNX model is [here](https://drive.google.com/open?id=1de1j8fyowi8RucnWM5Q4L8s8BHa0wf1U).
> 
> Then I ran `onnx2trt drn.onnx -o drn.trt` successfully and got `drn.trt`. I followed NVIDIA's TensorRT tutorial to load the engine (i.e. drn.trt file) and to run inference on a sample image.
> 
> The segmentation result looks correct, **which is why I believe the entire conversion process is correct (pytorch -> ONNX -> TensorRT engine trt file)**. However, the running speed is slower than before at **~0.33s / image** on Titan X. It ran even slower at **~0.42s / image** on Titan V. **I didn't quite get why TensorRT will slow things down. Do you have some ideas?**
> 
> Therefore, I wanted to try FP16 to further speed up the model. On Titan X, the conversion `onnx2trt` went through but the model was still using FP32 because
> 
> https://github.com/onnx/onnx-tensorrt/blob/f6f413852388e0eb37447b02fa170a9cdf89b0cc/main.cpp#L298
> is false.
> 
> On Titan V, the conversion `onnx2trt` failed and here is the error message again.
> 
> ```
> ----------------------------------------------------------------
> Input filename:   drn.onnx
> ONNX IR version:  0.0.3
> Opset version:    6
> Producer name:    pytorch
> Producer version: 0.3
> Domain:           
> Model version:    0
> Doc string:       
> ----------------------------------------------------------------
> Parsing model
> Building TensorRT engine, FP16 available:1
>     Max batch size:     32
>     Max workspace size: 1024 MiB
> [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to create object
> fish: “onnx2trt drn.onnx -o drn_float1…” terminated by signal SIGABRT (Abort)
> ```
> 
> Sorry for the long message. I hope this clarifies my situation. Thanks again for your generous help.

I'm trying to use your method. And i got error like 

/onnx/onnx/onnx_onnx2trt_onnx .pb.h:12:2: error: #error This file was generated by a newer version of protoc w hich is                                                                           #error This file was generated by a newer version of protoc which is  
while make -j8.  think this is protoc version error. may i know what version did you use

**Comment by poorneshwaran** [comment]
> > @yinghai Thanks a lot for helping out.
> > I will try to walk you through what I have done:
> > The original semantic segmentation pytorch model is [here](https://drive.google.com/file/d/1cXKoG5k0rO8UZ-cQx2U_iggS4kiBgOYg/view?usp=sharing)
> > The inference time for this pytorch model is **~0.17s / image** on Titan X. I tried to use TensorRT to accelerate it.
> > First of all, I converted the Pytorch model to ONNX model using the code below because I didn't want to create the model definition in the TensorRT format from scratch.
> > ```
> > import torch
> > from segment import DRNSeg
> > 
> > weights = 'drn-d-105_ms_cityscapes.pth'
> > model = DRNSeg('drn_d_105', 19, pretrained_model=None, pretrained=False)
> > model.load_state_dict(torch.load(weights))
> > dummy_input = torch.randn(1, 3, 512, 1024, requires_grad=False)
> > torch.onnx.export(model, dummy_input, "drn.onnx")
> > ```
> > 
> > 
> > The converted ONNX model is [here](https://drive.google.com/open?id=1de1j8fyowi8RucnWM5Q4L8s8BHa0wf1U).
> > Then I ran `onnx2trt drn.onnx -o drn.trt` successfully and got `drn.trt`. I followed NVIDIA's TensorRT tutorial to load the engine (i.e. drn.trt file) and to run inference on a sample image.
> > The segmentation result looks correct, **which is why I believe the entire conversion process is correct (pytorch -> ONNX -> TensorRT engine trt file)**. However, the running speed is slower than before at **~0.33s / image** on Titan X. It ran even slower at **~0.42s / image** on Titan V. **I didn't quite get why TensorRT will slow things down. Do you have some ideas?**
> > Therefore, I wanted to try FP16 to further speed up the model. On Titan X, the conversion `onnx2trt` went through but the model was still using FP32 because
> > https://github.com/onnx/onnx-tensorrt/blob/f6f413852388e0eb37447b02fa170a9cdf89b0cc/main.cpp#L298
> > 
> > is false.
> > On Titan V, the conversion `onnx2trt` failed and here is the error message again.
> > ```
> > ----------------------------------------------------------------
> > Input filename:   drn.onnx
> > ONNX IR version:  0.0.3
> > Opset version:    6
> > Producer name:    pytorch
> > Producer version: 0.3
> > Domain:           
> > Model version:    0
> > Doc string:       
> > ----------------------------------------------------------------
> > Parsing model
> > Building TensorRT engine, FP16 available:1
> >     Max batch size:     32
> >     Max workspace size: 1024 MiB
> > [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> > [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> > terminate called after throwing an instance of 'std::runtime_error'
> >   what():  Failed to create object
> > fish: “onnx2trt drn.onnx -o drn_float1…” terminated by signal SIGABRT (Abort)
> > ```
> > 
> > 
> > Sorry for the long message. I hope this clarifies my situation. Thanks again for your generous help.
> 
> I'm trying to use your method. And i got error like
> 
> /onnx/onnx/onnx_onnx2trt_onnx .pb.h:12:2: error: #error This file was generated by a newer version of protoc w hich is #error This file was generated by a newer version of protoc which is
> while make -j8. I think , this is protoc version error. May i know what version did you use and please share for protoc installation.

I Solved the Installation Problem ..

Now I followed your code & I got error like segmentation fault (core dumped) on tensorrt 5.1.2    

can you please help me with that..

**Comment by liuchang8am** [comment]
any updates?
Same issue here, no speed gain from Pytorch->ONNX->TRT

**Comment by poorneshwaran** [comment]
> 
> 
> > > @yinghai Thanks a lot for helping out.
> > > I will try to walk you through what I have done:
> > > The original semantic segmentation pytorch model is [here](https://drive.google.com/file/d/1cXKoG5k0rO8UZ-cQx2U_iggS4kiBgOYg/view?usp=sharing)
> > > The inference time for this pytorch model is **~0.17s / image** on Titan X. I tried to use TensorRT to accelerate it.
> > > First of all, I converted the Pytorch model to ONNX model using the code below because I didn't want to create the model definition in the TensorRT format from scratch.
> > > ```
> > > import torch
> > > from segment import DRNSeg
> > > 
> > > weights = 'drn-d-105_ms_cityscapes.pth'
> > > model = DRNSeg('drn_d_105', 19, pretrained_model=None, pretrained=False)
> > > model.load_state_dict(torch.load(weights))
> > > dummy_input = torch.randn(1, 3, 512, 1024, requires_grad=False)
> > > torch.onnx.export(model, dummy_input, "drn.onnx")
> > > ```
> > > 
> > > 
> > > The converted ONNX model is [here](https://drive.google.com/open?id=1de1j8fyowi8RucnWM5Q4L8s8BHa0wf1U).
> > > Then I ran `onnx2trt drn.onnx -o drn.trt` successfully and got `drn.trt`. I followed NVIDIA's TensorRT tutorial to load the engine (i.e. drn.trt file) and to run inference on a sample image.
> > > The segmentation result looks correct, **which is why I believe the entire conversion process is correct (pytorch -> ONNX -> TensorRT engine trt file)**. However, the running speed is slower than before at **~0.33s / image** on Titan X. It ran even slower at **~0.42s / image** on Titan V. **I didn't quite get why TensorRT will slow things down. Do you have some ideas?**
> > > Therefore, I wanted to try FP16 to further speed up the model. On Titan X, the conversion `onnx2trt` went through but the model was still using FP32 because
> > > https://github.com/onnx/onnx-tensorrt/blob/f6f413852388e0eb37447b02fa170a9cdf89b0cc/main.cpp#L298
> > > 
> > > is false.
> > > On Titan V, the conversion `onnx2trt` failed and here is the error message again.
> > > ```
> > > ----------------------------------------------------------------
> > > Input filename:   drn.onnx
> > > ONNX IR version:  0.0.3
> > > Opset version:    6
> > > Producer name:    pytorch
> > > Producer version: 0.3
> > > Domain:           
> > > Model version:    0
> > > Doc string:       
> > > ----------------------------------------------------------------
> > > Parsing model
> > > Building TensorRT engine, FP16 available:1
> > >     Max batch size:     32
> > >     Max workspace size: 1024 MiB
> > > [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> > > [2018-07-19 02:45:33   ERROR] reformat.cu (1369) - Cuda Error in NCHWToNHWC: 9
> > > terminate called after throwing an instance of 'std::runtime_error'
> > >   what():  Failed to create object
> > > fish: “onnx2trt drn.onnx -o drn_float1…” terminated by signal SIGABRT (Abort)
> > > ```
> > > 
> > > 
> > > Sorry for the long message. I hope this clarifies my situation. Thanks again for your generous help.
> > 
> > 
> > I'm trying to use your method. And i got error like
> > /onnx/onnx/onnx_onnx2trt_onnx .pb.h:12:2: error: #error This file was generated by a newer version of protoc w hich is #error This file was generated by a newer version of protoc which is
> > while make -j8. I think , this is protoc version error. May i know what version did you use and please share for protoc installation.
> 
> I Solved the Installation Problem ..
> 
> Now I followed your code & I got error like segmentation fault (core dumped) on tensorrt 5.1.2
> 
> can you please help me with that..

generally segmentation fault (core dumped) relates to memory allocation problem. I provide full access to my path and file and memory's are free. Even though, it replicate the same error.  please update if any one solved or ideas relate to this problem.

**Comment by ShawnNew** [comment]
Seems that `bool fp16 = trt_builder->platformHasFastFp16();` will always end up `false`, which tells that the platform has no fp16 supported.
Anyone knows how to add the functionality of fp16 to the platform?

Many thanks.

**Comment by oelgendy** [comment]
**FP16 inference is 10x slower than FP32!**
Hi,
I am doing inference with Onnxruntime in C++. I converted the ONNX file into FP16 in Python using onnxmltools convert_float_to_float16. I obtain the fp16 tensor from libtorch tensor, and wrap it in an onnx fp16 tensor using
`g_ort->CreateTensorWithDataAsOrtValue(memory_info, libtorchTensor.data_ptr(), input_tensor_size * 2, input_node_dims.data(), input_node_dims.size(), ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16, &onnxTensor)`
What am I missing?
Thanks,
-Omar

**Comment by kevinch-nv** [comment]
Coming late to this thread, so I'll try my best to answer the questions posed by multiple users:

- For later versions of TensorRT, we recommend using the [trtexec](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) tool we have to convert ONNX models to TRT engines over `onnx2trt` (we're planning on deprecating onnx2trt soon)
- To use mixed precision with TensorRT, you'll have to specify the corresponding `--fp16` or `--int8` flags for `trtexec` to build in your specified precision
- If `trt_builder->platformHasFastFp16()` returns false, that means the GPU on your system does not support FP16 operations. You can refer to [this list](https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix) for the list of cards that support different precisions
- ONNX-Runtime inference is different from TensorRT inference. Please re-run your benchmarks with trtexec with the `--fp16` flag  specified.

Closing this thread, if anyone needs an update on their specific issue feel free to open a new issue.

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, we can help you solve quantization problems
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md
