### ISSUE TITLE
onnx2trt error when convert a onnx using ./trtexex --onnx=*.onnx

### ISSUE THREAD

**Issue by cheneyfan** [onnx/onnx-tensorrt#321]
ERROR: builtin_op_importers.cpp:1399 In function importPad:
[8] Assertion failed: mode == "constant" && value == 0
![image](https://user-images.githubusercontent.com/15644150/68207362-b6cfd180-0009-11ea-8ce9-2ca5201d49c0.png)
![image](https://user-images.githubusercontent.com/15644150/68207374-bd5e4900-0009-11ea-9787-ac38164915ba.png)

**Comment by rmccorm4** [comment]
Duplicate of here: https://github.com/NVIDIA/TensorRT/issues/195

**Comment by kevinch-nv** [comment]
Adding keywords. TRT only supports 0 constant padding currently.

**Comment by kevinch-nv** [comment]
TensorRT versions > 8.2 supports  non-0 constant padding now. Closing this issue.
