### ISSUE TITLE
How to start if wanna implement a ROIAlign plugin?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#323]
Hi, does there any tutorial on how to written a plugin on top of onnx-tensorrt?

**Comment by martin-91x** [comment]
Hi,
I would also need a tutorial for this. Especially, I want to implement a plugin for depthwise correlation (see https://github.com/STVIR/pysot/blob/master/pysot/core/xcorr.py - xcorr_depthwise)

**Comment by yflv-yanxia** [comment]
I also want to add a plugin in onnx, but there are no any tutorials or examples.

**Comment by justingyym** [comment]
I also want to add a plugin in onnx, but there are no any tutorials or examples.

me too

**Comment by John-Yao** [comment]
> Hi,
> I would also need a tutorial for this. More precise, I want to implement a plugin for depthwise correlation (see https://github.com/STVIR/pysot/blob/master/pysot/core/xcorr.py - xcorr_depthwise)

@martin-91x 
Have you figure out how  to implement a plugin for depthwise correlation. I am also trying to implement xcorr in tensorrt.
I wil appreciate it if you share your solution.

**Comment by kevinch-nv** [comment]
Please see here (https://github.com/onnx/onnx-tensorrt/blob/master/docs/faq.md#custom-layer-support) for instructions on getting started for implementing a custom op through a TensorRT plugin.
