### ISSUE TITLE
When will Greater support?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#327]
In case that almost every morden model will using Greater, besides it also helps model accelerate much if it can be traced inside onnx and forward usin tensorrt.

When will Greater op support though?

**Comment by jinfagang** [comment]
Or if none-zero support also can help us export much more model.

However none of them supported.

**Comment by kevinch-nv** [comment]
The greater operator has been supported since TRT 7.0. We are still working on supporting non-zero. Closing this issue.
