### ISSUE TITLE
No importer registered for op: LSTM

### ISSUE THREAD

**Issue by jamesguo** [onnx/onnx-tensorrt#330]
onnx2trt No importer registered for op: LSTM

https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-6.html#rel_6-0-1

New plugins:
Added a persistent LSTM plugin; a half precision persistent LSTM plugin that supports variable sequence lengths. This plugin also supports bi-direction, setting initial hidden/cell values, storing final hidden/cell values, and multi layers. You can use it through the PluginV2 interface, achieves better performance with small batch sizes, and is currently only supported on Linux. For more information, see Persistent LSTM Plugin in the TensorRT Developer Guide. (not applicable for Jetson platforms)

[ner_clean.onnx.zip](https://github.com/onnx/onnx-tensorrt/files/3841374/ner_clean.onnx.zip)

**Comment by jamesguo** [comment]
Parser built against:
  ONNX IR version:  0.0.5
  TensorRT version: 6.0.1

**Comment by kevinch-nv** [comment]
We've added support for LSTMs in TRT 7.0. Please try using the latest TensorRT version to parse any LSTM models you have.

Closing this issue for now, feel free to open a new one if you are still having trouble with the latest TensorRT version.
