### ISSUE TITLE
Why the PluginFactory and some plugin example were removed from master?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#336]
Compare to previous version 5.0, these plugin examples were all remove from master, for what kinds of reason?

**Comment by ttyio** [comment]
Sorry @jinfagang we adding new samples/plugins, and may remove some deprecated ones. May I ask which missing plugin/sample are you looking for? thanks.

**Comment by yzpfyang** [comment]
hi, ttyio @ttyio  would you please share me  the samples for plugin in new version?

**Comment by ttyio** [comment]
Hello @yzpfyang , you can find latest samples and plugin in 
https://github.com/NVIDIA/TensorRT/tree/release/7.1/samples
https://github.com/NVIDIA/TensorRT/tree/release/7.1/plugin

Thanks.

**Comment by kevinch-nv** [comment]
All ONNX plugins that were previously held in the repo has either:

1. Moved into the main TensorRT Plugin repository (as noted by @ttyio above), or
2. Been deprecated for native TRT layers over the releases.

In the most recent onnx-tensorrt releases (>= 7.0), there is no longer any plugin code in the repository.
