### ISSUE TITLE
Cannot load Resnet50 converted from onnx model zoo

### ISSUE THREAD

**Issue by KeDengMS** [onnx/onnx-tensorrt#34]
Repro:

```
wget https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz
tar xzf resnet50.tar.gz
onnx2trt resnet50/model.onnx -o resnet50.trt
python -c "import tensorrt as trt; eng = trt.lite.Engine(PLAN='resnet50.trt')"
```

It shows:
TypeError: Dimension mismatch
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/dist-packages/tensorrt/lite/engine.py", line 248, in __init__
    self.output_dim = [self.engine.get_binding_dimensions(o).to_DimsCHW() for o in output_index]
  File "/usr/lib/python3.5/dist-packages/tensorrt/lite/engine.py", line 248, in <listcomp>
    self.output_dim = [self.engine.get_binding_dimensions(o).to_DimsCHW() for o in output_index]
SystemError: <built-in method to_DimsCHW of nv_infer_bindings.Dims object at 0x7f8da85c0458> returned a result with an error set

**Comment by BobLiu20** [comment]
@KeDengMS  same error with you. any idea?

**Comment by kevinch-nv** [comment]
There is no issue parsing the resnet50 model from the model zoo with the latest TensorRT version (7.2) with the [trtexec](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) binary. Closing this issue as we are no longer supporting older versions of TensorRT.
