### ISSUE TITLE
parse yolov3.onnx  encounter problem

### ISSUE THREAD

**Issue by xiaoga501** [onnx/onnx-tensorrt#346]
I have tried to use the tf2onnx convert yolov3.pb -> yolov3.onnx. (https://github.com/onnx/tensorflow-onnx)
The  yolov3 tensorflow model comes from https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py#L23. 
But when I modified the tensorrt mnist_onnx_sample to parse the yolov3.onnx, encounter the problem below:
[color="orange"][color="gray"](mypy35) xiaoga@xiaoga-Lenovo:~/到 TensorRT-5.1.5.0 的链接/bin$ ./sample_onnx_mnist
&&&& RUNNING TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
----------------------------------------------------------------
Input filename:   ../../../data/mnist/yolov3.onnx
ONNX IR version:  0.0.4
Opset version:    7
Producer name:    tf2onnx
Producer version: 1.5.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
While parsing node number 151 [Slice]:
ERROR: builtin_op_importers.cpp:2041 In function importSlice:
[8] Assertion failed: std::find(axes.begin(), axes.end(), BATCH_DIM) == axes.end()
[E] Failure while parsing ONNX file
&&&& FAILED TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
sample_onnx_mnist: sampleOnnxMNIST.cpp:212: int main(int, char**): Assertion `trtModelStream != nullptr' failed.
已放弃 (核心已转储)[/color]

[/color]

Please give some advice and thanns a lot!

**Comment by kevinch-nv** [comment]
Hi @xiaoga501, if you want to test whether or not an ONNX model can run with TensorRT, I recommend using our CLI tool [trtexec](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) with the latest TensorRT version release.

I'm going to close this issue for now, feel free to reopen it if you have any further issues.
