### ISSUE TITLE
Building from Dockerfile does not work

### ISSUE THREAD

**Issue by SharifElfouly** [onnx/onnx-tensorrt#349]
When I try to build a Docker image from: [docker/onnx-tensorrt-deb.Dockerfile](https://github.com/onnx/onnx-tensorrt/blob/master/docker/onnx-tensorrt-deb.Dockerfile) it fails at STEP 6. With the following error message:

`dpkg: error: cannot access archive 'nv-tensorrt-repo-ubuntu1804-cuda10.1-trt6.0.1.5-ga-20190913_1-1_amd64.deb': No such file or directory`

This `nv-tensorrt-repo-ubuntu1804-cuda10.1-trt6.0.1.5-ga-20190913_1-1_amd64.deb` file does not seem to exist.

**Comment by Semihal** [comment]
Download it from here: https://developer.nvidia.com/nvidia-tensorrt-6x-download

**Comment by SharifElfouly** [comment]
Oh it requires me to log in, thats why I did not find it. Thank you!
