### ISSUE TITLE
Is there any way to use onnx parser with opset 11 support ? 

### ISSUE THREAD

**Issue by dhkim0225** [onnx/onnx-tensorrt#351]
## Description

onnx-parser is basically built with ir_version 3, opset 7 (https://github.com/onnx/onnx-tensorrt/blob/master/onnx_trt_backend.cpp)

Is there any way to use onnx parser with opset 11 support ? 

## Environment

**TensorRT Version**: 7.0.0
**GPU Type**: T4
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2.89
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu18.04
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 1.4.0
**PyTorch Version (if applicable)**: 1.3.1

**Comment by jinfagang** [comment]
@dhkim0225  You can check supported op matrix in readme, all supported onnx op were there.

**Comment by dhkim0225** [comment]
@jinfagang Thank you for fast reply. 
I mean, It works when I use ir4_opset7 version onnx, but onnx-parser cannot parse if I use ir4_opset11 version onnx.

Also, parser cannot parse opset 8 and 9.

My onnx model is made from pytorch 1.3.1.

**Comment by dhkim0225** [comment]
@jinfagang 
I also found an similiar issue that you made https://github.com/onnx/onnx-tensorrt/issues/241
How did you solve your problem?

**Comment by kevinch-nv** [comment]
Later releases of TensorRT supports opset11. You can check the latest support matrix [here](https://github.com/onnx/onnx-tensorrt/blob/master/operators.md)
