### ISSUE TITLE
docker cannot be built

### ISSUE THREAD

**Issue by OValery16** [onnx/onnx-tensorrt#352]
With the new version of tensorrt (trrt 7), the docker build fails

**Comment by leimao** [comment]
I found the problem. Will fix soon.

**Comment by bluerythem** [comment]
Any update?

**Comment by aif2017** [comment]
SOON!

**Comment by kedardg** [comment]
is that done?

**Comment by kevinch-nv** [comment]
We've removed the old docker images and consolidated them with the main TensorRT images in the 7.2 release. You can see the README on the master branch for more information on this, and please use those docker images moving forward.
