### ISSUE TITLE
Swig command issue solved using python

### ISSUE THREAD

**Issue by manendranathshukla** [onnx/onnx-tensorrt#359]
I solved the swig command issue using python. I created my own python script that convert the onnx model to tensorrt model using python.
Please have a look on my Readme.txt :  https://github.com/manendranathshukla/onnx-tensorrt/blob/master/Python/README.txt

**Comment by peasant98** [comment]
Hi @manendranathshukla, check out https://github.com/onnx/onnx-tensorrt/issues/350, I found that adding a line to one of the files allowed everything to work.

**Comment by kevinch-nv** [comment]
As mentioned in #350, the setup.py script has now been updated in master to not rely on SWIG anymore. 

Closing this issue, if you are having trouble with the new Python backend installation process feel free to open a new issue.
