### ISSUE TITLE
parsing  SpaceToDepth failure

### ISSUE THREAD

**Issue by z397164725** [onnx/onnx-tensorrt#360]
onnx1.6.0 + tensorrt7.0
While parsing node number 220 [SpaceToDepth]:
ERROR: builtin_op_importers.cpp:2946 In function importSpaceToDepth:
[6] Assertion failed: dims.d[1 + i] % block_size == 0

**Comment by lxl910915** [comment]
same problem

**Comment by shokohigol** [comment]
same problem with opset 10 and 11 with tensorrt7

**Comment by shokohigol** [comment]
Update libonnxparser.
Get onnxparser [source](https://github.com/onnx/onnx-tensorrt.git) and build.
replace /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.7.0.0 with new lib

**Comment by ttyio** [comment]
Hello @z397164725 @lxl910915 thanks for reporting

Have you followed @shokohigol 's instruction and fixed the failure? thanks.

**Comment by JoeyforJoy** [comment]
> Hello @z397164725 @lxl910915 thanks for reporting
> 
> Have you followed @shokohigol 's instruction and fixed the failure? thanks.

I solved this issue by following it.

**Comment by kevinch-nv** [comment]
Closing as this issue looks to be fixed.
