### ISSUE TITLE
onnx-tensorrt-6.0 proper onnx version

### ISSUE THREAD

**Issue by DaveBGld** [onnx/onnx-tensorrt#364]
Thanks for this project!

I'm building onnx-tensorrt-6.0 because of tensorRT 6.0.1 dependency.
I run into an error 
`onnx-tensorrt-6.0/ShapedWeights.hpp:25:10: fatal error: onnx/onnx_pb.h: No such file or directory`

I'm assuming I need to install onnx, but wonder if there is a onnx version issue here.

Many thanks!

**Comment by lovepan1** [comment]
Have you solved this problem,I also encountered this problem

**Comment by DaveBGld** [comment]
No.

**Comment by lovepan1** [comment]
ok, thank U, do you have some suggestions???
,
