### ISSUE TITLE
cp: cannot stat 'lib/lib*': No such file or directory

### ISSUE THREAD

**Issue by taomiao** [onnx/onnx-tensorrt#367]
when I was run 
```
docker build -f docker/onnx-tensorrt-tar.Dockerfile --tag=onnx-tensorrt:6.0.1 .
```
an error occur

here is the error command

cp: cannot stat 'lib/lib*': No such file or directory
The command '/bin/sh -c tar -xvf TensorRT-${TENSORRT_VERSION}.*.tar.gz &&     cd TensorRT-${TENSORRT_VERSION}/ &&     cp lib/lib* /usr/lib/x86_64-linux-gnu/ &&     rm /usr/lib/x86_64-linux-gnu/libnv*.a &&     cp include/* /usr/include/x86_64-linux-gnu/ &&     cp bin/* /usr/bin/ &&     mkdir /usr/share/doc/tensorrt &&     cp -r doc/* /usr/share/doc/tensorrt/ &&     mkdir /usr/src/tensorrt &&     cp -r samples /usr/src/tensorrt/  &&     pip2 install python/tensorrt-${TENSORRT_VERSION}-cp27-none-linux_x86_64.whl &&     pip3 install python/tensorrt-${TENSORRT_VERSION}-cp${PY3_VERSION}-none-linux_x86_64.whl &&     pip2 install uff/uff-*-py2.py3-none-any.whl &&     pip3 install uff/uff-*-py2.py3-none-any.whl &&     cd ../ &&     rm -rf TensorRT-${TENSORRT_VERSION}*' returned a non-zero code: 1

**Comment by BouweCeunen** [comment]
Any news on this?

**Comment by kevinch-nv** [comment]
Those docker files have been deprecated in favor of the official TensorRT OSS Dockerfiles that you can find [here](https://github.com/NVIDIA/TensorRT).

If you have any issues building with the latest version of TensorRT, feel free to open a new issue.
