### ISSUE TITLE
Could NOT find TENSORRT (missing: TENSORRT_LIBRARY)

### ISSUE THREAD

**Issue by omeralierdemir** [onnx/onnx-tensorrt#385]
Hi, I try convert  onnx model to tensortRT C++ API but I couldn't.
My system: 
I have a jetson tx2, tensorRT6 (and tensorRT 5.1.6 on different tx2) 
I tried to this commend cmake . -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include -DTENSORRT_ROOT=/usr/src/tensorrt -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc in onnx_tensorRT directory. I got this output:

`
CMake Error at CMakeLists.txt:100 (add_subdirectory):
The source directory

/home/omer/onnx-tensorrt/third_party/onnx

does not contain a CMakeLists.txt file.

-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so;TENSORRT_LIBRARY_MYELIN-NOTFOUND
-- Could NOT find TENSORRT (missing: TENSORRT_LIBRARY) 
ERRORCannot find TensorRT library.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TENSORRT_LIBRARY_MYELIN
linked by target "nvonnxparser_static" in directory /home/omer/onnx-tensorrt
linked by target "nvonnxparser" in directory /home/omer/onnx-tensorrt

-- Configuring incomplete, errors occurred

`
I have few quastions. is this repo supported tensorRT 6.0 or 5.1.6 version and tx2? because : https://devtalk.nvidia.com/default/topic/1069634/how-to-upgrade-tensorrt-to-7-0-version/?offset=10 How can convert onnx model to tensorRT C++ API ?

**Comment by rmccorm4** [comment]
Hi @omeralierdemir,

> Please set them or make sure they are set and tested correctly in the CMake files:
TENSORRT_LIBRARY_MYELIN

Myelin was introduced in TensorRT 7, which implies that you're building from either the 7.0 branch or from master. Please try building from the 6.0 branch for TensorRT 6.0. 

See:  https://github.com/onnx/onnx-tensorrt/issues/355#issuecomment-568831810

**Comment by omeralierdemir** [comment]
Hi @rmccorm4 
Firstly, thanks for answering my questions quickly. I did what your said and I cloned 6.0 branch. But I couldn't  build. I got this output.
`git clone -b 6.0 --single-branch https://github.com/onnx/onnx-tensorrt.git`
`mkdir build && cd build &&cmake .. -DTENSORRT_ROOT=/usr/src/tensorrt`

`
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- The CUDA compiler identification is NVIDIA 10.0.326
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.11.2") 
CMake Error at CMakeLists.txt:121 (add_subdirectory):
  The source directory

    /home/omer/Desktop/onnx-tensorrt/third_party/onnx

  does not contain a CMakeLists.txt file.


-- GPU_ARCH is not defined. Generating CUDA code for default SMs.
-- Found CUDNN: /usr/include  
-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so
-- Found TENSORRT: /usr/include/aarch64-linux-gnu  
-- Configuring incomplete, errors occurred!
See also "/home/omer/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/omer/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeError.log".


`

I tried this issue  #354 but it didn't work

**Comment by rmccorm4** [comment]
> I tried this issue #354 but it didn't work

What specifically did you try and what result did you get?

> CMake Error at CMakeLists.txt:121 (add_subdirectory):
> The source directory /home/omer/Desktop/onnx-tensorrt/third_party/onnx
> does not contain a CMakeLists.txt file.

I agree that initializing the submodules should fix this error as per #354. This worked for me just now on an x86 machine with a P4 GPU (CC 6.1):

```
git clone -b 6.0 --single-branch https://github.com/onnx/onnx-tensorrt.git
cd onnx-tensorrt/
git submodule update --init --recursive
# Assuming you have protobuf and other necessary dependencies installed
mkdir build && cd build &&cmake .. -DTENSORRT_ROOT=/usr/src/tensorrt
```

**Comment by omeralierdemir** [comment]
Hi @rmccorm4, 
These steps worked. thank you very, very much. Now I  have a .trt file. I searched README.md and last issues for sample test  used with C++ api. But I couldn't find.  This website (https://elinux.org/TensorRT/YoloV3) used this command for test:
`./trtexec --onnx=yolov3.onnx --output=layer106-conv --int8 --batch=$BATCH --device=$DEVICE // BATCH = 1, 2, 6 … 32`  
there is probably something I omited

tahnks again

**Comment by rmccorm4** [comment]
Hi @omeralierdemir,

This repo is for the ONNX parser for TensorRT, which is just a subset of TensorRT (you could've also built the ONNX parser, like you did above, by following the steps in the TensorRT GitHub repo). 

See https://github.com/NVIDIA/TensorRT for open source C++ samples. There should also be some samples that come with the TensorRT release that you installed in `/usr/src/tensorrt/samples`.

**Comment by omeralierdemir** [comment]
thanks for your help.
I close this issue...
