### ISSUE TITLE
Dynamic `scales` parameter is not supported for Resize op

### ISSUE THREAD

**Issue by vdel** [onnx/onnx-tensorrt#389]
I  recently tried to convert a TF model via tensorflow-onnx (https://github.com/onnx/tensorflow-onnx) and run it using onnx-tensorrt.

I had some upscaling (ResizeBilinear) operations with a dynamic target size parameter (i.e. dynamic computation of the resize shape). The constructed graph for this ResizeBilinear TF op went through the "else" branch [here](https://github.com/onnx/tensorflow-onnx/blob/84cfa03d35846ddaf524f42890ffc1576ee95134/tf2onnx/onnx_opset/nn.py#L686) because of this dynamic shape. The `scales` parameter was thus the output of the `Concat` op [here](https://github.com/onnx/tensorflow-onnx/blob/84cfa03d35846ddaf524f42890ffc1576ee95134/tf2onnx/onnx_opset/nn.py#L699).

It then failed in Tensort runtime [at this line](https://github.com/onnx/onnx-tensorrt/blob/457f2c34918e12a4a951c7d320ef7c6cf096f6ee/builtin_op_importers.cpp#L2466) because `scales.is_weights()` is false as `scales` if the output of the `Concat` op as discussed above and not a parameter of the model.

My question is: do you have any plans to support dynamic `scales` or do we have to use ONNX 11 opset and  the `sizes` parameter for the Resize op (which supports dynamic `sizes`) ?

**Comment by kevinch-nv** [comment]
We recommend using at least the opset 11 definition of resize that supports the sizes parameter as it's more generalized than the scales parameter.

**Comment by kevinch-nv** [comment]
Dynamic scales for resize as well as shape is supported in TensorRT versions >=8.2. Closing this issue.
