### ISSUE TITLE
core dumped error

### ISSUE THREAD

**Issue by walton-wang929** [onnx/onnx-tensorrt#391]
when i import onnx and tensorrt together, it would create **core dumped error.** what's wrong with my docker image. 

root@e23c27fc5af4:/workspace/img_17_class_porn_new/onnx_tensorrt_new# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> import tensorrt
Segmentation fault (core dumped)

root@e23c27fc5af4:/workspace/img_17_class_porn_new/onnx_tensorrt_new# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt
>>> tensorrt.__version__
'6.0.1.5'
>>> import onnx
Segmentation fault (core dumped)

root@e23c27fc5af4:/workspace/img_17_class_porn_new/onnx_tensorrt_new# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx.__version__
'1.5.0'
>>> import tensorrt
Segmentation fault (core dumped)

**Comment by walton-wang929** [comment]
need your help !!

**Comment by tianwen0110** [comment]
have you solved this problem? I met the same one!

**Comment by kevinch-nv** [comment]
Can you upgrade to a later TRT version? This issue should no longer occur with later TRT releases.
