### ISSUE TITLE
ERROR: input:44 In function importInput: [7] Assertion failed: convert_dims(onnx_tensor_type.shape().dim(), trt_dims)

### ISSUE THREAD

**Issue by AsharFatmi** [onnx/onnx-tensorrt#393]
I am converting a Keras model to TensorRT.
I have used keras2onnx to convert Keras model to .onnx model.

Now while trying to convert onnx model to a TensorRT engine I am getting the following error:-

```
kingashar@kingashar:~/tensorRT$ onnx2trt /home/kingashar/YOLOV3-LP/keras_model.onnx -o keras_wpod.trt
----------------------------------------------------------------
Input filename:   /home/kingashar/YOLOV3-LP/keras_model.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    keras2onnx
Producer version: 1.6.5
Domain:           onnx
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
ERROR: input:44 In function importInput:
[7] Assertion failed: convert_dims(onnx_tensor_type.shape().dim(), trt_dims)
```

onnx model neutron image:-

![Screenshot from 2020-02-10 14-32-59](https://user-images.githubusercontent.com/36506102/74142428-4d67ec00-4c12-11ea-8310-cf9b222ec49b.png)

Any idea of how to can solve this?

**Comment by nicolasgorrity** [comment]
Same issue here!
I am also using a model converted from Keras to ONNX via [keras-onnx](https://github.com/onnx/keras-onnx).
Another way to reproduce the error is:
```
import onnx
import onnx_tensorrt.backend as backend
model = onnx.load('model_file.onnx')
engine = backend.prepare(model, device='CUDA:0')  # or device='CUDA'
```
The last `backend.prepare(...)` instruction throws the following:
```
  File "<stdin>", line 1, in <module>
  File "/home/nicolas/onnx-tensorrt/onnx_tensorrt/backend.py", line 200, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/nicolas/onnx-tensorrt/onnx_tensorrt/backend.py", line 86, in __init__
    raise RuntimeError(msg)
RuntimeError: While parsing node number -1:
input_1:191 In function importInput:
[7] Assertion failed: convertOnnxDims(onnxDtype.shape().dim(), trt_dims)
```
Using:
- python 3.6.9
- cuda 10.0
- cudnn 7.6.5
- onnx==1.6.0
- onnxconverter-common==1.6.5
- tensorrt==7.0.0.11

**Comment by UndeadBlow** [comment]
@AsharFatmi Did you solve it? Why it's closed?
I'm running into the same issue when try to load onnx model in C++ after succeed export in Python.

**Comment by AsharFatmi** [comment]
Yeah, the issue was regarding the input shape of the Keras and onnx model.

I had initialized a dynamic shape, but for TensorRT and Onnx models, there needs to be a fixed input_shape.

**Comment by wqw-900902** [comment]
can you share your method?

**Comment by wqw-900902** [comment]
now ,i meeted the same issue with you @AsharFatmi

**Comment by AsharFatmi** [comment]
@wqw-900902 
You just need to fix the input shape of the model. by default, the Keras models generally have a dynamic shape. you have to specify a specific shape for the model eg. (1,300,300,0)

**Comment by nicolasgorrity** [comment]
As @AsharFatmi said, the input shape needs to be fixed as dynamic batch sizes are not supported by TensorRT.

The changes need to be made where you create the Keras Input layer. Instead of :
```python
input_layer = keras.layers.Input(shape=(300, 300, 3), name='input_layer')
```
You should write:
```python
batch_size = 1  # or whatever size you want
input_layer = keras.layers.Input(batch_shape=(batch_size, 300, 300, 3), name='input_layer')
```

Export your model again with this configuration and this should solve the error.

**Note:** TensorRT offers a feature for dynamic shapes, however I am not sure it works for dynamic batch sizes. I didn't go into the details, but you can find more [there](https://docs.nvidia.com/deeplearning/sdk/tensorrt-sample-support-guide/index.html#sample-dynamic-reshape).
