### ISSUE TITLE
How to use .trt file in C++

### ISSUE THREAD

**Issue by big-chan** [onnx/onnx-tensorrt#395]
i converted onnx model to .trt for using engine in C++.
But i can't find method of using .trt file in C++. How to load .trt file ??

**Comment by rmccorm4** [comment]
Check out this code sample: https://github.com/NVIDIA/TensorRT/blob/572d54f91791448c015e74a4f1d6923b77b79795/samples/common/sampleEngines.cpp#L488-L516

**Comment by big-chan** [comment]
Thank you

**Comment by Pavithran99** [comment]
how to use that .trt file in python ?
