### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by amrit110** [onnx/onnx-tensorrt#40]
I get this error while building the library...

``
    CMake Error at CMakeLists.txt:97 (add_subdirectory):
    The source directory
     /opt/onnx2trt/third_party/onnx
     does not contain a CMakeLists.txt file.
``

**Comment by amrit110** [comment]
ohh false alarm, needed to clone the repo recursively with submodules.

**Comment by drormeir** [comment]
Can you please explain what are the submodules and where can I clone them from?
