### ISSUE TITLE
onnx2trt-exported engine failed to deserialize for MSVC build (caused by CRLF linebreaks of windows ofstream)

### ISSUE THREAD

**Issue by tormentliang** [onnx/onnx-tensorrt#404]
Platform: win10, MSVC build by Visual Studio 2019.

Model successfully converted by onnx2trt, but failed to load by trtexec(Length in header does not match remaining archive length).

After modifying main.cpp (changing ofstream(engine_filename.c_str()) to fopen(engine_filename.c_str(),"wb")) we managed to get a correct serialized engine file.

**Comment by kevinch-nv** [comment]
Thanks for the report. `onnx2trt` was not written with Windows compatibility in mind, and we recommend using `trtexec` as the main program for converting onnx networks to TensorRT engines. Closing.
