### ISSUE TITLE
importGlobalAveragePool ERROR

### ISSUE THREAD

**Issue by jianyin2016** [onnx/onnx-tensorrt#405]
parse onnx model failed
=================
I believe my onnx model is exported without dynamic shape by setting `dynamic_axes=None`
-------------------------------------------------------------------------------------------------------
*pytorch to onnx export api are called as follows:*

    torch.onnx.export(model, inputs, './segment.onnx',
                              export_params=True,
                              verbose=True,
                              training=False,
                              input_names=None,
                              output_names=None,
                              operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
                              opset_version=11,
                              do_constant_folding=True,
                              example_outputs=torch_out,
                              strip_doc_string=True,
                              dynamic_axes=None,
                              keep_initializers_as_inputs=True
                              )

*but when parse onnx model with TensorRt api, function `createNetwork()` and `createNetworkV2(0U)` ends up with the same error:*

---
>ERROR: ModelImporter.cpp:457 In function importModel:
[4] Assertion failed: !_importer_ctx.network()->hasImplicitBatchDimension() && "This version of the
ONNX parser only supports TensorRT INetworkDefinitions with an explicit batch dimension. Please ensure the network was created using the EXPLICIT_BATCH NetworkDefinitionCreationFlag."

*changing the `createNetwork()` function to `createNetworkV2()` by setting the explict_batch flag like*

    INetworkDefinition* network = builder->createNetworkV2(1U <<
		static_cast<int>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH));
*this results in another error:*

>While parsing node number 645 [GlobalAveragePool]:
ERROR: builtin_op_importers.cpp:1087 In function importGlobalAveragePool:
[8] Assertion failed: !isDynamic(kernelSize) && "Cannot run global average pool on an input with dynamic spatial dimensions!" 

*onnx model verbose shows no GlobalAveragePlooing dynamic shape sign*

>%1258 : Float(1, 128, 1, 1) = onnx::GlobalAveragePool

detailed enviroment information
--------------------------------------

---
>OS : Windows 7
TensorRt version : 7.0.11
pyTorch version : 1.4.0
cuda : 10.2
ONNX IR version : 0.0.4
Opset version : 11
Producer name :  pytorch
Producer version : 1.3

*BTW,using trtexec.exe araise similar error* 

>While parsing node number 645 [GlobalAveragePool]:
ERROR: builtin_op_importers.cpp:1087 In function importGlobalAveragePool:
[8] Assertion failed: !isDynamic(kernelSize) && "Cannot run global average pool on an input with dynamic spatial dimensions!"
[02/28/2020-16:28:50] [E] Failed to parse onnx file
[02/28/2020-16:28:50] [E] Parsing model failed
[02/28/2020-16:28:50] [E] Engine creation failed
[02/28/2020-16:28:50] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # E:\TensorRT-7.0.0.11\samples\trtexec\\..\..\bin\trtexec.exe --onnx=E:\models\segment.onnx

**Comment by Beam-wi** [comment]
@jianyin2016 Hi，have you solved this problem? I get same  problem with you. Could you share solutions?

**Comment by jianyin2016** [comment]
@Beam-wi Hi, I guess you can bypass this via using the normal pooling if your input size is fixed.but I think it is not the right way doing so.
