### ISSUE TITLE
tensorrt 7  dynamic inputs，cann't set max_batch_size -1

### ISSUE THREAD

**Issue by 121786404** [onnx/onnx-tensorrt#409]
i follow [https://github.com/NVIDIA/tensorrt-inference-server/issues/1105#issuecomment-586474508](url) , set max_batch_size -1

./onnx2trt fr_mfnb.onnx -b -1 -o fr_mfnb.plan

Building TensorRT engine, FP16 available:1
Max batch size: 18446744073709551615
Max workspace size: 1024 MiB
[2020-03-05 01:47:08 ERROR] Parameter check failed at: ../builder/builder.cpp::setMaxBatchSize::113, condition: batchSize > 0 && batchSize <= MAX_BATCH_SIZE

**Comment by chiehpower** [comment]
Your link was invalid.

**Comment by 121786404** [comment]
https://github.com/NVIDIA/triton-inference-server/issues/1105#issuecomment-586474508

**Comment by kevinch-nv** [comment]
Hi @121786404, if your model has a static batch size, the you cannot make it dynamic through the onnx2trt binary.

First you will have to make sure that you have exported your model with a dynamic batch size (i.e -1), you can verify that the batch is dynamic through inspecting your model through a visualizer such as Netron.

Once you have a model with a dynamic batch, I would recommend using our [trtexec](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) tool over onnx2trt to properly import your model into TensorRT. You can see example command line options in the link.

**Comment by kevinch-nv** [comment]
Closing due to no response, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.
