### ISSUE TITLE
Convert the matterport MaskRCNN model from onnx to trt

### ISSUE THREAD

**Issue by chiehpower** [onnx/onnx-tensorrt#413]
## Description
Hi all,
I was converting the onnx model of MRCNN to TRT by onnx2trt. The onnx model of MaskRCNN was generated by tf2onnx from the maskrcnn repository of matterport on my AGX. Although while I was converting from pb to onnx, it appeared some strange warnings, it still successfully convert to onnx model. So I took this onnx model to convert to trt model on my desktop.

**Command:**
```
onnx2trt ./mrcnn.onnx -o ./mrcnn.trt
```
**Output information:**
```
----------------------------------------------------------------
Input filename:   ./mrcnn.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    tf2onnx
Producer version: 1.6.0
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2020-03-12 09:30:03 WARNING] /home/chieh/github/onnx-tensorrt/onnx2trt_utils.cpp:235: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2020-03-12 09:30:03 WARNING] /home/chieh/github/onnx-tensorrt/onnx2trt_utils.cpp:261: One or more weights outside the range of INT32 was clamped
[2020-03-12 09:30:03   ERROR] /home/chieh/github/onnx-tensorrt/onnx2trt_utils.cpp:369: Size mismatch when importing initializer: cond__954. Expected size: 1 , actual size: 4
ERROR: /home/chieh/github/onnx-tensorrt/ModelImporter.cpp:92 In function parseGraph:
[8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
```

## Desktop Environment
**TensorRT Version**: 7.0.0.11
**GPU Type**: 1060
**Nvidia Driver Version**: 440
**CUDA Version**: 10.0
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu 18.04 
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 1.14

## Relevant Files
MRCNN Model of Matterport:
https://drive.google.com/file/d/117JoQ30ogJgYNzuNbgtZxLhfe-ELYelc/view?usp=sharing

### Download my [model](https://drive.google.com/file/d/117JoQ30ogJgYNzuNbgtZxLhfe-ELYelc/view?usp=sharing) from google drive and use this command below:
**Command:**
```
onnx2trt ./mrcnn.onnx -o ./mrcnn.trt
```

### Or From stretch
1. Download the file from github
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py
2. Follow the step 6 of [prerequisites](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#prerequisites) to get the model.
`wget https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5`
3. Modify the code of mrcnn_to_trt_single.py. We just need to get rid of this function [uff.from_tensorflow_frozen_model](https://github.com/NVIDIA/TensorRT/blob/5e289e919eabdc563208b82e88ac298ac50ffbfb/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py#L150) from line 150 to line 160. In addition, modify the output .pb path, [here](https://github.com/NVIDIA/TensorRT/blob/5e289e919eabdc563208b82e88ac298ac50ffbfb/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py#L139).
Then we can implement this command.
```
python3 mrcnn_to_trt_single.py -w ./mask_rcnn_coco.h5 -o ./mask_rcnn_coco.uff
```
Dont worry. It just requests users to provide an output .uff path, but it will not be used in the end.
We can get a .pb file.

BTW if you didn't have the uff package, please remove it from [here](https://github.com/NVIDIA/TensorRT/blob/5e289e919eabdc563208b82e88ac298ac50ffbfb/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py#L33)

Also, I used the TF tool, summarize_graph, to confirm the input and output names.
```
Found 3 possible inputs: (name=input_image, type=float(1), shape=[?,3,1024,1024]) (name=input_image_meta, type=float(1), shape=[?,93]) (name=input_anchors, type=float(1), shape=[?,?,4]) 
No variables spotted.
Found 1 possible outputs: (name=mrcnn_mask/Reshape_1, op=Reshape) 
```
**In brief, we took the [MaskRCNN of matterport](https://github.com/matterport/Mask_RCNN) which is used by Keras, and we need to convert the .h5 model to .pb model first.** 
Next step, I hope that I can convert this .pb to .onnx. 

Eventually, type this command on our terminal line.
```
python3 -m tf2onnx.convert --graphdef ./mask_rcnn_coco.pb --output ./mask_rcnn_coco.onnx \
    --fold_const --opset 11 \
    --inputs input_image:0,input_image_meta:0,input_anchors:0\
    --outputs mrcnn_mask/Reshape_1:0
```
*Be careful of your .pb path.*

You can also use the onnx parser to build an engine, but the error message is same with onnx2trt.
If you have any idea, I will be grateful for any help you can provide.
Thank you.

**Comment by jinfagang** [comment]
Nvidia TensorRT git repo already contains this version MaskRCNN to tensorrt. You can try that one.

**Comment by chiehpower** [comment]
> Nvidia TensorRT git repo already contains this version MaskRCNN to tensorrt. You can try that one.

Hi @jinfagang,
Nvidia TensorRT git repo only provided the sample which is using uff parser to convert the MaskRCNN. (i.e., h5 > pb > uff > tensorrt)
However, I was converting from pb to onnx then onnx to trt. That is different way.

**Comment by jinfagang** [comment]
I don't think you have to through onnx... all roads lead to Rome..

**Comment by jinfagang** [comment]
However what I want to say is that, nvidia version proves that that model doesn't accelerate much even in tensorrt, I have tested that speed, fast from realtime and even same with vanillia pytorch cuda version..

**Comment by chiehpower** [comment]
> I don't think you have to through onnx... all roads lead to Rome..

Of course, you are right.
However, as UFF parser will be deprecated in the future and there are also some unsupported operations for uff parser, that's why I wanna try this way. I have another mrcnn model which is generated by myself. It is quite hard to use uff parser. I just want to show even the matterport rcnn which can also be used with onnx2trt.

**Comment by chiehpower** [comment]
> However what I want to say is that, nvidia version proves that that model doesn't accelerate much even in tensorrt, I have tested that speed, far from realtime and even same with vanillia pytorch cuda version..

Thanks for your information! I don't know that. 
Even it cannot accelerate so much, but it can still release the GPU memory, right?
What my purpose of using TensorRT is to release GPU memory. TensorFlow accounts for a lot of GPU memory.

**Comment by jinfagang** [comment]
Haven't heard uff will deprecated, that's a breaking news. Then you can stick in onnx way, anyway, it's more easy convert to other framework via onnx though.

**Comment by chiehpower** [comment]
> Haven't heard uff will deprecated, that's a breaking news. Then you can stick in onnx way, anyway, it's more easy convert to other framework via onnx though.

Check [Deprecated Features](https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-7.html#tensorrt-7). 
Yes, I will. Thanks for your advice!

**Comment by rmccorm4** [comment]
Hi @chiehpower ,

Not sure why, but your ONNX model is invalid:

```
root@59bac4fb1105:/mnt# python checker.py 
Traceback (most recent call last):
  File "checker.py", line 3, in <module>
    onnx.checker.check_model(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for DenseToDenseSetOperation with domain_version of 11

==> Context: Bad node spec: input: "mrcnn_detection/ExpandDims:0" input: "mrcnn_detection/ExpandDims_1:0" output: "mrcnn_detection/DenseToDenseSetOperation:0" output: "mrcnn_detection/DenseToDenseSetOperation:1" output: "mrcnn_detection/DenseToDenseSetOperation:2" name: "mrcnn_detection/DenseToDenseSetOperation" op_type: "DenseToDenseSetOperation" attribute { name: "set_operation" s: "intersection" type: STRING } attribute { name: "validate_indices" i: 1 type: INT }
```

May be an issue with tf2onnx, you might want to file there and see what they say: https://github.com/onnx/tensorflow-onnx/issues

**Comment by chiehpower** [comment]
Hi @rmccorm4,

Thanks for your testing!
I will try the keras2onnx as well. 

BTW 
Provide one information
the MaskRCNN sample is used the keras version 2.1.3. However, `keras2onnx` version can only be accepted over version  (>=) 2.2.4. So should be careful this point. :)
 
I will close this issue.

**Comment by bitwangdan** [comment]
@chiehpower 
hi, have you solved the problem? I met the same problem as you
