### ISSUE TITLE
what's the difference between official tensorrt's onnx parser and onnx-tensorrt?

### ISSUE THREAD

**Issue by Wallace00V** [onnx/onnx-tensorrt#424]
as i known, the official tensorrt also has onnx parser, so i want to know the specific difference between tensorrt's onnx parser and onnx-tensorrt?

**Comment by kevinch-nv** [comment]
@Wallace00V this repository is the open source version of the binary onnx parser library that's shipped with TensorRT. 

On [release](https://github.com/onnx/onnx-tensorrt/releases), these two are equivalent. Any commits on top of each version branch are bug fixes for that version of TensorRT, so this repository is the most up-to-date in terms of features and fixes for a specific TRT version.
