### ISSUE TITLE
While parsing node number 94 [Constant]: ERROR: ModelImporter.cpp:492 In function importModel: [7] Assertion failed: _importer_ctx.tensors().at(output.name()).is_tensor()

### ISSUE THREAD

**Issue by daixiangzi** [onnx/onnx-tensorrt#425]

**Comment by kevinch-nv** [comment]
@daixiangzi can your reproduce this error with the latest TRT version?

**Comment by kevinch-nv** [comment]
Closing due to no repro., if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.
