### ISSUE TITLE
ResizeBilinear in 5.1 branch should be supported

### ISSUE THREAD

**Issue by NikolasMarkou** [onnx/onnx-tensorrt#426]
ONNX supports the linear resize on that specific version but trt does not

**Comment by TengFeiHan0** [comment]
@NikolasMarkou how to add this operation under TensorRT7.0?

**Comment by NikolasMarkou** [comment]
Hi @TengFeiHan0 i think it is already supported in TRT7.0.
Automatic conversion we have made from onnx to TRT7.0 did not require anything extra.
This is specifically for trt version 5.1.*

**Comment by TengFeiHan0** [comment]
@NikolasMarkou in the operator's [lists]() of tensorrt7.0, they didn't mention that Bilinear upsampling has been supported. I also find some [iusses](https://github.com/NVIDIA/TensorRT/issues/386) related to this operation.

**Comment by NikolasMarkou** [comment]
@TengFeiHan0 as you can see in the buildin_op_importers it is linear and 
  if (mode == "linear"){
    RETURN_FIRST_OUTPUT(
        ctx->addPluginV2(
          new ResizeBilinearPlugin(scale), 
          {&inputs.at(0).tensor()}));

**Comment by NikolasMarkou** [comment]
Maybe a renaming would made the issue clearer

**Comment by NikolasMarkou** [comment]
Hello, is there a problem in merging this ?

**Comment by DJMeng** [comment]
> @NikolasMarkou in the operator's lists of tensorrt7.0, they didn't mention that Bilinear upsampling has been supported. I also find some [iusses](https://github.com/NVIDIA/TensorRT/issues/386) related to this operation.

Hello,Do you solve this problem? Thanks

**Comment by NikolasMarkou** [comment]
Yes

**Comment by DJMeng** [comment]
> Yes
> […](#)

You mean that resizebilinear have been supported on tensorrt7.0？How do you solve it？Please help.Thank you.

**Comment by NikolasMarkou** [comment]
@kevinch-nv ?

**Comment by kevinch-nv** [comment]
Apologies for the late response. Are you still having trouble with bilinear resizes? We have added support for these in later versions of TensorRT through its resize layer.

**Comment by NikolasMarkou** [comment]
Hi @kevinch-nv we fixed the issue in our internal repo. And after some time we moved into a newer version
