### ISSUE TITLE
In function parseGraph: [8] No importer registered for op: NonMaxSuppression

### ISSUE THREAD

**Issue by rgc183** [onnx/onnx-tensorrt#444]
I wanted to know if anyone has already implemented this op.
 When are we planning to add support for this?

**Comment by rgc183** [comment]
I am trying to write Importer for this app and struggling with input params. The issue is already posted here: https://github.com/NVIDIA/TensorRT/issues/510, looking for help here.

**Comment by kevinch-nv** [comment]
Closing as duplicate of NVIDIA/TensorRT#510
