### ISSUE TITLE
[8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)

### ISSUE THREAD

**Issue by rgc183** [onnx/onnx-tensorrt#445]
When I try to convert onnx model to tensorrt using `onnx2trt my_graph.onnx -o engine.trt` I get the following error. I am using latest master for the onnx2trt and tensorflow-onnx converter.

`Size mismatch when importing initializer: cond__377. Expected size: 1 , actual size: 4
ERROR: ModelImporter.cpp:92 In function parseGraph:
[8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)`

After debugging I found that, the tensor is having data type `bool` but the data is stored in `raw_data` of `TensorProto` for this tensor. The code in `convertOnnxWeights` expects bool data is stored in `uint32` and hence we get error at line 92.  Why `raw_data` is used to store `bool` data. From the proto file, it should be using `int32_data`.

Is this a known problem with the parser? What is the workaround?

**Comment by x-jeff** [comment]
I met the same problem.Have you solved it?

**Comment by rgc183** [comment]
This issue is fixed in latest master

**Comment by vilmara** [comment]
Hi @rgc183, what branch and TRT release did you use?. I am using branch 7.2.1  and TRT 7.2.1 and the problem` [8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)` persists

**Comment by balablb** [comment]
> Hi @rgc183, what branch and TRT release did you use?. I am using branch 7.2.1 and TRT 7.2.1 and the problem` [8] Assertion failed: convertOnnxWeights(initializer, &weights, ctx)` persists

I met the same problem.Have you solved it?
