### ISSUE TITLE
In function importPad: [8] Assertion failed: inputs.at(1).is_weights()

### ISSUE THREAD

**Issue by rgc183** [onnx/onnx-tensorrt#456]
I am using latest master. Second input to `Pad` operator is 1D tensor with dimension `2*rank_of_input`. Currently `Pad` importer expects it as a weight and fails to take tensor.

**Comment by WIll-Xu35** [comment]
Same problem here

**Comment by passion3394** [comment]
same problem

**Comment by KevenLee** [comment]
How do you solve it?

**Comment by lrh454830526** [comment]
Anyone can help?

**Comment by Felixyin91** [comment]
Same problem here. How to solve it?

**Comment by kevinch-nv** [comment]
See my response on #452 - closing this issue as duplicate.
