### ISSUE TITLE
Does onnx-tensorrt support TensorRT 4?

### ISSUE THREAD

**Issue by horance-liu** [onnx/onnx-tensorrt#46]
1. I don't know whether or not to refactor onnx-tensorrt, because TensorRT 4 have supported onnx specification.

2. I don't know whether or not to manages a registry of extension implementations for addtional operations using onnx-tensorrt(if support TensorRT 4).

thanks.

**Comment by yinghai** [comment]
Yes it does.

**Comment by horance-liu** [comment]
I decide to convert onnx to tensorrt plan file, for example RestNet-50. Now, I have two choices. 
1.  using tensorrt directly, but report error: **No converter registered for op type: Identity. I guess that tensorrt have not implement these operations.**
2. using onnx-tensorrt, but I'm not sure that  whether or not to support all tensorflow operations for onnx-tensorrt. 

any good suggestions?

**Comment by yinghai** [comment]
You can try onnx-tensorrt and if some op is not supported you can use the plug-in mechanism to implement that yourself.

**Comment by benbarsdell** [comment]
@horance-liu Identity is supported; are you building the latest code?
