### ISSUE TITLE
About torch.nn.Upsample (torch 1.0.1, tensorrt5.1.5, onnx 1.4.0)

### ISSUE THREAD

**Issue by study0098** [onnx/onnx-tensorrt#460]
Hi, thanks for this great work! I'm using pytorch1.0.1 and tensorrt 5.1.5.0. When I wanted to transfer this model to .trt engine:
![QQ截图20200518162553](https://user-images.githubusercontent.com/36301088/82190911-54df1580-9924-11ea-9246-45d5ae4a9695.png)
the pytorch-onnx-tensorrt works well. However, when I wanted to use tensorrt to do inference in python3.7, I cannot properly load (Serialize) the engine. It said:
`[TensorRT] ERROR: Serialized engine contains plugin, but no plugin factory was provided. To deserialize an engine without a factory, please use IPluginV2 instead.`
I've noticed that [https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/model.py](url) gave an excellent example of supporting upsample in pytorch, but it seems that my tensorrt cannot deserialize the upsample op in serialized engine, although the engine is properly generated by `onnx2trt` command. I am really confused about it. Your suggestions will be highly appreciated!

**Comment by DJMeng** [comment]
+1, I have same proplems

**Comment by kevinch-nv** [comment]
In TensorRT 5, the upsample implementation was done through a plugin, which means you'll have to provide the onnx-tensorrt plugin library (IIRC it was named `libnvonnxparser_runtime.so`  as a plugin factory when deserializing your engine.

In later TRT versions, resize is now a native layer within TRT so deseriazation can be done without providing this external plugin library. I would recommend updating to the latest TRT version to simplify the workflow and to obtain access to our latest performance optimizations.

**Comment by study0098** [comment]
> In TensorRT 5, the upsample implementation was done through a plugin, which means you'll have to provide the onnx-tensorrt plugin library (IIRC it was named `libnvonnxparser_runtime.so` as a plugin factory when deserializing your engine.
> 
> In later TRT versions, resize is now a native layer within TRT so deseriazation can be done without providing this external plugin library. I would recommend updating to the latest TRT version to simplify the workflow and to obtain access to our latest performance optimizations.

Thank you for your advice, I have tried TensorRT6.0.1 and it all works well!
