### ISSUE TITLE
trt model created from tensorrt7 is much bigger than tensorrt4

### ISSUE THREAD

**Issue by HaoLiuHust** [onnx/onnx-tensorrt#461]
I am migrating tensorrt4 to tensorrt7, however, I found that the trt model create with tensorrt7 is nearly 2 times bigger than tensorrt4,  and I tried tensorrt6, it's same with tensorrt7. What makes tensorrt7 model bigger?

**Comment by kevinch-nv** [comment]
Thanks for your question. What's the order of magnitude of size difference between the two engines? We have added more kernels in later TRT versions. In addition, if you are building an engine with dynamic shapes, the resulting engine will also be larger.

**Comment by HaoLiuHust** [comment]
about 2 times size difference, however, it's not a big problem
