### ISSUE TITLE
Understanding onnx-tensorrt workflow

### ISSUE THREAD

**Issue by solarflarefx** [onnx/onnx-tensorrt#463]
Forgive me as I am new to this project.  I would like to make sure I understand the intended function of onnx-tensorrt.

I have worked with TensorRT and ONNX models, where I have loaded an ONNX file, built an engine, and then run inference.  I have done this in C++.

Is the purpose of onnx-tensorrt to create a serialized engine to save that can be loaded later without having to be built again to run inference?

**Comment by manhongnie** [comment]
> Forgive me as I am new to this project. I would like to make sure I understand the intended function of onnx-tensorrt.
> 
> I have worked with TensorRT and ONNX models, where I have loaded an ONNX file, built an engine, and then run inference. I have done this in C++.
> 
> Is the purpose of onnx-tensorrt to create a serialized engine to save that can be loaded later without having to be built again to run inference?

How did you build the engine? I am also tensorflow to onnx
Can you give me a pointer?

**Comment by mk-nvidia** [comment]
> Is the purpose of onnx-tensorrt to create a serialized engine to save that can be loaded later without having to be built again to run inference?
@solarflarefx onnx-tensorrt is the ONNX parser (`nvonnxparser`) that TensorRT uses to load and convert a .onnx model into its internal representation. This repository is included in github.com/NVIDIA/TensorRT as a submodule, so when you build the open-source components from there, this repository also gets built.
Hope that answers your question, if not please ask more questions!
