### ISSUE TITLE
Potential repeated names from ImporterContext

### ISSUE THREAD

**Issue by tdp2110** [onnx/onnx-tensorrt#466]
Suppose we have a network with (not all distinct) layer names

layer
layer_1
layer

When `ImporterContext` sees "layer", it sees it's not in `mLayerNameCounts`, and sets `mLayerNameCounts["layer"] = 1` and adds a TRT layer with name "layer". It then sees "layer_1", concludes it's not in `mLayerNameCounts`, so it sets `mLayerNameCounts["layer_1"] = 1` and adds a TRT layer with name "layer_1". NOW when it sees "layer", it sees that `mLayerNameCounts["layer"] == 1`, so we produce a "uniqueName" of `"layer" + "_" + std::to_string(mLayerNameCounts["layer"] )`, ie "layer_1", which is a name conflict for the TRT net.

We actually hit this bug on one of our networks at work.

One easy way to fix this is to keep sets of strings for the tensorNames and layerNames that have been inserted in the network, and pull names that don't appear in the set. I'll submit a patch which does just that.

**Comment by kevinch-nv** [comment]
Thanks @tdp2110 for the contribution. The MR was merged a while ago, so closing this issue.
