### ISSUE TITLE
-O "pass_1;pass_2;pass_3" 

### ISSUE THREAD

**Issue by qzlshy** [onnx/onnx-tensorrt#470]
What's meaning of pass_1 here. And how can I get pass_1?
onnx2trt my_model.onnx -O "pass_1;pass_2;pass_3" -m my_model_optimized.onnx

**Comment by wwdok** [comment]
Me too, i want to know the meaning of "pass_1;pass_2;pass_3", without more explanation, i totally have no idea what it is...

**Comment by kevinch-nv** [comment]
You can take a look at the source MR (https://github.com/onnx/onnx-tensorrt/pull/420) for more information.

It does the optimizations on the ONNX graph listed in [this repo](https://github.com/onnx/onnx/tree/master/onnx/optimizer/passes).
