### ISSUE TITLE
parseFromFile returns `true` if it failed to parse file.

### ISSUE THREAD

**Issue by stelek** [onnx/onnx-tensorrt#471]
This code is wrong:
https://github.com/onnx/onnx-tensorrt/blob/7ec88b96c2f03a1a0c3629ff6830decc480dcc10/ModelImporter.cpp#L630
It returns `EXIT_FAILURE` which is apparently not `0`, while function return type is `bool`.

**Comment by tdp2110** [comment]
👍

**Comment by LeslieGerman** [comment]
Because of this bug, it returns `true` when the file does not exist... :roll_eyes:

**Comment by kevinch-nv** [comment]
Thanks for the report. Fixed in the above MR.
