### ISSUE TITLE
Assertion failed: convert_onnx_weights(initializer_weight, &weights)

### ISSUE THREAD

**Issue by chiehpower** [onnx/onnx-tensorrt#473]
Hi all,

As my onnx model size is quite big (takes almost 700 MB size), when I converted the onnx model to tensorRT model by onnx2trt on `TX2`, I got this error below.

Command:
```
$ onnx2trt model.onnx -o model.trt                   
```
Output on TX2:
```
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 779763912
----------------------------------------------------------------
Input filename:   model.onnx
ONNX IR version:  0.0.4
Opset version:    11
Producer name:    pytorch
Producer version: 1.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 779763912
ERROR: /home/nvidia/Downloads/onnx-tensorrt/ModelImporter.cpp:130 In function importInputs:
[8] Assertion failed: convert_onnx_weights(initializer_weight, &weights)
```
 
However, I can convert the same model to TensorRT engine by `onnx2trt` on my PC and successfully implement it. (The TensorRT engine took 1.5GB size in my PC after I converted from onnx to TRT.)

Is there any idea about this error? 
Thank you.

# Environment Information

- TX2:
  - ONNX IR version:  0.0.5
  - TensorRT version: 6.0.1
  - JetPack version: 4.3
  - ubuntu version: 18.04
  - python3 version: 3.6.9
  - CUDA version: 10.0.326
- PC:
  - ONNX IR version:  0.0.6
  - TensorRT version: 7.0.0.11
  - Cuda version: 10.0
  - Cudnn version: 7.6.5
  - Ubuntu: 18.04
  - Python 3.6.9

**Comment by 2730gf** [comment]
hi,have you solve this probolem,can you tell how to fix it?

**Comment by chiehpower** [comment]
Hi @2730gf,

This issue was quite long time ago. As far as I know, TensorRT and Jetson devcies have updated a lot that you might be able to try the latest version and using `trtexec` to convert the TRT engine.

Cheers.
