### ISSUE TITLE
Installation Step-by-Step

### ISSUE THREAD

**Issue by rose-jinyang** [onnx/onnx-tensorrt#488]
Hello
How are you?
Thanks for contributing this project.
Of course, we may refer NVIDIA/TensorRT project's installation as you said.
Could u provide the detailed installation steps in README?
Thanks.

**Comment by mk-nvidia** [comment]
Thanks for the suggestion. By referring to NVIDIA/TensorRT's README, we are able to maintain the installation steps in one place. That prevents the instructions from going out of sync and reduces our maintenance burden.
