### ISSUE TITLE
No module named 'onnx_tensorrt' 

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx-tensorrt#492]
I use `import onnx_tensorrt.backend as backend` in code, but get error:
`ModuleNotFoundError:` No module named 'onnx_tensorrt'`

My onnx-tensorrt is ok ,and I can use onnx2trt，but this error, Does somebody knows?

**Comment by kolingv** [comment]
I encounterted the same error inside docker, it seems that when comes to "python setup.py build && python setup.py install" failed.

**Comment by mk-nvidia** [comment]
Closing as dupe of #298 
We're taking a look at this issue.
