### ISSUE TITLE
dockerfile build fail

### ISSUE THREAD

**Issue by quinwu** [onnx/onnx-tensorrt#496]
tensorRT version:7.0.0.11
onnx-tensorrt version:7.0

Step 15/18 : RUN rm -rf build/ &&     mkdir -p build &&     cd build &&     cmake -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include/ .. &&     make -j$(nproc) &&     make install &&     ldconfig &&     cd .. &&     python2 setup.py build &&     python2 setup.py install &&     python3 setup.py build &&     python3 setup.py install &&     rm -rf ./build/
 ---> Running in f916bb7885ec
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
CMake Error at CMakeLists.txt:100 (add_subdirectory):
  The source directory

    /opt/onnx-tensorrt/third_party/onnx

  does not contain a CMakeLists.txt file.

-- Found TensorRT headers at /usr/include/x86_64-linux-gnu
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so;/usr/lib/x86_64-linux-gnu/libmyelin.so
-- Found TENSORRT: /usr/include/x86_64-linux-gnu  
-- Configuring incomplete, errors occurred!
See also "/opt/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/opt/onnx-tensorrt/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c rm -rf build/ &&     mkdir -p build &&     cd build &&     cmake -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include/ .. &&     make -j$(nproc) &&     make install &&     ldconfig &&     cd .. &&     python2 setup.py build &&     python2 setup.py install &&     python3 setup.py build &&     python3 setup.py install &&     rm -rf ./build/' returned a non-zero code: 1

**Comment by quinwu** [comment]
i think this dockerfile should be update.

**Comment by wyukai** [comment]
Hello, how did you solve this problem?
