### ISSUE TITLE
what if onnxDtype == ::ONNX_NAMESPACE::TensorProto::DOUBLE?

### ISSUE THREAD

**Issue by haoyuanz13** [onnx/onnx-tensorrt#501]
In the official onnx source code, https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L450-L479, it seems like it can support DOUBLE.

However, in the file onnx-tensorrt/onnx2trt_utils.cpp#311, the function convertOnnxWeights doesn't support the DOUBLE type which throw a LOG error 【Found unsupported datatype (11) when importing initializer】...

Why this tool cannot make consistent with the onnx?

**Comment by zhouyuangan** [comment]
@haoyuanz13 Had you solved this problem?

**Comment by haoyuanz13** [comment]
> @haoyuanz13 Had you solved this problem?

not yet, I have already tried to constraint my model weights into the FLOAT type but nothing changed...

**Comment by haoyuanz13** [comment]
any update?

**Comment by zhouyuangan** [comment]
> any update?

Dont use tensor slice to update a tensor, instead of creating a tensor,I used tensorrt7.1.3.4 convert yolov3 successfully.
for example,
`tensor[:,0]*= another_tensor`
raise errors

**Comment by zhouyuangan** [comment]
> > > any update?
> > 
> > 
> > Dont use tensor slice to update a tensor, instead of creating a tensor,I used tensorrt7.1.3.4 convert yolov3 successfully.
> > for example,
> > `tensor[:,0]*= another_tensor`
> > raise errors
> 
> does the trt version make a difference?

ONLY test on tensorrt 7.1.3.4 successfully,

**Comment by zhouyuangan** [comment]
Tensorrt 7.1.3.4 is developed on onnx opset=11, it's important for noticing.

**Comment by haoyuanz13** [comment]
> Tensorrt 7.1.3.4 is developed on onnx opset=11, it's important for noticing.

good to know, thx

**Comment by kevinch-nv** [comment]
Hi all,

TensorRT does not have native support for the DOUBLE datatype at the moment, which is why you are seeing an error message if you attempt to import a model that uses the DOUBLE type.

I would recommend trying to export your models in float32 type at the moment and see if the resulting model can be imported by TensorRT.

**Comment by bulatnv** [comment]
Hello @kevinch-nv, @zhouyuangan.

Did you found a solution to this problem?

I'm aiming to convert faster rcnn from torchvision. 
Torch exports one of the nodes as %2432 = Constant[value = <Scalar Tensor []>]()
After applying ONNX optimizer or simplifier this initializer become %2432[DOUBLE, scalar]
As a result: Found unsupported datatype (11) when importing initializer: 2432.
I'm using TensorRT 7.2.1.6.

Is there any way to convert this node to float or bypass this problem?

Thank you kindly.

**Comment by jinfagang** [comment]
@bulatnv onnx optimizer will not change tensor data types.
