### ISSUE TITLE
--explicitBatch 

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [onnx/onnx-tensorrt#508]
Hi @Yangqing @shinh v @tdp2110  @Maratyszcza  @yinghai 
I want to know @who

As the title, there is an option in tensorrt7.0 trtexec “--explicitbatch,”

How can I add it when using onnx2trt,

**Comment by kevinch-nv** [comment]
Hi @CallmeZhangChenchen, we recommend using trtexec going forward, as onnx2trt will be deprecated soon.
