### ISSUE TITLE
Unable to find onnx_tensorrt package.

### ISSUE THREAD

**Issue by mojomojo52** [onnx/onnx-tensorrt#511]
In the README - ONNX Python backend usage it saids to import onnx_tensorrt.backend.
Well I don't seem to be able to find the onnx_tensorrt package anywhere.
I've checked tensorrt_install_dir like README saids, but it only installs tensorrt packe, which doesn't have a .backend.
Can you please be kind enough to point me in the right direction?

**Comment by mk-nvidia** [comment]
Closing as dupe of #298 
We're taking a look at this issue.
