### ISSUE TITLE
Network has dynamic or shape inputs, but no optimization profile has been defined. TRT 7.1

### ISSUE THREAD

**Issue by konradkostrzewa** [onnx/onnx-tensorrt#518]
Building TensorRT engine, FP16 available:1
    Max batch size:     5
    Max workspace size: 1024 MiB
[2020-08-20 11:03:50   ERROR] Network has dynamic or shape inputs, but no optimization profile has been defined.
[2020-08-20 11:03:50   ERROR] Network validation failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)

I am using exactly the same file of the onnx model, as I did for TRT 6.0 and 7.0. For previous version the conversion worked. I am using the following command: 

onnx2trt model.onnx -o output.bin -d 32 -b 5

on Nvidia Jetson nano with Jetpack 4.4 and Tensorflow 1.15.2. The model is the Keras-trained Mobilenet.

Any idea why it could stop working on TRT 7.1?

**Comment by SergeLiu** [comment]
I have the same question with you，have you solved this problem？Thanks！

**Comment by nyanmn** [comment]
You have to use optimization profile.
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes
sample is here.
https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleDynamicReshape

**Comment by mk-nvidia** [comment]
@nyanmn Thanks for the links.
@konradkostrzewa Do the links above solve your issue? If so please close this.

**Comment by mk-nvidia** [comment]
Closing, reopen if this is still a problem.

**Comment by FuzhiYang** [comment]
@konradkostrzewa Have you solved this problem?

**Comment by samsterckval** [comment]
I can't find how to solve this using the supplied links, could anyone help me where I could define this optimization profile?

**Comment by sonctmirasoft** [comment]
`    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(network_creation_flag) as network, trt.OnnxParser(network, TRT_LOGGER) as parser, builder.create_builder_config() as config:        
        profile = builder.create_optimization_profile()     
        profile.set_shape("input_1", (1, 224, 224, 3), (1, 224, 224, 3), (1, 224, 224, 3))
        config.add_optimization_profile(profile)
        engine = builder.build_engine(network, config)
`
Python example to set the dynamic input layer **input_1** to size (1, 224, 224, 3)

**Comment by umairjavaid** [comment]
@sonctmirasoft what's the name of the file in which u put this code?

**Comment by dig19998** [comment]
> You have to use optimization profile. https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes sample is here. https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleDynamicReshape

It shows page not found

**Comment by DrRyanHuang** [comment]
> > You have to use optimization profile. https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes sample is here. https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleDynamicReshape
> 
> It shows page not found

Maybe here:

https://github.com/NVIDIA/TensorRT/blob/main/samples/sampleDynamicReshape/README.md
https://github.com/NVIDIA/TensorRT/blob/main/samples/README.md
