### ISSUE TITLE
anyone convert torchvision.models.resnet50 successfuly?

### ISSUE THREAD

**Issue by twmht** [onnx/onnx-tensorrt#519]
I can't convert torchvision.models.resnet50, here is the detail (https://github.com/NVIDIA/TensorRT/issues/751).

Any idea?

**Comment by rmccorm4** [comment]
Hi @twmht ,

I just tried this and was able to export to ONNX and parse with TensorRT successfully:

Setup Environment
```
# Start TensorRT 7.1.3.4 container
nvidia-docker run -it -v $PWD:/mnt nvcr.io/nvidia/tensorrt:20.08-py3

# Install dependencies
pip install torch==1.6.0 torchvision==0.7.0 onnx==1.7.0

# Generate resnet50_fixed.onnx model
python resnet50-repro.py

# Parse onnx model
trtexec --explicitBatch --onnx=resnet50_fixed.onnx
...
&&&& PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=resnet50_fixed.onnx
```

Pytorch -> ONNX
```
# resnet50-repro.py
import argparse
import torch
import torchvision

parser = argparse.ArgumentParser()
parser.add_argument("--opset", type=int, default=11, help="ONNX opset version to generate models with.")
args = parser.parse_args()

dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
model = torchvision.models.resnet50(pretrained=True).cuda()

# Fixed Shape
torch.onnx.export(model, dummy_input, "resnet50_fixed.onnx", verbose=True, opset_version=args.opset)
```

**Comment by twmht** [comment]
@rmccorm4 

I tried with tensorrt python api but failed to generate the engine file.

maybe you can try python api.

by the way, I have mentioned the multi batch problem in another thread (https://github.com/NVIDIA/TensorRT/issues/751). and `resnet50_fixed.onnx` also have this issue.

**Comment by twmht** [comment]
If you want the multibatch code, I can give that to you.

**Comment by mk-nvidia** [comment]
@twmht On NVIDIA/TensorRT#751 you commented that you were going to verify if this issue was fixed. Any luck?

**Comment by mk-nvidia** [comment]
Closing due to lack of response.
