### ISSUE TITLE
How to do batch inference on input with 3 channels like bgr images by TensorRT?

### ISSUE THREAD

**Issue by y200504040u** [onnx/onnx-tensorrt#522]
How to do batch inference on input with 3 channels like bgr images by TensorRT?
I read examples:
./samples/python/int8_caffe_mnist/  && ./samples/python/yolov3_onnx/
"int8_caffe_mnist" do batch inference on binary images with only one channel.
However, "yolov3_onnx" do inference on bgr images with 3 channels on by one.

Does`def do_inference(context, bindings, inputs, outputs, stream, batch_size=1):` only support input with only one channel???

**Comment by kevinch-nv** [comment]
All you need to is update the `batch_size` parameter in the function to the batch size you want to do inference with - it doesn't matter on the size of the input. 

Note that this is true for networks created with implicit batch, in later versions of TensorRT for ONNX graphs INetworks must be created in explicit batch mode, which uses a slightly different API. You can look at the `do_inference_v2` function to see the difference.
