### ISSUE TITLE
cout statements are being used instead of the logger

### ISSUE THREAD

**Issue by josh-gleason** [onnx/onnx-tensorrt#526]
Unless there's some underlying reason which I'm unaware of it seems like the cout statements at [ModelImporter.cpp:658](https://github.com/onnx/onnx-tensorrt/blob/master/ModelImporter.cpp#L658) should be reported to the logger instead of using cout. Also, why are these considered warning level messages? Wouldn't info level filtering be more appropriate since these aren't actually warnings?

**Comment by kevinch-nv** [comment]
Thanks for the report, I'll make a MR updating this.

**Comment by kevinch-nv** [comment]
Change submitted, closing issue
