### ISSUE TITLE
where INT64 comes? 

### ISSUE THREAD

**Issue by yk1110** [onnx/onnx-tensorrt#527]
graph(%input : Float(1, 3, 32, 32),
      %conv1.weight : Float(6, 3, 5, 5),
      %conv1.bias : Float(6),
      %conv2.weight : Float(16, 6, 5, 5),
      %conv2.bias : Float(16),
      %fc1.weight : Float(120, 400),
      %fc1.bias : Float(120),
      %fc2.weight : Float(84, 120),
      %fc2.bias : Float(84),
      %fc3.weight : Float(10, 84),
      %fc3.bias : Float(10)):
  %11 : Float(1, 6, 28, 28) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[0, 0, 0, 0], strides=[1, 1]](%input, %conv1.weight, %conv1.bias) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py:346:0
  %12 : Float(1, 6, 28, 28) = onnx::Relu(%11) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1063:0
  %13 : Float(1, 6, 14, 14) = onnx::MaxPool[ceil_mode=0, kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%12) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:539:0
  %14 : Float(1, 16, 10, 10) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[0, 0, 0, 0], strides=[1, 1]](%13, %conv2.weight, %conv2.bias) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py:346:0
  %15 : Float(1, 16, 10, 10) = onnx::Relu(%14) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1063:0
  %16 : Float(1, 16, 5, 5) = onnx::MaxPool[ceil_mode=0, kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%15) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:539:0
  %17 : Tensor = onnx::Constant[value=  -1  400 [ CPULongType{2} ]]()
  %18 : Float(1, 400) = onnx::Reshape(%16, %17) # C:/Users/13020/PycharmProjects/torch_project/main_cifar10.py:29:0
  %19 : Float(1, 120) = onnx::Gemm[alpha=1., beta=1., transB=1](%18, %fc1.weight, %fc1.bias) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1610:0
  %20 : Float(1, 120) = onnx::Relu(%19) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1063:0
  %21 : Float(1, 84) = onnx::Gemm[alpha=1., beta=1., transB=1](%20, %fc2.weight, %fc2.bias) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1610:0
  %22 : Float(1, 84) = onnx::Relu(%21) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1063:0
  %output : Float(1, 10) = onnx::Gemm[alpha=1., beta=1., transB=1](%22, %fc3.weight, %fc3.bias) # C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1610:0
  return (%output)

### this is my CNN,  when parse the network with tensorrt

it comes like this 
 Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.

**Comment by kevinch-nv** [comment]
In most cases this warning can be ignored since ONNX uses INT64 to generate constants by default. Since TRT doesn't natively support INT64, this warning is to notify the user that we are casting down to INT32. 

From your log, I see this following line `%17 : Tensor = onnx::Constantvalue= -1 400 [ CPULongType{2} ]`. Since this value can also be represented in INT32 you can safely ignore this warning.
