### ISSUE TITLE
Custom Plugin Support?

### ISSUE THREAD

**Issue by golden0080** [onnx/onnx-tensorrt#529]
Seems like the current onnx parser for TensorRT doesn't really have a way to implement/inject new NodeImporter for new Ops.
Any plan to support Custom plugins for TensorRT? I think UFF parser has something like this and able to handle custom ops well.

**Comment by yk1110** [comment]
https://github.com/NVIDIA/TensorRT/tree/master/plugin

**Comment by golden0080** [comment]
> https://github.com/NVIDIA/TensorRT/tree/master/plugin

This is only part of the puzzle actually. Since the `ModelImporter` implemented in this repo doesn't have ability to import custom ops, even you've registered a TensorRT. This becomes obvious if you look at: https://github.com/onnx/onnx-tensorrt/blob/master/ModelImporter.hpp#L68

**Comment by eric-tc** [comment]
Hi @golden0080 have you found a way to have custom plugin? I am also interested in this feature. Thanks

**Comment by golden0080** [comment]
@eric-tc You would need to import the underlying implementation class of `OnnxParser` and that implementation class should direct you to how to handle custom ops (or any ops).

**Comment by golden0080** [comment]
Instead of using TensorRT provoded API to create `IParser`, try to create a parser with this class (or subclass it) here:
https://github.com/onnx/onnx-tensorrt/blob/master/ModelImporter.hpp#L37

**Comment by kevinch-nv** [comment]
See my answer in #145.
