### ISSUE TITLE
make error, undefined reference libcudnn.so.8 libnvinfer.so libmyelin.so

### ISSUE THREAD

**Issue by kalenforn** [onnx/onnx-tensorrt#530]
hello,my environment is CUDA11 and Tensorrt7.1.3.4, 
the `cmake .. -DTENSORRT_ROOT=$TENSORRT_ROOT -DCUDA_INCLUDE_DIR=$CUDA_PATH/include`   result is here:
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
Generated: /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.proto
Generated: /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx-ml.proto
-- 
-- ******** Summary ********
--   CMake version         : 3.18.2
--   CMake command         : /usr/local/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 7.5.0
--   CXX flags             :  -Wall -Wno-deprecated-declarations -Wno-unused-function -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_NAMESPACE=onnx2trt_onnx
--   CMAKE_PREFIX_PATH     : 
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : 
-- 
--   ONNX version          : 1.6.0
--   ONNX NAMESPACE        : onnx2trt_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
-- 
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf includes     : /usr/include
--   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : OFF
-- Found TensorRT headers at /home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/include
-- Find TensorRT libs at /home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so;/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so;/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tujunfeng/code/github/onnx-tensorrt/build
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------

and then I use `make -j8`, some problems is here:
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
[  1%] Running gen_proto.py on onnx/onnx.in.proto
Processing /home/tujunfeng/code/github/onnx-tensorrt/third_party/onnx/onnx/onnx.in.proto
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.proto
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.proto3
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-ml.pb.h
generating /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_pb.py
[  2%] Running C++ protocol buffer compiler on /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_onnx2trt_onnx-ml.proto
[  2%] Built target gen_onnx_proto
[  3%] Running gen_proto.py on onnx/onnx-operators.in.proto
Processing /home/tujunfeng/code/github/onnx-tensorrt/third_party/onnx/onnx/onnx-operators.in.proto
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx-ml.proto
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx-ml.proto3
Writing /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators-ml.pb.h
generating /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx_operators_pb.py
[  5%] Running C++ protocol buffer compiler on /home/tujunfeng/code/github/onnx-tensorrt/build/third_party/onnx/onnx/onnx-operators_onnx2trt_onnx-ml.proto
Scanning dependencies of target onnx_proto
[  6%] Building CXX object third_party/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx_onnx2trt_onnx-ml.pb.cc.o
[  7%] Building CXX object third_party/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx-operators_onnx2trt_onnx-ml.pb.cc.o
[  8%] Linking CXX static library libonnx_proto.a
[ 11%] Built target onnx_proto
Scanning dependencies of target nvonnxparser_static
Scanning dependencies of target nvonnxparser
Scanning dependencies of target onnx
[ 12%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o
[ 14%] Building CXX object CMakeFiles/nvonnxparser.dir/onnx2trt_utils.cpp.o
[ 16%] Building CXX object CMakeFiles/nvonnxparser.dir/NvOnnxParser.cpp.o
[ 16%] Building CXX object CMakeFiles/nvonnxparser.dir/ModelImporter.cpp.o
[ 17%] Building CXX object CMakeFiles/nvonnxparser_static.dir/NvOnnxParser.cpp.o
[ 19%] Building CXX object CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o
[ 20%] Building CXX object CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o
[ 21%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o
[ 23%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
[ 24%] Building CXX object CMakeFiles/nvonnxparser.dir/ShapedWeights.cpp.o
[ 25%] Building CXX object CMakeFiles/nvonnxparser.dir/ShapeTensor.cpp.o
[ 26%] Building CXX object CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o
[ 28%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
[ 29%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
[ 30%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
[ 32%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapedWeights.cpp.o
[ 33%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapeTensor.cpp.o
[ 34%] Building CXX object CMakeFiles/nvonnxparser_static.dir/LoopHelpers.cpp.o
[ 35%] Building CXX object CMakeFiles/nvonnxparser.dir/LoopHelpers.cpp.o
[ 37%] Building CXX object CMakeFiles/nvonnxparser.dir/RNNHelpers.cpp.o
[ 38%] Building CXX object CMakeFiles/nvonnxparser.dir/OnnxAttrs.cpp.o
[ 39%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/status.cc.o
[ 41%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
[ 42%] Building CXX object CMakeFiles/nvonnxparser_static.dir/RNNHelpers.cpp.o
[ 43%] Building CXX object CMakeFiles/nvonnxparser_static.dir/OnnxAttrs.cpp.o
[ 44%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
[ 46%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
[ 47%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
[ 48%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/function.cc.o
[ 50%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
[ 51%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
[ 52%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
[ 53%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
[ 55%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
[ 56%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
[ 57%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
[ 58%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
[ 60%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
[ 61%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
[ 62%] Linking CXX shared library libnvonnxparser.so
[ 62%] Built target nvonnxparser
[ 64%] Linking CXX static library libnvonnxparser_static.a
[ 65%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
[ 65%] Built target nvonnxparser_static
[ 66%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
[ 67%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
[ 69%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
Scanning dependencies of target getSupportedAPITest
[ 70%] Building CXX object CMakeFiles/getSupportedAPITest.dir/getSupportedAPITest.cpp.o
[ 71%] Building CXX object CMakeFiles/getSupportedAPITest.dir/ModelImporter.cpp.o
[ 73%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
[ 74%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
[ 75%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
[ 76%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
[ 78%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
[ 79%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
[ 80%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
[ 82%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
[ 83%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
[ 84%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
[ 85%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
[ 87%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/optimizer/optimize.cc.o
[ 88%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/optimizer/pass.cc.o
[ 89%] Linking CXX executable getSupportedAPITest
[ 91%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/optimizer/pass_manager.cc.o
/usr/bin/ld: warning: libcudnn.so.8, needed by /home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnSetTensor4dDescriptor’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnPoolingForward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnActivationForward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreate@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionBackwardFilterAlgorithmMaxCount@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnConvolutionBackwardData@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyActivationDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetRNNParamsSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateLRNDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetPooling2dDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnTransformTensor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetBatchNormalizationForwardTrainingExWorkspaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetDropoutDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetBatchNormalizationBackwardExWorkspaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetLRNDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetFilter4dDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnConvolutionForward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetFilterNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetTensorNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetActivationDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionBackwardDataAlgorithmMaxCount@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetTensor4dDescriptorEx@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyOpTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetVersion@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnBatchNormalizationForwardTrainingEx@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnCreateTensorDescriptor’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyConvolutionDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetRNNMatrixMathType@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetTensorNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnDestroyTensorDescriptor’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnAddTensor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetTensor4dDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionMathType@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionBackwardDataAlgorithm_v7@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyRNNDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetConvolution2dDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnBatchNormalizationBackwardEx@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnRNNForwardInference@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnDeriveBNTensorDescriptor’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnDeriveBNTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroy@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateActivationDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetConvolutionForwardWorkspaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionForwardAlgorithm_v7@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetErrorString@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetTensor4dDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateRNNDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyDropoutDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetTensorNdDescriptorEx@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyPoolingDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnConvolutionBackwardFilter@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionForwardAlgorithmMaxCount@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreatePoolingDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnSetStream’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetProperty@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyFilterDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDropoutGetStatesSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetConvolutionMathType@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer_plugin.so：对‘cudnnBatchNormalizationForwardTraining’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnLRNCrossChannelForward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetRNNLinLayerBiasParams@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetBatchNormalizationTrainingExReserveSpaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetRNNDescriptor_v6@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSoftmaxForward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetRNNLinLayerMatrixParams@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnGetConvolutionBackwardFilterAlgorithm_v7@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetConvolutionNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnOpTensor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateConvolutionDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateFilterDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnDestroyLRNDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetOpTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetRNNWorkspaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnPoolingBackward@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetStream@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetFilterNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libmyelin.so：对‘cudnnSetPoolingNdDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateOpTensorDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnGetConvolutionBackwardDataWorkspaceSize@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnCreateDropoutDescriptor@libcudnn.so.8’未定义的引用
/home/tujunfeng/Application/nvidia/nvidia/cuda11/TensorRT-7.1.3.4/lib/libnvinfer.so：对‘cudnnSetConvolutionGroupCount@libcudnn.so.8’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/getSupportedAPITest.dir/build.make:124: recipe for target 'getSupportedAPITest' failed
make[2]: *** [getSupportedAPITest] Error 1
CMakeFiles/Makefile2:213: recipe for target 'CMakeFiles/getSupportedAPITest.dir/all' failed
make[1]: *** [CMakeFiles/getSupportedAPITest.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 92%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/optimizer/pass_registry.cc.o
[ 93%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
[ 94%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
[ 96%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
[ 97%] Linking CXX static library libonnx.a
[ 97%] Built target onnx
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
the error from the TensorRT-7.1.3.4/lib/libnvinfer.so and TensorRT-7.1.3.4/lib/libmyelin.so. the word "未定义的引用" can be understood as "undefined reference", this is my teacher's computer so i can't change the language. could someone help me?
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------

**Comment by kalenforn** [comment]
it is my error.i have solve this.thanks!

**Comment by bladesaber** [comment]
I meet a similar problem, would you like to share how to solve it :)

**Comment by kalenforn** [comment]
> I meet a similar problem, would you like to share how to solve it :)

I forget how I slove it,maybe your CUDA version is not supported or add TENSORRT_ROOT=/path/to/your/tensorrt/installed/dir to your ~/.bashrc.
