### ISSUE TITLE
Converting ONNX to .trt Engine in Xavier NX

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [onnx/onnx-tensorrt#539]
Hi there, 
               I have a custom YOLOV3-TensorFlow model , my ultimate goal is to convert this model to trt engine and run in Xavier NX. 
Now I have a few questions about that. 

1. I am able to convert .pb weights to .onnx on Titan V gpu however unable to convert on GTX 1080 Ti and Xavier NX (The process killed , might be due to memory problem). So If I Convert .pb > .onnx > .trt  on Titian V , can I use this converted trt engine on Xavier NX?  Or I must convert it in Xavier using same TensorRT version and other used libraries? 

2. After conversion from  .pb to .onnx , is there any method to verify if my mode is converted right or not?  Because I am facing problem in conversion from .onnx to .trt. 
 
3. Is there any method to directly converted  frozen_graph.pb to .trt engine? 

1. If I successfully convert  model to .trt Engine , How I can use it for real time object detection in Xavier NX? Is there any sample codes for yolov3 (without .cfg and .weights because it's tensorflow model)?

**Comment by kevinch-nv** [comment]
See my responses inline: 

> 1. I am able to convert .pb weights to .onnx on Titan V gpu however unable to convert on GTX 1080 Ti and Xavier NX (The process killed , might be due to memory problem). So If I Convert .pb > .onnx > .trt  on Titian V , can I use this converted trt engine on Xavier NX?  Or I must convert it in Xavier using same TensorRT version and other used libraries?

TRT engines are device and version specific - so you'll have to create the engine on the device you are deploying on.

> 2. After conversion from  .pb to .onnx , is there any method to verify if my mode is converted right or not?  Because I am facing problem in conversion from .onnx to .trt.

You can use a different backend (such as onnx-runtime) to verify that the ONNX file you've created is correct. You can use our [polygraphy](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy) tool to run inference on different backends including TensorRT.

> 3. Is there any method to directly converted  frozen_graph.pb to .trt engine?

You can try using the TF-TRT library, more details can be found here: https://github.com/tensorflow/tensorrt

> 4. If I successfully convert  model to .trt Engine , How I can use it for real time object detection in Xavier NX? Is there any sample codes for yolov3 (without .cfg and .weights because it's tensorflow model)?

We have a python example that is shipped with the TensorRT package under `samples/python/yolov3_onnx` that you can look at for an example.
