### ISSUE TITLE
crt/host_config.h No such file

### ISSUE THREAD

**Issue by bladesaber** [onnx/onnx-tensorrt#544]
Excuse me, can some someone meet similar error and give me a hand. :) 

the steps I follow:
1. git clone -b 6.0 --single-branch https://github.com/onnx/onnx-tensorrt.git
2. cd onnx-tensorrt/
3. git submodule update --init --recursive
4. mkdir build && cd build
5. cmake .. -DTENSORRT_ROOT=/home/blade/Downloads/TensorRT-6.0.1.5 -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include

my environment:
CUDA:10.0
Tensorrt:6.0.1.5

the error I meet:
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/bladesaber/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_28caf/fast"
    /usr/bin/make -f CMakeFiles/cmTC_28caf.dir/build.make CMakeFiles/cmTC_28caf.dir/build
    make[1]: Entering directory '/home/bladesaber/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_28caf.dir/main.cu.o
    /usr/local/cuda/bin/nvcc     -x cu -c /home/bladesaber/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_28caf.dir/main.cu.o
    In file included from <command-line>:0:0:
    /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:83:10: fatal error: crt/host_config.h: No such file or directory
     #include "crt/host_config.h"
              ^~~~~~~~~~~~~~~~~~~
    compilation terminated.
    CMakeFiles/cmTC_28caf.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_28caf.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_28caf.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/home/bladesaber/Desktop/onnx-tensorrt/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_28caf/fast' failed
    make: *** [cmTC_28caf/fast] Error 2

**Comment by kevinch-nv** [comment]
Can you double check your CUDA installation? On my machine this header exists under `/usr/local/cuda-10.0/include/crt/host_config.h`

**Comment by bladesaber** [comment]
@kevinch-nv thanks for your advise , :), I solve it.

**Comment by xdtzzz** [comment]
hi, i have meet this question, too.  and my header exists/usr/local/cuda/include/crt/host_config.h, too. But i still meet this question, can you help me?
thank you in advance!!!
