### ISSUE TITLE
Fail to build at step "make -j"

### ISSUE THREAD

**Issue by shroudie** [onnx/onnx-tensorrt#550]
It looks like a really good and convenient library, but I have failed to build it multiple times. 

cmake correctly generates buildfiles, but "make -j" does not generate any error messages but causes my whole system to freeze, and I had to forcefully shutdown my pc. I've tried 3 times they are all the same.

Any one facing similar issues could share some thoughts? Thanks

My environment:
Ubuntu 20.04
cuda 10.2
tensorrt 7.2.1

**Comment by mk-nvidia** [comment]
Can you try `make -j12` instead of `make -j`. `make` might be creating so many parallel jobs that you might be running out of system memory, resulting in the kernel invoking the OOM killer. This could somehow be making your system unstable.

**Comment by shroudie** [comment]
> @shroudie Can you try `make -j12` instead of `make -j`. `make` might be creating so many parallel jobs that you might be running out of system memory, resulting in the kernel invoking the OOM killer. This could somehow be making your system unstable.

Yeah that worked, should've be more familiar with make before I asked this question. Thanks alot

**Comment by aditdoshi333** [comment]
Thanks a lot. 

> @shroudie Can you try `make -j12` instead of `make -j`. `make` might be creating so many parallel jobs that you might be running out of system memory, resulting in the kernel invoking the OOM killer. This could somehow be making your system unstable.
