### ISSUE TITLE
Can't Convert a Classification Network Based on 1st two Blocks of Resnet18 fron ONNX to TensorRT Engine

### ISSUE THREAD

**Issue by mmaaz60** [onnx/onnx-tensorrt#562]
[checkpoint_2.zip](https://github.com/onnx/onnx-tensorrt/files/5501700/checkpoint_2.zip)

Base Platform: PyTorch
PyTorch Version: 1.6.0
TorchVision: 0.7.0

ONNX has dynamic shapes.

**Command used to convert onnx to trt:**

trtexec --onnx=checkpoin_2.onnx --explicitBatch --optShapes=actual_input_1:3x3x50x100 --maxShapes=actual_input_1:256x3x50x100 --minShapes=actual_input_1:1x3x50x100 --saveEngine=checkpoint_2.trt

**Error:**

[11/06/2020-11:44:22] [W] [TRT] onnx2trt_utils.cpp:217: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
ERROR: builtin_op_importers.cpp:359 In function importClip:
[8] Assertion failed: inputs.at(2).is_weights() && "Clip max value must be an initializer!"
[11/06/2020-11:44:22] [E] Failed to parse onnx file
[11/06/2020-11:44:22] [E] Parsing model failed
[11/06/2020-11:44:22] [E] Engine creation failed
[11/06/2020-11:44:22] [E] Engine set up failed

Any help would be highly appreciated.

**Grateful,**
M. Maaz

**Comment by volpepe** [comment]
I'm having the same problem, did you find a solution?

**Comment by mmaaz60** [comment]
> I'm having the same problem, did you find a solution?

Yes, I got done with this. As you can see it's the Clip layer that was causing trouble. You must set the max value in the Clip layer to convert it from ONNX to TensorRT engine. You can edit the ONNX graph to achieve this.

**Comment by volpepe** [comment]
> You can edit the ONNX graph to achieve this.

Alright, thanks! I wasn't aware that the ONNX graph could be edited!

**Comment by kevinch-nv** [comment]
Closing as this seems resolved.

**Comment by xjsxujingsong** [comment]
@mmaaz60 I met the same problem using C++ code to convert onnx to tensorrt. Is there anyway to solve this problem? What is "ONNX graph "?
