### ISSUE TITLE
QLinearConv and QLinearMatMul implementations -- where to find them?

### ISSUE THREAD

**Issue by Nedae** [onnx/onnx-tensorrt#567]
Hi,
I am trying to convert quantized onnx models to tensorRT. For thatI need to create custom layers/plugins in tensorRt from `QLinearConv` and `QLinearMatMul`  (which are not currently supported by them). 

I browsed in `onnx/onnx` repo, and the only place I could get to was 
https://github.com/onnx/onnx/blob/a7a0fec7f25cae567429af62b7eaaee1c3f0e247/onnx/defs/nn/defs.cc#L857
https://github.com/onnx/onnx/blob/274e8b54e4c11c40a8c0a89599196f5311088b64/onnx/defs/math/defs.cc#L2286
but, not further than that and I am basically stuck here.

So, where is the actual implementation of these two ops?  I would appreciate if you could point me to `onnx ops implementations`.

**Comment by Nedae** [comment]
@kevinch-nv can you help please?

**Comment by Nedae** [comment]
@linkerzhang , @askhade can you help please?

**Comment by kevinch-nv** [comment]
@Nadae see my response in #560. Closing this as duplicate.
