### ISSUE TITLE
Compile error due to std::move

### ISSUE THREAD

**Issue by matthill** [onnx/onnx-tensorrt#571]
Compiling against the latest software on Ubuntu 20.04 and GCC 9, I get the following error:

cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘std::vector<nvinfer1::PluginField> onnx2trt::{anonymous}::loadFields(string_map<std::vector<unsigned char> >&, const OnnxAttrs&, const nvinfer1::PluginFieldCollection*)’:

cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3737:21: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
 3737 |     return std::move(fields);
      |            ~~~~~~~~~^~~~~~~~

I see some discussion here: http://www.cplusplus.com/forum/general/186411/

**Comment by kevinch-nv** [comment]
This was fixed in #568. Closing.
