### ISSUE TITLE
Cannot run global average pool on an input with dynamic spatial dimensions!

### ISSUE THREAD

**Issue by duducode** [onnx/onnx-tensorrt#581]
the model exported   torch1.5  and the  onnx1.6,onnx-tensorrt-7.0

**Comment by kevinch-nv** [comment]
I don't see that assertion on the latest [7.0 commit](https://github.com/onnx/onnx-tensorrt/blob/6f649111e5c720b526351c120bc5f63f0ff84c90/builtin_op_importers.cpp#L1152), do you have the latest build?
