### ISSUE TITLE
What does min and max clip values must be an initializer mean?

### ISSUE THREAD

**Issue by kochsebastian** [onnx/onnx-tensorrt#586]
I want to use clip in my network. When converting to TensorRT I get "Clip max value must be an initializer!"   
I think it's easily solvable but I just don't know what that means.
Clarification or explanation would be nice

**Comment by pranavm-nvidia** [comment]
An initializer in ONNX is just a constant in the graph. It sounds like in your case, the max value is being computed at inference time.

**Comment by kochsebastian** [comment]
Actually I think the problem was that I only gave a max value. When I added a min value with -inf. It worked fine.  
The max value was indeed calculated at inference time. But this doesn't seem to cause a problem
