### ISSUE TITLE
 NvOnnxParser.h:26:21: fatal error: NvInfer.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by wangzilu** [onnx/onnx-tensorrt#59]
wang@ian:~/Downloads/onnx-tensorrt$ python setup.py build
running build
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/onnx_tensorrt
copying onnx_tensorrt/__init__.py -> build/lib.linux-x86_64-2.7/onnx_tensorrt
copying onnx_tensorrt/tensorrt_engine.py -> build/lib.linux-x86_64-2.7/onnx_tensorrt
copying onnx_tensorrt/backend.py -> build/lib.linux-x86_64-2.7/onnx_tensorrt
creating build/lib.linux-x86_64-2.7/onnx_tensorrt/parser
copying onnx_tensorrt/parser/__init__.py -> build/lib.linux-x86_64-2.7/onnx_tensorrt/parser
creating build/lib.linux-x86_64-2.7/onnx_tensorrt/runtime
copying onnx_tensorrt/runtime/__init__.py -> build/lib.linux-x86_64-2.7/onnx_tensorrt/runtime
running build_ext
building 'onnx_tensorrt.parser._nv_onnx_parser_bindings' extension
swigging nv_onnx_parser_bindings.i to nv_onnx_parser_bindings_wrap.cpp
swig -python -c++ -modern -builtin -o nv_onnx_parser_bindings_wrap.cpp nv_onnx_parser_bindings.i
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c nv_onnx_parser_bindings_wrap.cpp -o build/temp.linux-x86_64-2.7/nv_onnx_parser_bindings_wrap.o -std=c++11 -DUNIX -D__UNIX -m64 -fPIC -O2 -w -fmessage-length=0 -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -Wall -DSWIG
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from nv_onnx_parser_bindings_wrap.cpp:3580:0:
NvOnnxParser.h:26:21: fatal error: NvInfer.h: No such file or directory
compilation terminated.

**Comment by yinghai** [comment]
@wangzilu Hi, where did you install your TensorRT lib?

**Comment by wangzilu** [comment]
@yinghai Hi, thank you for your replying. TensorRT lib is in /home/wang/Downloads/TensorRT-4.0.1.6/lib

where wang is my user name. Could you give some help please.

**Comment by yinghai** [comment]
Could you try 
```
TENSORRT_ROOT= /home/wang/Downloads/TensorRT-4.0.1.6 python setup.py build
```

**Comment by xperzy** [comment]
@yinghai I had the same problem and tried TENSORRT_ROOT= ...  python setup.py build,
It still fails with "NnInfer.h: No such file or directoty" error

**Comment by yinghai** [comment]
Could you find where your `NvInfer.h` file is located? It should be in the include directory of the tensorrt lib you downloaded. For example, if it's `/opt/tensorrt/include`, you can use 
```
INC = ["-L/opt/tensorrt/include"]
```
in https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L25

**Comment by xperzy** [comment]
> Could you find where your `NvInfer.h` file is located? It should be in the include directory of the tensorrt lib you downloaded. For example, if it's `/opt/tensorrt/include`, you can use
> 
> ```
> INC_DIRS = ["-L/opt/tensorrt/include"]
> ```
> in https://github.com/onnx/onnx-tensorrt/blob/master/setup.py#L25

Thanks, I added 

INC_DIRS = ["MY/PATH/TO/tensorrt/include"]

This works!  I think "-L" is not needed.

**Comment by yinghai** [comment]
@xperzy Ah, right! Great that it works for you!
