### ISSUE TITLE
 Assertion failed: !empty() ../builder/intInterval.cpp:20 Aborting...

### ISSUE THREAD

**Issue by Jialeen** [onnx/onnx-tensorrt#596]
I am trying to convert deeplabV3+ (tf onnx,  https://github.com/rishizek/tensorflow-deeplab-v3-plus ) to TensorRT engine, but it gives me following errorr:
 
[2020-12-21 02:38:02     BUG] Assertion failed: !empty()
../builder/intInterval.cpp:20
Aborting...
[2020-12-21 02:38:02   ERROR] ../builder/intInterval.cpp (20) - Assertion Error in min: 0 (!empty())
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)

How can I solve this problem?
Thanks!

**Comment by kevinch-nv** [comment]
What TRT version are you using? How are you generating the TRT engine?

**Comment by kevinch-nv** [comment]
Closing due to no repro provided.
