### ISSUE TITLE
Build onnx2trt problem on Windows10

### ISSUE THREAD

**Issue by lllsiriuslll** [onnx/onnx-tensorrt#60]
Hi.

Recently, TensorRT 5 RC for Windows has been released. 
So I am trying to build onnx2trt on Windows 10. 
However, code seems to be written for Linux, and I have failed to build. 
Is there a way to make it build on Windows?

Thanks.

**Comment by yinghai** [comment]
I don't think it current code is written with Windows support in mind. But cmake supports windows, you can try building it and see what happens.

**Comment by lllsiriuslll** [comment]
Hi.
I am sorry, reply is late.
This problem was solved by supporting onnxparser in TensorRT 5 GA version.
Thanks.

**Comment by ZhuoranLyu** [comment]
@lllsiriuslll Hi, did you run onnx2trt successfully on windows?

**Comment by xinsuinizhuan** [comment]
> @lllsiriuslll Hi, did you run onnx2trt successfully on windows?

did yo have compiled it on windows?
