### ISSUE TITLE
请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。

### ISSUE THREAD

**Issue by Wulingtian** [onnx/onnx-tensorrt#607]
![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103402073-77a5fd80-4b86-11eb-8f1d-ca24a9184b12.jpg)
有onnx转trt int8的推理速度还是很快的，5ms左右，就是不出框。。。
有人能一起交流一下吗？

**Comment by ttyio** [comment]
hello @Wulingtian ,
 this is duplicate to https://github.com/NVIDIA/TensorRT/issues/997
I will triage this issue, could you also send me the code to repro the issue? thanks!

**Comment by Wulingtian** [comment]
我怎么发给你呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaodong (Vincent) Huang"<notifications@github.com&gt;; 
发送时间: 2021年1月23日(星期六) 上午9:40
收件人: "onnx/onnx-tensorrt"<onnx-tensorrt@noreply.github.com&gt;; 
抄送: "willer"<2813389262@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [onnx/onnx-tensorrt] 请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。 (#607)





 
hello @Wulingtian ,
 this is duplicate to NVIDIA/TensorRT#997
 I will triage this issue, could you also send me the code to repro the issue? thanks!

**Comment by Wulingtian** [comment]
> hello @Wulingtian ,
> this is duplicate to [NVIDIA/TensorRT#997](https://github.com/NVIDIA/TensorRT/issues/997)
> I will triage this issue, could you also send me the code to repro the issue? thanks!

可以给我你的邮箱吗？

**Comment by ttyio** [comment]
@Wulingtian  vincenth#nvidia.com, thanks!
