### ISSUE TITLE
Question about converting quantized 8-bit onnx model to tensorrt

### ISSUE THREAD

**Issue by zccyman** [onnx/onnx-tensorrt#608]
- Relevant 8-bit Quantization (https://github.com/yhhhli/APoT_Quantization/blob/master/ImageNet/models/quant_layer.py)

I am trying to convert an already quantized 8-bit onnx model to tensorrt!
onnx version : 1.8.0
tensorrt version: 7.2.1.6

When I try to parse my quantized onnx network, I get the following error
````
ERROR: Failed to parse the ONNX file.
In node -1 (importConv): UNSUPPORTED_NODE: Assertion failed: ctx->network()->hasExplicitPrecision() && "TensorRT only supports multi-input conv for explicit precision QAT networks!"
````

**Comment by kevinch-nv** [comment]
You'll need to populate the explicit precision flag when creating the TensorRT network.

```
auto networkFlags = 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kEXPLICIT_BATCH) | 1U << static_cast<uint32_t>(nvinfer1::NetworkDefinitionCreationFlag::kEXPLICIT_PRECISION);
auto network = builder->createNetworkV2(networkFlags)

**Comment by jinfagang** [comment]
@kevinch-nv Hi, I met this error even I am covert a float32 onnx model to tensorrt.

```
[8] Assertion failed: ctx->network()->hasExplicitPrecision() && "TensorRT only supports multi-input conv for explicit precision QAT networks!"

```

The code raises this error is:

```
seg_preds = F.conv2d(seg_preds, kernel_preds,
                             stride=1).squeeze(0).sigmoid()
```

Do u have any idea why it behavior like that?

**Comment by jinfagang** [comment]
@kevinch-nv Hi, any response of this question?

@zccyman Any solution?

**Comment by kevinch-nv** [comment]
See my reply on 1/22 - are you creating your network definition with both the explict batch and explicit precision flag set?

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, we can help you solve quantization problems
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md
