### ISSUE TITLE
Python AttributeError: module 'tensorrt' has no attribute 'infer' TensorRT 5.0.0.10

### ISSUE THREAD

**Issue by xperzy** [onnx/onnx-tensorrt#61]
I know RT 5 is still RC release, just remind someone like me who are using RT 5.0:

Python will raise an error " no attribute 'infer' " when running "backend.prepare..."

I checked TensorRT 5.0.0.10 python interface, which does NOT have 'infer' module.

**Comment by benbarsdell** [comment]
https://github.com/onnx/onnx-tensorrt/pull/50 may fix the issue; can you try it?

**Comment by xperzy** [comment]
> #50 may fix the issue; can you try it?

Yes, I have modified related python files and reinstall the python interface, now there is no import error and the basic example seems working without error.  Will try more complicated models using RT 5.0.

Thanks.

**Comment by pechora** [comment]
Facing the same issue, can anyone please point out the changes required.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/onnx_tensorrt-0.1.0-py3.5-linux-x86_64.egg/onnx_tensorrt/backend.py", line 178, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/onnx_tensorrt-0.1.0-py3.5-linux-x86_64.egg/onnx_tensorrt/backend.py", line 60, in __init__
    self._logger = trt.infer.ConsoleLogger(trt.infer.LogSeverity.WARNING)
AttributeError: module 'tensorrt' has no attribute 'infer'`

**Comment by jinfagang** [comment]
Same error here

**Comment by Tian14267** [comment]
Do you solve this problem? I get same problem... @jinfagang @pechora
