### ISSUE TITLE
/home/jetson7/coding/onnx-tensorrt/third_party/onnx    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by leeyunhome** [onnx/onnx-tensorrt#611]
Hello,
Thank you for sharing good material.

I encountered the following error.
jetson7@jetson7-desktop:~/coding/onnx-tensorrt/build$ cmake .. -DTENSORRT_ROOT=/usr/lib/tensorrt && make -j
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.8.0") 
CMake Error at CMakeLists.txt:102 (add_subdirectory):
  The source directory

    /home/jetson7/coding/onnx-tensorrt/third_party/onnx

  does not contain a CMakeLists.txt file.

-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so;/usr/lib/aarch64-linux-gnu/libmyelin.so
-- Found TENSORRT: /usr/include/aarch64-linux-gnu  
-- Configuring incomplete, errors occurred!
See also "/home/jetson7/coding/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/jetson7/coding/onnx-tensorrt/build/CMakeFiles/CMakeError.log".

Can you tell me how to solve this problem?

Thank you.

**Comment by kelia** [comment]
make sure to update the submodule after cloning the repo. 
I.e., after cloning:
```
git submodule init
git submodule update
```

**Comment by kevinch-nv** [comment]
Thanks @kelia for the response. This error occurs because you haven't synced all the required submodules to build. Closing this issue.

**Comment by cuge1995** [comment]
> make sure to update the submodule after cloning the repo.
> I.e., after cloning:
> 
> ```
> git submodule init
> git submodule update
> ```

that works for me
