### ISSUE TITLE
ScatterND is not supported

### ISSUE THREAD

**Issue by ajaichemmanam** [onnx/onnx-tensorrt#618]
I was trying to convert pytorch model to onnx and then to tensorrt .

However
    kps[..., ::2] += xs.view(batch, K, 1).expand(batch, K, num_joints)
    kps[..., 1::2] += ys.view(batch, K, 1).expand(batch, K, num_joints)
this line of code causes ScatterND not supported error. Any solution or workaround for it?

**Comment by kevinch-nv** [comment]
Marking this as an enhancement for supporting ScatterND in the future.

**Comment by chenjun2hao** [comment]
@kevinch-nv ,Any other ways to bypass this operator？

**Comment by jinfagang** [comment]
This can be avoided by switching inplace index by concate.

**Comment by chenjun2hao** [comment]
> This can be avoided by switching inplace index by concate.

thanks, i have solved.

**Comment by ajaichemmanam** [comment]
How to concatenate in my case?

```
kps[..., ::2] += xs.view(batch, K, 1).expand(batch, K, num_joints)
kps[..., 1::2] += ys.view(batch, K, 1).expand(batch, K, num_joints)
```

How to replace this code?

**Comment by muyoucun** [comment]
> How to concatenate in my case?
> 
> ```
> kps[..., ::2] += xs.view(batch, K, 1).expand(batch, K, num_joints)
> kps[..., 1::2] += ys.view(batch, K, 1).expand(batch, K, num_joints)
> ```
> 
> How to replace this code?

sorry but do you know how to solve this now?

**Comment by kevinch-nv** [comment]
ScatterND has been added now (in TensorRT 8.2), so closing off this issue.

If you are still having trouble importing your model with latest TensorRT, please open a new issue.
