### ISSUE TITLE
Is onnx-tensorrt supported on jetson TX2?

### ISSUE THREAD

**Issue by zbw4034** [onnx/onnx-tensorrt#62]
Hi,I have seen that onnx-tensorrt requires tensorrt3.0+,and now jetson TX2 supports Tensorrt 4.0.
So is onnx-tensorrt supported on TX2 or did anyone ever run through onnx-tensorrt on TX2 successfully?

Thanks a lot for anyone providing helpful suggestion!

**Comment by yinghai** [comment]
Yes, it should be.

**Comment by nchafni** [comment]
@zbw4034 did you get this working?

**Comment by nchafni** [comment]
@yinghai does this need the python tensorrt api?

**Comment by yinghai** [comment]
@nchafni It's optional, not necessary.

**Comment by nchafni** [comment]
I get an ImportError: No module named tensorrt, i removed it from setup.py. have you used this on the jetson before?

**Comment by yinghai** [comment]
Nope. I usually do `cmake` instead of `setup.py`.

**Comment by jeremyolsen** [comment]
TensorRT python api is not supported on the TX2 according to Nvidia.  Mod gave an example of how to create a chat bot using the TX2 and TensorRT using UFF models.  I'm not sure on how this would apply to ONNX model types though.

https://devtalk.nvidia.com/default/topic/1042900/tensorrt/when-can-jetson-tx2-support-tensorrt-python-api-or-how-to-use-onnx-tensorrt-on-tx2-/

**Comment by TawitU** [comment]
@bpinaya Is that meant you are running TRT5.0.2 GA on TX2? I am curious if TRT5.0.2 GA will support Python API on TX2.

**Comment by bpinaya** [comment]
Hi there @TawitU nope, jetpack isn't shipping with trt5ga for the TX2 as far as I'm aware. I've just used it on a host pc. Also the python API seems to have been redesigned so I don't think it's super stable.

**Comment by TawitU** [comment]
@bpinaya Thanks for the info. I am looking forward to TensorRT Python API on TX2 too.

**Comment by kevinch-nv** [comment]
Yes, TensorRT and onnx-tensorrt are supported on Jetson platforms. See [here](https://developer.nvidia.com/embedded/jetpack) for the latest information about jetpack installation, and see these [instructions](https://github.com/NVIDIA/TensorRT#setting-up-the-build-environment) for the most up-to-date information about cross-compiling TensorRT open source components (including onnx-tensorrt) on Jetson platforms. Closing this issue - feel free to reopen if you are still having troubles with newer TensorRT versions.
