### ISSUE TITLE
How to add a new layer with plugin?

### ISSUE THREAD

**Issue by runningJ** [onnx/onnx-tensorrt#63]

**Comment by kevinch-nv** [comment]
New layers are supported through the TensorRT [plugin API](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending).

As a concreate example, the InstanceNormalization node in onnx-tensorrt is handled by the (instance normalization plugin)[https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin] available in the main TensorRT open source repository. You can use this as base for writing your plugin.

If you need further clarification, feel free to reopen this issue with your specific questions.
