### ISSUE TITLE
"make" occurs error "nvinfer1"  

### ISSUE THREAD

**Issue by GeorgeBohw** [onnx/onnx-tensorrt#630]
os：ubuntu
tensorrt:7.0

when install onnx-tensorrt,execute command "make":
/home/mk/qiaobaohua/onnx_tensorrt/onnx-tensorrt/ShapeTensor.cpp:444:14: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
     shuffle->setZeroIsPlaceholder(zeroIsPlaceholder);
              ^~~~~~~~~~~~~~~~~~~~
/home/mk/qiaobaohua/onnx_tensorrt/onnx-tensorrt/ShapeTensor.cpp: In function ‘nvinfer1::IShuffleLayer* onnx2trt::addShuffle(onnx2trt::IImporterContext*, nvinfer1::ITensor&, const onnx2trt::ShapeTensor&, bool)’:
/home/mk/qiaobaohua/onnx_tensorrt/onnx-tensorrt/ShapeTensor.cpp:444:14: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
     shuffle->setZeroIsPlaceholder(zeroIsPlaceholder);
              ^~~~~~~~~~~~~~~~~~~~

**Comment by kevinch-nv** [comment]
This looks like a mismatch between the TRT version and the ONNX-TRT version you are using. Are you building off the master or 7.0 branch?

**Comment by GeorgeBohw** [comment]
@kevinch-nv thanks，i use the wrong version of TRT,it has resolved!
