### ISSUE TITLE
Supported / Unsupported operators in ONNX-->TRT

### ISSUE THREAD

**Issue by israelwei** [onnx/onnx-tensorrt#635]
Hey,
The webpage I used so far for the Supported / Unsupported operators in ONNX-->TRT, is not available now:
https://github.com/onnx/onnx-tensorrt/blob/master/operators.md
Can you please fix this page / update how to get to the webpage of the operators?

**Comment by kevinch-nv** [comment]
In the recent 21.02 release we have moved the location of the doc to: https://github.com/onnx/onnx-tensorrt/blob/master/docs/operators.md
