### ISSUE TITLE
facing building error in cmake command

### ISSUE THREAD

**Issue by nikhil-salodkar** [onnx/onnx-tensorrt#636]
## Description

The below installation is being tried inside the docker container which was built by following the instructions in TensorRT github repo and here : https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT. I am successfully able to follow instructions and convert bert models to plans and use them to do inference as instructed in the link above. 
The reason I am trying out this repo is because I am interested in easier way for converting onnx models to trt plans.

while running this command : 
```
cmake .. -DTENSORRT_ROOT=<path_to_trt> && make -j
```
with path_to_trt as workspace/TensorRT , I am getting following error : 
```
-- Found TensorRT headers at /workspace/TensorRT/include
-- Find TensorRT libs at TENSORRT_LIBRARY_INFER-NOTFOUND;TENSORRT_LIBRARY_INFER_PLUGIN-NOTFOUND;TENSORRT_LIBRARY_MYELIN-NOTFOUND
-- Could NOT find TENSORRT (missing: TENSORRT_LIBRARY) 
ERRORCannot find TensorRT library.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TENSORRT_LIBRARY_INFER
    linked by target "nvonnxparser_static" in directory /workspace/onnx-tensorrt
    linked by target "nvonnxparser" in directory /workspace/onnx-tensorrt
TENSORRT_LIBRARY_INFER_PLUGIN
    linked by target "nvonnxparser_static" in directory /workspace/onnx-tensorrt
    linked by target "nvonnxparser" in directory /workspace/onnx-tensorrt
TENSORRT_LIBRARY_MYELIN
    linked by target "nvonnxparser_static" in directory /workspace/onnx-tensorrt
    linked by target "nvonnxparser" in directory /workspace/onnx-tensorrt

-- Configuring incomplete, errors occurred!
See also "/workspace/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/workspace/onnx-tensorrt/build/CMakeFiles/CMakeError.log".
```
not able to figure out what files am I missing or what installation instructions could I have missed

## Environment

**TensorRT Version**: TensorRT-7.2.2.3 
**ONNX-TensorRT Version / Branch**: master
**GPU Type**: Nvidia T4
**Nvidia Driver Version**: 440.64.00
**CUDA Version**: 10.2
**CUDNN Version**: cannot ascertain this inside the container. but was able to perform inference using the tutorial as mentioned above
nvcc --version output : 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```
nvidia-smi output : 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9

Please help in resolving this issue. 
Much appreciated
Thanks

**Comment by kevinch-nv** [comment]
If you are using the container in the TensorRT repository, your `-DTENSORRT_ROOT` should be `TRT_RELEASE`, which I think is mapped to the `/tensorrt` directory inside the container.

**Comment by nikhil-salodkar** [comment]
Thanks a lot for pointing that out. It is working now.

**Comment by owoshch** [comment]
Hi @nikhil-salodkar! Can you please share the final command that helped you to fix the issue?
I'm trying to install onnx-tensorrt library from the official tensorrt docker container and I'm facing the same issue with ERRORCannot find TensorRT library.

**Comment by Biaocsu** [comment]
Hi @owoshch , I have the problem either, please share the command if you already solved it, thanks

**Comment by wangxudong-cq** [comment]
me too @nikhil-salodkar

**Comment by kevinch-nv** [comment]
With the most recent containers, the TensorRT libs and headers are pre-installed in the default lib / include paths. You would only need to run `cmake ..` inside the build directory to build.

**Comment by wangxudong-cq** [comment]
@kevinch-nv not containers, steps as blow:
git clone -b master https://github.com/nvidia/TensorRT TensorRT
cd TensorRT
git submodule update --init --recursive
mkdir -p build && cd build
cmake .. 
make -j$(nproc)

**Comment by wangxudong-cq** [comment]
@kevinch-nv I got it , I  need download TENSORRT GA release first, and specify the TRT_LIB_DIR.
