### ISSUE TITLE
Network has dynamic or shape inputs, but no optimization profile has been defined

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [onnx/onnx-tensorrt#638]
## Environment

**TensorRT Version**:  7.1.3
**ONNX-TensorRT Version / Branch**: master
**GPU Type**: jetson xavior
**Nvidia Driver Version**: 
**CUDA Version**: 10.2.89
**CUDNN Version**: 8.0.0.180
**Operating System + Version**: 
**Python Version (if applicable)**: 3.6
**TensorFlow + TF2ONNX Version (if applicable)**: tf q2.3
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce
Generated onnx file from savedmodel file by following the below github
https://github.com/onnx/tensorflow-onnx
Then trying to load and prepare trt engine as below by giving correct onnx file path
   model = onnx.load(onnx_path)
    engine = backend.prepare(model)

am getting the following error:
**[TensorRT] ERROR: Network has dynamic or shape inputs, but no optimization profile has been defined.
[TensorRT] ERROR: Network validation failed.
Traceback (most recent call last):
  File "onnx_trt.py", line 22, in <module>
    main()
  File "onnx_trt.py", line 14, in main
    engine = backend.prepare(model)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-aarch64.egg/onnx_tensorrt/backend.py", line 200, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/onnx_tensorrt-0.1.0-py3.6-linux-aarch64.egg/onnx_tensorrt/backend.py", line 100, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network**

**Comment by kevinch-nv** [comment]
Does the model run with trtexec?

**Comment by VeeranjaneyuluToka** [comment]
I just now tried with trtexec command as below
./trtexec --onnx=/data/Veeru/models/classification/thebeast_onnx/model_thebeast.onnx --shapes=input:8X456x456x3
got something like below
PASSED TensorRT.trtexec # ./trtexec --onnx=/data/Veeru/models/classification/thebeast_onnx/model_thebeast.onnx --shapes=input:8X456x456x3
which means i think it is run correctly but how do i save trt file or will it save somewhere?
Thanks,
Veeru.

**Comment by VeeranjaneyuluToka** [comment]
I can save also using --saveEngine option, next am checking how to load trt file and run the inference.

**Comment by VeeranjaneyuluToka** [comment]
I could solve this issue using trtexec. so closing this issue.
