### ISSUE TITLE
In node -1 (importInstanceNormalization): UNSUPPORTED_NODE: Assertion failed: !isDynamic(tensorPtr->getDimensions()) && "Instancoes not support dynamic inputs!"

### ISSUE THREAD

**Issue by ThrillerWYY** [onnx/onnx-tensorrt#639]
## Description

when i convert model.onnx to model.trt, i met this problem, somebody suggested update the version,but it's useless for me . Has anybody solved this problem?

## Environment

**TensorRT Version**: 7.1.3.4
**ONNX-TensorRT Version / Branch**: onnx16.0
**GPU Type**: GTX2080Ti
**Nvidia Driver Version**: 440.33
**CUDA Version**: cuda10.2
**CUDNN Version**: 8.0
**Operating System + Version**: linux ubuntu
**Python Version (if applicable)**: python3.5
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**:pytorch1.5 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

```
import os
import torch
import tensorrt as trt
import sys

TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

def GiB(val):
    return val * 1 << 30

def conver_engine(onnx_file_path, engine_file_path="", max_batch_size=1):
    """Attempts to load a serialized engine if available, otherwise builds a new TensorRT engine and saves it."""
    """Takes an ONNX file and creates a TensorRT engine to run inference with"""
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_workspace_size = GiB(max_batch_size)
        builder.max_batch_size = max_batch_size
        # Parse model file
        if not os.path.exists(onnx_file_path):
            print('ONNX file {} not found, please run yolov3_to_onnx.py first to generate it.'.format(onnx_file_path))
            exit(0)
        print('Loading ONNX file from path {}...'.format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            if not parser.parse(model.read()):
                print ('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print (parser.get_error(error))
                return None
        # The actual yolov3.onnx is generated with batch size 64. Reshape input to batch size 1
        print('Completed parsing of ONNX file')
        print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
        engine = builder.build_cuda_engine(network)
        print("Completed creating Engine")
        with open(engine_file_path, "wb") as f:
            f.write(engine.serialize())
        print("Completed writing Engine. Well done!")

if __name__ == "__main__":
    onnx_file_path = 'weapon.onnx'
    engine_file_path = "weapon.trt"
    conver_engine(onnx_file_path, engine_file_path)


[TensorRT] VERBOSE: ModelImporter.cpp:125:  [Constant] inputs:
[TensorRT] VERBOSE: ModelImporter.cpp:179:  [Constant] outputs: [2381 -> (32)],
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node:  [InstanceNormalization]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 2379
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 2380
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 2381
[TensorRT] VERBOSE: ModelImporter.cpp:125:  [InstanceNormalization] inputs: [2379 -> (-1, 32, -1)], [2380 -> (32)], [2381 -> (32)],
ERROR: Failed to parse the ONNX file.
In node -1 (importInstanceNormalization): UNSUPPORTED_NODE: Assertion failed: !isDynamic(tensorPtr->getDimensions()) && "InstanceNormalization does not support dynamic inputs!"

```

**Comment by ThrillerWYY** [comment]
help....

**Comment by kevinch-nv** [comment]
@ThrillerWYY this limitation is no longer there on the latest version of TRT (7.2.3.4) on the master branch. Can you build the latest version and try importing your model again?

**Comment by duohaoxue** [comment]
I made the same mistake with TensorRT7.2.3.4

[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node:  [InstanceNormalization]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 512
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 513
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 514
[TensorRT] VERBOSE: ModelImporter.cpp:125:  [InstanceNormalization] inputs: [512 -> (-1, 32, -1)], [513 -> (32)], [514 -> (32)], 
ERROR: Failed to parse the ONNX file.
In node -1 (importInstanceNormalization): UNSUPPORTED_NODE: Assertion failed: !isDynamic(tensorPtr->getDimensions()) && "InstanceNormalization does not support dynamic inputs!"

**Comment by kevinch-nv** [comment]
This has been updated in TensorRT 8.x, we now support dynamic inputs for InstanceNormalization.

I recommend upgrading your version and importing your model again. If you are still having troubles feel free to re-open this issue.
