### ISSUE TITLE
trtexec works fine but onnx2trt yields "Network has dynamic or shape inputs, but no optimization profile has been defined"

### ISSUE THREAD

**Issue by codethief** [onnx/onnx-tensorrt#651]
## Description

I'm trying to convert a model from ONNX to TRT. The following works fine:

```
$ /usr/src/tensorrt/bin/trtexec --onnx=model.onnx --shapes=input_1:1x96x96x3
```

But 

```
$ onnx2trt model.onnx -o model.trt -b 1
```

yields

>  Network has dynamic or shape inputs, but no optimization profile has been defined.

Since `$ /usr/src/tensorrt/bin/trtexec --onnx=model.onnx --batch=1` results in the same error message, I assume I must pass the precise input shape to `onnx2trt`. Is there any way to do that? How else can I specify the "optimization profile" / fixate the input shape?

## Environment

**TensorRT Version**: 7.1.3
**ONNX-TensorRT Version / Branch**: 
```
./onnx2trt -V
Parser built against:
  ONNX IR version:  0.0.7
  TensorRT version: 7.1.3
```

**GPU Type**: Jetson Nano
**Nvidia Driver Version**: JetPack 4.4.1
**CUDA Version**: 10.2.89
**CUDNN Version**: 8.0.0.180
**Operating System + Version**:  Ubuntu 18.04, as included in the Nvidia SDK for the Jetson Nano

**Comment by codethief** [comment]
Never mind, I just realized that onnx-tensorrt for TensorRT 7.2.2 comes with dynamic shape support, so I should probably give this a try first.

**Comment by agrija9** [comment]
@codethief I have the same environment settings as yours (except I have a Jetson Xavier).

Were you able to test this on TensorRT 7.2.2? As far as I know, it is not possible to update TensorRT in the Jetson, the only option is to go from Jetpack 4.4 (trt 7.1.3) to let's say Jetpack 4.6 (trt 8.0.X).

**Comment by codethief** [comment]
@agrija9 Unfortunately, I haven't worked on this since summer last year, so I'm afraid I don't remember. But I think it ended up working.

As for updating TensorRT: What's preventing you from updating JetPack?

**Comment by agrija9** [comment]
@codethief I was able to convert from onnx into trt engine using the trtexec command that comes with TensorRT (still in trt 7.1.3) (I could not do it using onnx2trt).

In #328 it is recommended to use an ``--explicitBatch`` argument, so my conversion from onnx to trt looks like this:

```
/usr/src/tensorrt/bin/trtexec --explicitBatch --onnx=model.onnx  --saveEngine=model.engine
```

Regarding updating my JetPack, I am trying to run OpenPifPaf in my Jetson, however, I was having dependency issues with Jetpack 4.6 so I went with 4.4.
