### ISSUE TITLE
[8] Assertion failed: trt_dtype == nvinfer1::DataType::kHALF && cast_dtype == ::ONNX_NAMESPACE::TensorProto::FLOAT

### ISSUE THREAD

**Issue by Jucjiaswiss** [onnx/onnx-tensorrt#654]
Tensorrt:6
Platform: JetsonNano
![webwxgetmsgimg](https://user-images.githubusercontent.com/18287639/110924034-86feaf80-835c-11eb-8ff4-79c2fdb75c0f.jpeg)
 Anyone solved this ? Help!

**Comment by kevinch-nv** [comment]
This should be fixed in the latest TensorRT version.
