### ISSUE TITLE
UNSUPPORTED_NODE: Assertion failed: filter_dim.d[nbSpatialDims - i] == kernel_tensor_ptr->getDimensions().d[kernel_tensor_ptr->getDimensions().nbDims - i]

### ISSUE THREAD

**Issue by whcjb** [onnx/onnx-tensorrt#655]
## Description

convert onnx to tensorrt, occur  (convMultiInput): UNSUPPORTED_NODE: Assertion failed: filter_dim.d[nbSpatialDims - i] == kernel_tensor_ptr->getDimensions().d[kernel_tensor_ptr->getDimensions().nbDims - i] error

## Environment

**TensorRT Version**:  7.1.3.4
**ONNX-TensorRT Version / Branch**: 
**GPU Type**: p40
**Nvidia Driver Version**: 450.51.06 
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**: centos7
**Python Version (if applicable)**: 3.6
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.6
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

[TensorRT] VERBOSE: ImporterContext.hpp:141: Registering layer: Concat_1767 for ONNX node: Concat_1767
[TensorRT] VERBOSE: ImporterContext.hpp:116: Registering tensor: 2012 for ONNX tensor: 2012
[TensorRT] VERBOSE: ModelImporter.cpp:179: Concat_1767 [Concat] outputs: [2012 -> (-1, -1, -1, -1)],
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Conv_1768 [Conv]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 2012
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 1954
[TensorRT] VERBOSE: ModelImporter.cpp:125: Conv_1768 [Conv] inputs: [2012 -> (-1, -1, -1, -1)], [1954 -> (-1, -1, -1, -1)],
ERROR: Failed to parse the ONNX file.
In node -1 (convMultiInput): UNSUPPORTED_NODE: Assertion failed: filter_dim.d[nbSpatialDims - i] == kernel_tensor_ptr->getDimensions().d[kernel_tensor_ptr->getDimensions().nbDims - i]

## Steps To Reproduce

 i find it's using ```F.conv2d(x, y) ``` that cause the problem.
the x, y is onling tensor， not fixed

**Comment by DeathKnightChen** [comment]
@whcjb Hi, I met the same issue. Have you solved this yet? Thanks.

**Comment by furkancoskun** [comment]
@whcjb Is there any update on this problem?

**Comment by oxana-nvidia** [comment]
Hi @whcjb, 

Could you please try if the issue is still present with more recent version of TensorRT? 
I've tried some tests with TensorRT 8.4 on random examples with conv2d and issue is not reproducible for me.

If the issue is still present could you please provide an example to reproduce it?

**Comment by oxana-nvidia** [comment]
Closing for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks
