### ISSUE TITLE
Would it be better to use elementwise instead of activation to implement Clip op?

### ISSUE THREAD

**Issue by grimoire** [onnx/onnx-tensorrt#664]
Hi,
There are some limits when we convert clip ops to TensorRT such as :
https://github.com/onnx/onnx-tensorrt/blob/984e57c7768a9bea3d2a8369ed199529f603d13b/builtin_op_importers.cpp#L414

It is inevitable cause the clip ops is built as an activation layer. Could we use elementwise max/min when max/min is not constant? That would remove the limit with negligible cost(I think).

**Comment by kevinch-nv** [comment]
Yes it's possible. Is there a network that you are trying to import that's blocked on this?

**Comment by grimoire** [comment]
Thanks for reply.
We are trying to convert object detection model. The Clip OP is used to clamp outputs of box regression. For now, I use some trick to do this like:
https://github.com/grimoire/mmdetection/blob/01a26ff36c25317db137b7efb3ec8d8c08743156/mmdet/core/export/onnx_helper.py#L26
But I do not think this is the best way to do that.

**Comment by kevinch-nv** [comment]
This should be fixed with https://github.com/onnx/onnx-tensorrt/pull/721 - closing.
