### ISSUE TITLE
deserialization of the generated trt file

### ISSUE THREAD

**Issue by Eddiesyn** [onnx/onnx-tensorrt#67]
After got the serialized *.trt* file, how can we deserialize it using tensorrt c++ api?

**Comment by yinghai** [comment]
Please check this tutorial on how to deserialize TRT engine in C++: 
https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#serial_model_c

**Comment by FunkyKoki** [comment]
I don't think the doc discribes the process clearly enough. What is the modeldata and modelsize? Should I use class IHostmemroy to save the data and information?
