### ISSUE TITLE
build error---onnx2trt_utils.cpp:330:36: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘data_location’  

### ISSUE THREAD

**Issue by jiawenhao2015** [onnx/onnx-tensorrt#673]
hi~~~when i build onnx-tensort from source code(master branch),i met such errors,
here are my steps:
`cd onnx-tensorrt&&
mkdir build &&
cd build&&
cmake .. -DTENSORRT_ROOT=<path_to_trt> && make -j`

**_onnx2trt_utils.cpp:330:36: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘data_location’_**  

**has anyone met this before???
many many thanks~~~
need help~~~~~~~**

**enviorment**
- tensort  7.2.2.3
- cuda 11.2
- cudnn  8.0.5
- cmake 3.16

**details:**

[ 31%] Built target onnx_proto
Scanning dependencies of target nvonnxparser
Scanning dependencies of target nvonnxparser_static
[ 37%] Building CXX object CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o
[ 37%] Building CXX object CMakeFiles/nvonnxparser.dir/NvOnnxParser.cpp.o
[ 48%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o
[ 48%] Building CXX object CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o
[ 48%] Building CXX object CMakeFiles/nvonnxparser.dir/onnx2trt_utils.cpp.o
[ 58%] Building CXX object CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o
[ 58%] Building CXX object CMakeFiles/nvonnxparser_static.dir/NvOnnxParser.cpp.o
[ 58%] Building CXX object CMakeFiles/nvonnxparser.dir/ModelImporter.cpp.o
[ 62%] Building CXX object CMakeFiles/nvonnxparser.dir/ShapedWeights.cpp.o
[ 72%] Building CXX object CMakeFiles/nvonnxparser.dir/ShapeTensor.cpp.o
[ 72%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapeTensor.cpp.o
[ 72%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapedWeights.cpp.o
[ 75%] Building CXX object CMakeFiles/nvonnxparser.dir/LoopHelpers.cpp.o
[ 79%] Building CXX object CMakeFiles/nvonnxparser_static.dir/LoopHelpers.cpp.o
[ 86%] Building CXX object CMakeFiles/nvonnxparser_static.dir/RNNHelpers.cpp.o
[ 86%] Building CXX object CMakeFiles/nvonnxparser.dir/RNNHelpers.cpp.o
[ 89%] Building CXX object CMakeFiles/nvonnxparser_static.dir/OnnxAttrs.cpp.o
[ 93%] Building CXX object CMakeFiles/nvonnxparser.dir/OnnxAttrs.cpp.o
/home/data/jiawenhao_data/onnx-tensorrt-master/o**nnx2trt_utils.cpp: In function ‘bool onnx2trt::convertOnnxWeights(const onnx2trt_onnx::TensorProto&, onnx2trt::ShapedWeights*, onnx2trt::IImporterContext*)’:
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:330:36: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘data_location’
     auto dataLocation = onnxTensor.data_location();**
                                    ^~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:339:45: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘external_data’; did you mean ‘set_raw_data’?
         for (auto onnxMapEntry : onnxTensor.external_data())
                                             ^~~~~~~~~~~~~
                                             set_raw_data
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp: In function ‘bool onnx2trt::convertOnnxWeights(const onnx2trt_onnx::TensorProto&, onnx2trt::ShapedWeights*, onnx2trt::IImporterContext*)’:
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:330:36: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘data_location’
     auto dataLocation = onnxTensor.data_location();
                                    ^~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:339:45: error: ‘const class onnx2trt_onnx::TensorProto’ has no member named ‘external_data’; did you mean ‘set_raw_data’?
         for (auto onnxMapEntry : onnxTensor.external_data())
                                             ^~~~~~~~~~~~~
                                             set_raw_data
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp: In function ‘std::vector<nvinfer1::PluginField> onnx2trt::{anonymous}::loadFields(string_map<std::vector<unsigned char> >&, const OnnxAttrs&, const nvinfer1::PluginFieldCollection*)’:
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp:4273:52: error: ‘SPARSE_TENSOR’ is not a member of ‘onnx2trt_onnx::AttributeProto’
             case ::ONNX_NAMESPACE::AttributeProto::SPARSE_TENSOR:
                                                    ^~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp:4276:52: error: ‘SPARSE_TENSORS’ is not a member of ‘onnx2trt_onnx::AttributeProto’
             case ::ONNX_NAMESPACE::AttributeProto::SPARSE_TENSORS:
                                                    ^~~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:489:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp: In function ‘std::vector<nvinfer1::PluginField> onnx2trt::{anonymous}::loadFields(string_map<std::vector<unsigned char> >&, const OnnxAttrs&, const nvinfer1::PluginFieldCollection*)’:
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp:4273:52: error: ‘SPARSE_TENSOR’ is not a member of ‘onnx2trt_onnx::AttributeProto’
             case ::ONNX_NAMESPACE::AttributeProto::SPARSE_TENSOR:
                                                    ^~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/builtin_op_importers.cpp:4276:52: error: ‘SPARSE_TENSORS’ is not a member of ‘onnx2trt_onnx::AttributeProto’
             case ::ONNX_NAMESPACE::AttributeProto::SPARSE_TENSORS:
                                                    ^~~~~~~~~~~~~~
/home/data/jiawenhao_data/onnx-tensorrt-master/onnx2trt_utils.cpp:489:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
CMakeFiles/nvonnxparser.dir/build.make:101: recipe for target 'CMakeFiles/nvonnxparser.dir/onnx2trt_utils.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser.dir/onnx2trt_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/nvonnxparser_static.dir/build.make:101: recipe for target 'CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/nvonnxparser_static.dir/build.make:88: recipe for target 'CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o] Error 1
CMakeFiles/nvonnxparser.dir/build.make:88: recipe for target 'CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o] Error 1
CMakeFiles/Makefile2:133: recipe for target 'CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/nvonnxparser_static.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_static.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
![image](https://user-images.githubusercontent.com/14249177/115956264-7716e580-a52e-11eb-843e-6d28f0064c78.png)

**Comment by kevinch-nv** [comment]
Are you building on the master branch? This looks like the ONNX submodule may be out of sync.

**Comment by primer-bi** [comment]
> Are you building on the master branch? This looks like the ONNX submodule may be out of sync.

My tensorrt version is also 7.2.2.3, the latest master branch supports it? If not, I am wondering which branch should I clone.

**Comment by kevinch-nv** [comment]
The main branch points to the latest available TRT version (currently 8.4).

The recommendation is to use the `Major.Minor-GA` branch for your TensorRT version.

To update the submodules when changing branches, you can run the following git command:

`git submodule update --init --recursive -f`
