### ISSUE TITLE
libmyelin has gone in trt 8.

### ISSUE THREAD

**Issue by xkszltl** [onnx/onnx-tensorrt#683]
## Description

trt 8 doesn't have libmyelin.so anymore.
CMake will get NOTFOUND when looking for it.

## Environment

**TensorRT Version**: 8
**ONNX-TensorRT Version / Branch**: master
**CUDA Version**: 11.3
**CUDNN Version**: 8
**Operating System + Version**: Ubuntu 18.04 / CentOS 7

## Relevant Files

https://github.com/onnx/onnx-tensorrt/blob/b235fb54926c80b17c9c6a8093cacc993c335727/CMakeLists.txt#L123-L132
https://github.com/onnx/onnx-tensorrt/blob/b235fb54926c80b17c9c6a8093cacc993c335727/CMakeLists.txt#L44-L46

**Comment by kevinch-nv** [comment]
Thanks @xkszltl for the issue. The master branch is still for TensorRT 7.2 since TensorRT 8.0 is still in EA. I've created a branch https://github.com/onnx/onnx-tensorrt/tree/8.0-EA that you can use to build against TRT 8.0.
