### ISSUE TITLE
build onnx-tensorrt (7.2.1) 

### ISSUE THREAD

**Issue by alicera** [onnx/onnx-tensorrt#686]
## Description
I build the onnx-tensorrt (7.2.1) and show the error

[ 85%] Built target getSupportedAPITest
[ 86%] Building CXX object CMakeFiles/onnx2trt.dir/main.cpp.o
[ 98%] Built target nvonnxparser
/tmp/onnx-tensorrt/main.cpp:26:10: fatal error: onnx/optimizer/optimize.h: No such file or directory
 #include <onnx/optimizer/optimize.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/onnx2trt.dir/build.make:62: recipe for target 'CMakeFiles/onnx2trt.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/onnx2trt.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/onnx2trt.dir/all' failed
make[1]: *** [CMakeFiles/onnx2trt.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

## Environment
NGC pytorch 20.10

**Comment by xxueniao** [comment]
checkout onnx to 1.8.1

**Comment by kevinch-nv** [comment]
We do not support ONNX 1.9 yet, please use an earlier version of ONNX as @xxueniao mentioned.
