### ISSUE TITLE
How to use script to convert fp16 or other modes?

### ISSUE THREAD

**Issue by ChanceQZ** [onnx/onnx-tensorrt#687]
Hi, i'm using this library, but I can't find the way to convert fp16 mode in .py source file.

**Comment by kevinch-nv** [comment]
Hi @ChanceQZ , see https://github.com/onnx/onnx-tensorrt/blob/master/docs/faq.md#how-do-i-import-and-run-an-onnx-model-through-tensorrt. Please use these tools to convert ONNX models into TRT engines. The FP16 flag should just be --fp16 for both of these toosl.
