### ISSUE TITLE
Onnx2trt to int8

### ISSUE THREAD

**Issue by htran170642** [onnx/onnx-tensorrt#692]
I am using the latest onnx-tensorrt repo. How can I convert my yolov5 model to int8 using onnx2trt? Thanks

**Comment by kevinch-nv** [comment]
`onnx2trt` will soon be deprecated. Please see [here](https://github.com/onnx/onnx-tensorrt/blob/master/docs/faq.md#how-do-i-import-and-run-an-onnx-model-through-tensorrt) for updated binaries you can use to convert ONNX models to TRT.

**Comment by Lenan22** [comment]
> I am using the latest onnx-tensorrt repo. How can I convert my yolov5 model to int8 using onnx2trt? Thanks

Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model.
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md

**Comment by Lenan22** [comment]
> I am using the latest onnx-tensorrt repo. How can I convert my yolov5 model to int8 using onnx2trt? Thanks

Please refer to our open source quantization tool ppq, we can help you solve quantization problems
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md
