### ISSUE TITLE
Which set of upsample modes are supported?

### ISSUE THREAD

**Issue by trathpai** [onnx/onnx-tensorrt#694]
## Description

I didn't find a clear documentation of upsample modes supported in Tensorrt 7.1.3.0 . Is bilinear, bicubic upsampling supported ? Onnx 1.6.0 seems to support both.

**Comment by kevinch-nv** [comment]
I assume you mean the `resize` operator, since upsample has been deprecated in ONNX since opset 10. You can see the notes about op support [here](https://github.com/onnx/onnx-tensorrt/blob/master/docs/operators.md) - we do support bilinear resizes but not bicubic.

**Comment by CarlosRDomin** [comment]
Are there any plans to support bicubic upsampling? If so, is there an ETA?
Alternatively, other Nvidia libraries like NPP already support it, are there any guides on how we could try to implement it as a custom TensorRT layer?  
Thanks!
