### ISSUE TITLE
unit test cannot pass inside docker

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx-tensorrt#7]
root@trt:/workspace# python onnx_backend_test.py
s.sEs.sssssssssssssss.s.s.s.s.s.sterminate called after throwing an instance of 'std::invalid_argument'
  what():  Unsupported form of asymmetric padding for AveragePool op
Aborted (core dumped)

**Comment by benbarsdell** [comment]
Just pushed https://github.com/onnx/onnx-tensorrt/commit/0ca16f96b599031875010e61182db7a93001d131; does it fix this problem for you?

**Comment by qigtang** [comment]
That one is fixed, new one show up

root@66aa1da6492f:/workspace# python onnx_backend_test.py
s.sEs.sssssssssssssss.s.s.s.s.s.sEs.s.sEsEsEsssssssssssss.s.s.s.s.s.s[TensorRT] ERROR: Parameter check failed at: InferPlugin.cpp::createConcatPlugin::79, condition: concatAxis == 1 || concatAxis == 2 || concatAxis == 3
Segmentation fault (core dumped)
root@66aa1da6492f:/workspace#

**Comment by kevinch-nv** [comment]
@qigtang closing this as we have a new docker container for the latest version of TensorRT. If you have issues with the newest version, feel free to open another issue.
