### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by HilmiK** [onnx/onnx-tensorrt#71]
Hi,

After converting onnx into trt model, is there any way to extract weights from layers ? I searched a lot but I could not find anything including documentation of tensorrt.

Thanks.

**Comment by benbarsdell** [comment]
If you're using the parser API (as opposed to the onnx2trt executable) then after parsing you can potentially access layers and weights in the INetworkDefinition through APIs such as https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_convolution_layer.html#a949cc67481826a27ac15eee2747cbcca

However, once the TensorRT engine is compiled, there is no supported way to extract the weights.
