### ISSUE TITLE
How to load tensorrt engine directly with building on runtime

### ISSUE THREAD

**Issue by Yadav03** [onnx/onnx-tensorrt#717]
Hi,

I am using the onnx_tensorrt library to convert onnx model to tensorrt model on runtime. But since it is building the tensorrt engine on runtime it takes more than 4minutes to complete. So i want to use direct tensorrt engine file directly without building on runtime. For this, i have converted onnx model to tensorrt engine .plan file offline. but i dont know how to use it directly in my code. Please help me with it.

import onnx
import onnx_tensorrt.backend as backend
import numpy as np

model = onnx.load("/path/to/model.onnx")
engine = backend.prepare(model, device=‘CUDA:1’)
input_data = np.random.random(size=(32, 3, 224, 224)).astype(np.float32)
output_data = engine.run(input_data)[0]
print(output_data)
print(output_data.shape)

currently i am using above code. Now i have .plan file with me ready. please let me know that how to inference .plan file directly.thanks

**Comment by kevinch-nv** [comment]
TensorRT's Runtime class has the ability to deserialize pre-built engines from disk. 

See the following code snippet (taken from [here](https://github.com/NVIDIA/TensorRT/blob/master/samples/python/yolov3_onnx/onnx_to_tensorrt.py#L92-L98):

```
    if os.path.exists(engine_file_path):
        # If a serialized engine exists, use it instead of building an engine.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
```
