### ISSUE TITLE
make -j8 error

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [onnx/onnx-tensorrt#72]
/home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:1724:82: error: invalid new-expression of abstract class type ‘FancyActivationPlugin’
          new FancyActivationPlugin(FancyActivationPlugin::THRESHOLDED_RELU, alpha),
                                                                                  ^
/home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:415:33: note: in definition of macro ‘RETURN_FIRST_OUTPUT’
   nvinfer1::ILayer* layer_ptr = layer; \
                                 ^
/home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importUpsample(onnx2trt::IImporterContext*, const onnx2trt_onnx::NodeProto&, std
::vector<onnx2trt::TensorOrWeights>&)’:
/home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:1836:67: error: invalid new-expression of abstract class type ‘ResizeNearestPlugin’
   RETURN_FIRST_OUTPUT(ctx->addPlugin(new ResizeNearestPlugin(scale),
                                                                   ^
/home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:415:33: note: in definition of macro ‘RETURN_FIRST_OUTPUT’
   nvinfer1::ILayer* layer_ptr = layer; \
                                 ^
In file included from /home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:27:0:
/home/test1050/tools/onnx-tensorrt/ResizeNearest.hpp:30:7: note:   because the following virtual functions are pure within ‘ResizeNearestPlugin’:
 class ResizeNearestPlugin final : public onnx2trt::Plugin {
       ^
In file included from /home/test1050/tools/onnx-tensorrt/NvOnnxParser.h:26:0,
                 from /home/test1050/tools/onnx-tensorrt/onnx2trt.hpp:25,
                 from /home/test1050/tools/onnx-tensorrt/builtin_op_importers.hpp:25,
                 from /home/test1050/tools/onnx-tensorrt/builtin_op_importers.cpp:23:
/home/test1050/tools/TensorRT-5.0.0.10/include/NvInfer.h:2666:25: note:         virtual const char* nvinfer1::IPluginExt::getPluginVersion() const
     virtual const char* getPluginVersion() const = 0;
                         ^
/home/test1050/tools/TensorRT-5.0.0.10/include/NvInfer.h:2676:25: note:         virtual nvinfer1::IPluginExt* nvinfer1::IPluginExt::clone() const
     virtual IPluginExt* clone() const = 0;
                         ^
CMakeFiles/nvonnxparser.dir/build.make:110: recipe for target 'CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o] Error 1
CMakeFiles/nvonnxparser_static.dir/build.make:86: recipe for target 'CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o] Error 1
CMakeFiles/nvonnxparser.dir/build.make:86: recipe for target 'CMakeFiles/nvonnxparser.dir/ModelImporter.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser.dir/ModelImporter.cpp.o] Error 1
CMakeFiles/nvonnxparser_static.dir/build.make:110: recipe for target 'CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/nvonnxparser_static.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_static.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

too many error,just show a few here
cmake version :3.5.1
cuda:9.0
nvcc:Built on Fri_Sep__1_21:08:03_CDT_2017
        Cuda compilation tools, release 9.0, V9.0.176
gcc version:5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by benbarsdell** [comment]
You'll need to update to the TensorRT 5 GA, available here: https://developer.nvidia.com/nvidia-tensorrt-download

**Comment by MoonBunnyZZZ** [comment]
> You'll need to update to the TensorRT 5 GA, available here: https://developer.nvidia.com/nvidia-tensorrt-download

What's the difference between TensorRT 5 GA and TensorRT 5.0.0.10 which is I am using?

**Comment by benbarsdell** [comment]
5.0.0.10 was the release candidate (RC) version, which is now superseded by the general availability (GA) release. Among other things, the GA release fixes backward compatibility with TensorRT 4, which resolves the problem you're observing.

**Comment by MoonBunnyZZZ** [comment]
> 5.0.0.10 was the release candidate (RC) version, which is now superseded by the general availability (GA) release. Among other things, the GA release fixes backward compatibility with TensorRT 4, which resolves the problem you're observing.

Thank you very much.The build process is ok,but :
collect2: error: ld returned 1 exit status
CMakeFiles/onnx2trt.dir/build.make:105: recipe for target 'onnx2trt' failed
make[2]: *** [onnx2trt] Error 1
CMakeFiles/Makefile2:295: recipe for target 'CMakeFiles/onnx2trt.dir/all' failed
make[1]: *** [CMakeFiles/onnx2trt.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by benbarsdell** [comment]
Could you post the complete build log. It looks like a linker error, but I don't see the details.

**Comment by MoonBunnyZZZ** [comment]
> Could you post the complete build log. It looks like a linker error, but I don't see the details.

Sorry.I reinstall OS on my computer...

**Comment by benbarsdell** [comment]
Closing this out. Feel free to re-open if you see the issue again.
