### ISSUE TITLE
Failed to build **onnx2trt** from source 

### ISSUE THREAD

**Issue by jiapei100** [onnx/onnx-tensorrt#724]
## Description

Failed to build **onnx2trt** with the following **ERROR** messages:

```console
[ 98%] Linking CXX executable onnx2trt
/usr/bin/cmake -E cmake_link_script CMakeFiles/onnx2trt.dir/link.txt --verbose=1
/usr/local/bin/c++ -L/usr/local/lib -Wall -Wno-deprecated-declarations -Wno-unused-function -O3 -DNDEBUG CMakeFiles/onnx2trt.dir/main.cpp.o -o onnx2trt  -Wl,-rpath,/usr/local/cuda/lib64: third_party/onnx/libonnx.a /usr/local/lib/libonnx_optimizer.a libnvonnxparser_static.a -lpthread -ldl third_party/onnx/libonnx_proto.a /usr/local/lib/libprotobuf.so -lpthread /usr/local/lib/libprotobuf.so /usr/local/cuda/lib64/libnvinfer.so /usr/local/cuda/lib64/libnvinfer_plugin.so 
/usr/bin/ld: CMakeFiles/onnx2trt.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0xa5e): undefined reference to `onnx2trt_onnx::optimization::GetAvailablePasses[abi:cxx11]()'
/usr/bin/ld: main.cpp:(.text.startup+0xc79): undefined reference to `onnx2trt_onnx::optimization::OptimizeFixed(onnx2trt_onnx::ModelProto const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x1b4b): undefined reference to `onnx2trt_onnx::optimization::Optimize(onnx2trt_onnx::ModelProto const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnx2trt.dir/build.make:108: onnx2trt] Error 1
make[2]: Leaving directory '....../onnx/onnx-tensorrt/build'
make[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/onnx2trt.dir/all] Error 2
make[1]: Leaving directory '....../onnx/onnx-tensorrt/build'
```

## Environment

**TensorRT Version**: 9.0.1
**ONNX-TensorRT Version / Branch**:
**GPU Type**: Geforce RTX 2080 Ti
**Nvidia Driver Version**: NVIDIA-SMI 460.84
**CUDA Version**: 11.3
**CUDNN Version**: 8.2.1
**Operating System + Version**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8.10
**TensorFlow + TF2ONNX Version (if applicable)**: 2.7.0 + 1.9.1
**PyTorch Version (if applicable)**: 1.10.0
**Baremetal or Container (if container which image + tag)**: N/A

## Relevant Files

Just a single file: [main.cpp](https://github.com/onnx/onnx-tensorrt/blob/master/main.cpp)

## Steps To Reproduce

cmake build **onnx-tensorrt** from source .

**Comment by kevinch-nv** [comment]
onnx2trt is marked to be deprecated soon, as it lacks a lot of features (such as dynamic shapes). 

You can use `trtexec` (see instructions [here](https://github.com/onnx/onnx-tensorrt/blob/master/docs/faq.md#how-do-i-import-and-run-an-onnx-model-through-tensorrt)) to do the onnx to TensorRT conversion.

**Comment by kevinch-nv** [comment]
We will be removing onnx2trt in a future release, marking this as WNF.
