### ISSUE TITLE
[network.cpp::validate::2684]Error Code 4: Internal Error (Network has dynamic or shape inputs, but no optimization profile has been defined.)

### ISSUE THREAD

**Issue by umairjavaid** [onnx/onnx-tensorrt#725]
## Description
I am trying to convert a pythorch yolov5 model with custom weights to tensorrt. I first convert it to ONNX I have run the TensorRT docker image. In in, I have cloned this repo and followed all the  build steps.
I am using `./onnx2trt /workspace/onnxmodels/ball_player_best.onnx -o /workspace/onnxmodels/ball_player_best.trt` to convert my ONNX model but I am getting the following error.

```
Input filename:   /workspace/onnxmodels/ball_player_best.onnx
ONNX IR version:  0.0.6
Opset version:    12
Producer name:    pytorch
Producer version: 1.9
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2021-07-31 17:30:19 WARNING] /workspace/onnx-tensorrt/onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2021-07-31 17:30:19 WARNING] /workspace/onnx-tensorrt/onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
Building TensorRT engine, FP16 available:1
    Max batch size:     32
    Max workspace size: 1024 MiB
[2021-07-31 17:30:20   ERROR] 4: [network.cpp::validate::2684] Error Code 4: Internal Error (Network has dynamic or shape inputs, but no optimization profile has been defined.)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)

```
How do I fix it? If I have to edit any code, kindly let me know which lines to add?

## Environment

**TensorRT 8**: 
**ONNX-TensorRT Version / Branch**:
**GPU gtx1660**:

**Comment by umairjavaid** [comment]
If I have to edit any code that just defeats the purpose of having a single line command to convert onnx model to tensorrt

**Comment by umairjavaid** [comment]
Kindly, let me know which lines do I have to edit or add in which file to get it working?

**Comment by maarten0912** [comment]
Did you find out how to add an optimization profile?

**Comment by DrRyanHuang** [comment]
Did you find out how to add an optimization profile?

**Comment by kevinch-nv** [comment]
`onnx2trt` currently does not have the capability to add optimization profiles. I recommend using a different tool such as trtexec or polygraphy, [instructions are outlined here](https://github.com/onnx/onnx-tensorrt/blob/main/docs/faq.md#how-do-i-import-and-run-an-onnx-model-through-tensorrt). `onnx2trt` will be removed in a future release.
