### ISSUE TITLE
Any thoughts on when boolean operator such as greater or equal will be supported?

### ISSUE THREAD

**Issue by ChengshuLi** [onnx/onnx-tensorrt#74]
Any thoughts on when boolean operator such as greater or equal will be supported?

This is actually the road blocker for me to transform one of my models to TensorRT.

**Comment by jinfagang** [comment]
@ChengshuLi As far as I know, the current onnx-tensorrt does not support Equal and Greater.

Equal is really essential for us simplifying some model process otherwise it can only be done outside of model structure.

**Comment by kevinch-nv** [comment]
We've added boolean operator support in TRT versions >= 7.0, along with support for those operators. Please upgrade to a higher version to run models with those operators.
