### ISSUE TITLE
Some questions when reading the source code

### ISSUE THREAD

**Issue by OYCN** [onnx/onnx-tensorrt#745]
Hi,
After reading the source code, I got some questions.
   
1. Why is some OP starting with `TRT_`?
2. When will the `producer_name` of the model become "TensorRT"?

Anyone help me.

**Comment by kevinch-nv** [comment]
See my answer in https://github.com/onnx/onnx-tensorrt/issues/744 - we are working on some internal tools that allows representing TRT graphs in ONNX format. This is the time where the producer of the graph will be `TensorRT` and we'll use some `TRT_` importer ops.
