### ISSUE TITLE
 libnvinfer.so.5 file could not be found

### ISSUE THREAD

**Issue by coallar** [onnx/onnx-tensorrt#775]
## Description
run: onnx2trt yolov5s6.onnx -o my_engine.trt
error: 
onnx2trt: error while loading shared libraries: libnvinfer.so.5: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/66529823/143048853-7e3061b3-151a-4b75-8744-76f9b9ac5f1b.png)

## Environment

**TensorRT Version**:  5.1.5.0
**ONNX-TensorRT Version / Branch** :https://github.com/onnx/onnx-tensorrt/tree/5.1
**GPU Type**: V100
**Nvidia Driver Version**: 
**CUDA Version**: 10.1
**CUDNN Version**: 7.5
**Operating System + Version**: ubuntu18.04
**Python Version (if applicable)**: 3.6

**PyTorch Version (if applicable)**: 1.10

**Comment by coallar** [comment]
third_party onnx: ttps://github.com/onnx/onnx/tree/765f5ee823a67a866f4bd28a9860e81f3c811ce8

**Comment by galagam** [comment]
Most likely cause for this is not having the installed TensorRT 5 libs in your library search path. 
You might like to try `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_tensorrtlibs>` where path_to_tensorrtlibs is the directory that contains `libinferinfo.so.5`. 
Regardless, it is highly recommended that you upgrade to newer versions of TensorRT, CUDA and CuDNN.
