### ISSUE TITLE
Build failure on master

### ISSUE THREAD

**Issue by truncs** [onnx/onnx-tensorrt#781]
## Description

  

Both TensorRT and onnx-tensorrt are current. Exact commits below

```
/mnt/onnx-tensorrt/onnx2trt_utils.hpp:376:11: error: ‘IScatterLayer’ in namespace ‘nvinfer1’ does not name a type
 nvinfer1::IScatterLayer* addScatterLayer(
           ^~~~~~~~~~~~~
/mnt/onnx-tensorrt/ModelImporter.cpp: In function ‘onnx2trt::Status onnx2trt::assertDimsWithSameNameAreEqual(onnx2trt::ImporterContext*, std::vector<{anonymous}::NamedDimension>&)’:
/mnt/onnx-tensorrt/ModelImporter.cpp:309:51: error: ‘class nvinfer1::INetworkDefinition’ has no member named ‘addAssertion’; did you mean ‘addActivation’?
                 auto* assertion = ctx->network()->addAssertion(*equal->getOutput(0), message.str().c_str());
                                                   ^~~~~~~~~~~~
                                                   addActivation
```

## Environment

**TensorRT Version**: 6f38570b74066ef464744bc789f8512191f1cbc0
**ONNX-TensorRT Version / Branch**: b5b9be23c9f01368843720f51dd7c33eaac35634
**GPU Type**:  Tegra
**Nvidia Driver Version**: N/A
**CUDA Version**: 10.2
**CUDNN Version**: 8
**Operating System + Version**: Ubuntu 18.04.6 LTS
**Python Version (if applicable)**: 3.6
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Steps To Reproduce

```
cmake .. -DTENSORRT_ROOT=/mnt/TensorRT/build/out
```

**Comment by galagam** [comment]
Please attempt reproducing with a released version - see [tags](https://github.com/onnx/onnx-tensorrt/tags).
