### ISSUE TITLE
Assertion failed (onnx_padding[0] == 0 && onnx_padding[1] == 0 && onnx_padding[4] == 0 && onnx_padding[5] == 0) on Resnet50 onnx model output from tensorflow-onnx tool

### ISSUE THREAD

**Issue by stonexjr** [onnx/onnx-tensorrt#79]
@benbarsdell @yinghai For more detail see the issue originally posted in the tensorflow-onnx repo. Can you guys help look into this? I guess something is not quite right either in onnx-tensorrt parser or tensorflow-onnx conversion tool.

**Comment by benbarsdell** [comment]
TensorRT does not support padding along any dimensions other than 2 and 3 (i.e., HW in NCHW format). This means the fix will have to be on the tensorflow-onnx side (either moving the transpose before the padding layer or fusing the padding and convolution layers, as discussed in https://github.com/onnx/tensorflow-onnx/issues/201).

**Comment by kevinch-nv** [comment]
TensorRT versions > 8.2 supports  ND padding now. Closing this issue.
