### ISSUE TITLE
Clarification of Resize Op checks for align_corners

### ISSUE THREAD

**Issue by mstallmo** [onnx/onnx-tensorrt#793]
We have been using TRT 7.2.1 for our model  inference and the onnx parser was parsing our models fine until a change introduced with PR #538 that modifies the checks around the Resize Op in linear mode with align_corners. 

I was wondering what are the requirements that these assertion changes are based off of? At this point I'm not sure if this a bug with the logic of the assertions here or if the previous logic was incorrect. Some clarification around the assertion logic would be much appreciated! 

Not sure if this is most appropriate place for this question, please feel free to redirect to a different location if this is not the correct place.

**Comment by kevinch-nv** [comment]
There was a bug in previous versions of TRT 7.2.1 where certain resize modes were providing incorrect results. 

I would recommend updating to TRT 8.2 where this has been fixed.
