### ISSUE TITLE
Not able to suppress "TensorRT was linked against x but loaded x" warning

### ISSUE THREAD

**Issue by styler00dollar** [onnx/onnx-tensorrt#798]
## Description

I want to use onnx-tensorrt inside vapoursynth, which does pipe all printed data into ffmpeg. 
```
vspipe -c y4m inference.py - | ffmpeg -i pipe: example.mkv
```
My code works if the enviroment is correctly set up, but I am seemingly not able to do it in Colab. My code works in the official NVidia TensorRT docker, but in Colab, I get:
```
[01/29/2022-06:26:36] [TRT] [W] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.3.0
[01/29/2022-06:26:36] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.0.5
```
The code (just using TensorRT on it's own) still seems to run, but this is not desirable. This results in ffmpeg not being able to correclty decode the piped data, since I assume ffmpeg also gets this warning piped as data. The result is 
```
[lrc @ 0x55c14252c000] Format lrc detected only with low score of 5, misdetection possible!
``` 
and no output video. Is it possible to completely disable this warning? I am not able to process piped data otherwise. I tried to block printing in various ways, without success.

## Environment

Tensorrt: 8.2.3-1+cuda11.4
onnx: 1.10.2
onnx-tensorrt: 8.2.1
onnxruntime: 1.10.0
onnxruntime-gpu: 1.10.0

**Comment by styler00dollar** [comment]
I confirmed that my code does not work because the warnings are getting piped as well as the data.

![unknown](https://user-images.githubusercontent.com/51405565/151922640-f584b725-8f9b-43bf-9a2b-46e8f469c796.png)

I tried recompiling and reinstalling stuff, but I always have some sort of warning message in Google Colab. I thought of disabling this warning when i compile TensorRT, but it seems like that part is closed source.
```
grep -Ril "TensorRT was linked against" .
./lib/libnvinfer.so
./lib/libnvinfer.so.8
./lib/libnvinfer.so.8.2.3
./lib/libnvinfer_static.a
./targets/x86_64-linux-gnu/lib/libnvinfer.so
./targets/x86_64-linux-gnu/lib/libnvinfer.so.8
./targets/x86_64-linux-gnu/lib/libnvinfer.so.8.2.3
./targets/x86_64-linux-gnu/lib/libnvinfer_static.a
```
Is there any way to disable this warning?

**Comment by styler00dollar** [comment]
The only solution I can come up with is using regex to supress the text, which does at least seem to work.
```
sd '^\[[0-9]{2}.*$\n' ''
```
```
vspipe -c y4m inference.py - | sd '^\[[0-9]{2}.*$\n' '' | ffmpeg -i pipe: test.mkv
```

**Comment by styler00dollar** [comment]
Managed to get it kind of working with a complex sed command.
```
sed -u '/\[[0-9].*\/[0-9].*\/[0-9]*-[0-9]*:[0-9]*:[0-9]*] \[TRT\]/d'
```
```
vspipe -c y4m inference.py - 2> /dev/null | sed -u '/\[[0-9].*\/[0-9].*\/[0-9]*-[0-9]*:[0-9]*:[0-9]*] \[TRT\]/d' | ffmpeg -i pipe: /example.mkv
```
Would be nice if I would not need such workarounds.

**Comment by styler00dollar** [comment]
After a week of trying to figure this out on my own, I think i finally found a working solution with the help of [stackoverflow](https://stackoverflow.com/questions/5081657/how-do-i-prevent-a-c-shared-library-to-print-on-stdout-in-python).
```python
import os
import sys
from contextlib import contextmanager

@contextmanager
def stdout_redirected(to=os.devnull):
    fd = sys.stdout.fileno()
    def _redirect_stdout(to):
        sys.stdout.close() # + implicit flush()
        os.dup2(to.fileno(), fd) # fd writes to 'to' file
        sys.stdout = os.fdopen(fd, 'w') # Python writes to fd

    with os.fdopen(os.dup(fd), 'w') as old_stdout:
        with open(to, 'w') as file:
            _redirect_stdout(to=file)
        try:
            yield # allow code to be run with the redirected stdout
        finally:
            _redirect_stdout(to=old_stdout) # restore stdout.
                                            # buffering and flags such as
                                            # CLOEXEC may be different

with stdout_redirected(to=os.devnull):
    # load model
    model = onnx.load("test.onnx")
    model = backend.prepare(model, device='CUDA:0', fp16_mode=True)
```
```
vspipe -c y4m inference.py - 3>/dev/null  2>/dev/null | ffmpeg -i pipe: example.mkv
```
No ram leaks, no warnings, it just works. Not using such a workaround would be nice though.

**Comment by kevinch-nv** [comment]
If you are using the onnx_tensorrt backend in your application, you can try to modify the default logging verbosity.

i.e. modify https://github.com/onnx/onnx-tensorrt/blob/master/onnx_tensorrt/backend.py#L31 to `trt.Logger.INTERNAL_ERROR`. 

This should suppress the warning messages from being printed out

**Comment by kevinch-nv** [comment]
Closing this issue, since it looks like this has been resolved.

**Comment by ke-dev** [comment]
Hi @styler00dollar , I meet the same problem and I couldn't get the inference result, could you please tell me how did you solve it?
`[TensorRT] WARNING: TensorRT was linked against cuDNN 8.0.4 but loaded cuDNN 7.6.3
Segmentation fault (core dumped)
`
much appreciation
