### ISSUE TITLE
Enhancement and Question

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx-tensorrt#8]
For best performance on production, we normally will convert the onnx file to tensorrt engine. 
Question:
1. After onnx2trt onnxfile -o foo.trt.   Do I need the onnx-tensorrt anymore even if there are some plugins provided from onnx-tensorrt? Or the only dependency is cuda library? 

2. a c++ example to run converted engine file would be greatly appreciated. 
Thanks!

**Comment by benbarsdell** [comment]
1. If any of onnx2trt's builtin plugins are used, you will need to link your runtime executable to libnvonnxparser_runtime.so and use the provided plugin factory via the API here: https://github.com/onnx/onnx-tensorrt/blob/master/NvOnnxParserRuntime.h#L63-L75

2. We will look into adding an example of this. Thanks for the suggestion!

**Comment by qigtang** [comment]
Thanks!

**Comment by yinghai** [comment]
C++ example for running converted TensorRT engine already exists in TensortRT distribution under `samples`.

**Comment by bettyeats** [comment]
 I used onnx2trt to convert onnx model file into trt format. But when used trtexec which is in tensorRT samples, get some errors. I compared mnist engine file, 34KB generated by onnx2trt while 1.7MB offered by TensorRT samples(which is in path: TensorRT/data/mnist/mnist.engine). If I converted in a wrong way?
code as follow:
$ ./onnx2trt /TensorRT-4.0.1.6/data/mnist/mnist.onnx -o mnist.engine
----------------------------------------------------------------
Input filename:   /TensorRT-4.0.1.6/data/mnist/mnist.onnx
ONNX IR version:  0.0.3
Opset version:    1
Producer name:    CNTK
Producer version: 2.4
Domain:           
Model version:    1
Doc string:       
----------------------------------------------------------------
Parsing model
Building TensorRT engine, FP16 available:0
    Max batch size:     32
    Max workspace size: 1024 MiB
Writing TensorRT engine to mnist.engine
All done

**Comment by myih** [comment]
@bettyeats Hi did you find a solution?
I have the same problem, the converted engine file is about 32KB though the mnist.onnx is about the same, while the mnist.onnx file works with trtexec, the mnist.engine doesn't
```
trtexec: trtexec.cpp:357: void createMemory(const nvinfer1::ICudaEngine&, std::vector<void*>&, const string&): Assertion `bindingIndex < buffers.size()' failed.
Aborted (core dumped)
```

One the other hand mnist.engine provided by TensorRT-4.0.1.6 doesn't work either (Segmentation fault)

**Comment by kevinch-nv** [comment]
Hi all, please use trtexec for parsing ONNX files with TensorRT going forward. onnx2trt is no longer officially supported and will be deprecated in a later release.
