### ISSUE TITLE
Unclear TensorRT version match

### ISSUE THREAD

**Issue by Michelvl92** [onnx/onnx-tensorrt#804]
## Description

It is unclear to me which version of TensorRT my environment should contain. I want to export my models to TensorRT for https://github.com/triton-inference-server/server .

I use that environment as and TensorRT environment. But the versions do not match with the released onnx-tensorrt TensorRT version requirements, since I always get compilation problems of the tool. E.g. for the 8.0 release the requirements are [TensorRT 8.0.1.6](https://developer.nvidia.com/nvidia-tensorrt-download). Does this mean that my environment should contain TensorRT==8.0.1.6, or TensorRT>=8.0.1.6?

**Comment by kevinch-nv** [comment]
TensorRT requirements are based on `Major.Minor` versions, so for TRT 8.0 compatibility is any `8.0.x.x` version you have.
