### ISSUE TITLE
how to load a plugin variable from onnx model file after the createPluginFactory removed from tensorrt8.2 ?

### ISSUE THREAD

**Issue by sainttelant** [onnx/onnx-tensorrt#815]
as the title showed ,  i am very confused that we couldn't use "createPluginFactory " function after tensorrt version updated above 5 or 6,  for example, the following code couldn' t be compiled successfully. 

mPlugins = nvonnxparser::createPluginFactory(gLogger);
std::cout << "deserializing" << std::endl;
mRunTime = nvinfer1::createInferRuntime(gLogger);
assert(mRunTime != nullptr);
mEngine= mRunTime->deserializeCudaEngine(data.get(), length, mPlugins);

that means we couldn' t get plugins through the createPluginFactory, so how to substitute this function in later version of tensorrt onnx

**Comment by sainttelant** [comment]
BTW,   i  checked the reference of tensorrt on nvidia website, it gives a example of creating custom plugin named customclipplugin,   basically, there are several steps to createplugins, such as defining construct functions of "myplugin", register plugin, and deserializing networks etcs. 

https://github.com/NVIDIA/TensorRT/tree/release/8.2/samples/python/uff_custom_plugin

i am wondering that is there any simple way to define and assigning values to defined variables of  custom plugin?  just like "createPluginFactory " in later tensorrt and tensorrt onnx.

i have trained the model from pytorch, and trasferred the trained model from pt to onnx files  already,,  so i really want a simple way to parser plugin layers to "mPlugins" variable in cpp,,   if  you got any suggestions, please help me! thanks you in advance

**Comment by sainttelant** [comment]
any samples or examples represent in this questions,  i will be so appreciated, this question has bothered me for a really long time!!!

**Comment by kevinch-nv** [comment]
You can refer to this document for working with plugins:  [link](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending)

In later TensorRT versions, `pluginFactory` has been deprecated for `pluginRegistry`.  As long as your plugin is registered in the registry, TRT will be able to read your plugin successfully upon deserialization.  In this new flow, you don't need to explicitly create a pluginFactory and pass it in as a parameter for the `deserializeCudaEngine` call.

**Comment by sainttelant** [comment]
@kevinch-nv ,thanks you very much ,i  will check the details and try to deploy it on my program

**Comment by kevinch-nv** [comment]
@sainttelant please close this issue if you are able to deserialize your plugin now
