### ISSUE TITLE
Export of Large Models Fails: onnx2trt_utils.cpp:1571: Failed to open file

### ISSUE THREAD

**Issue by oborchers** [onnx/onnx-tensorrt#818]
## Description

I'm currently trying to export a large model to TRT using [this](https://github.com/ELS-RD/transformer-deploy) repository.
There are some minor modifications in my implementation, but this is also reproducible with the standard examples.
I assume the `ICudaEngine` does have some problems when models are making use of the ONNX external data format, which leads to the following error:

```
/usr/local/lib/python3.8/dist-packages/transformers/models/gpt2/modeling_gpt2.py:196: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attn_weights = attn_weights / (float(value.size(-1)) ** 0.5)
[03/14/2022-09:03:29] [TRT] [E] onnx2trt_utils.cpp:1571: Failed to open file: transformer.wte.weight
[03/14/2022-09:03:29] [TRT] [E] 4: [network.cpp::validate::2633] Error Code 4: Internal Error (Network must have at least one output)
[03/14/2022-09:03:29] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
Traceback (most recent call last):
  File "/usr/local/bin/convert_model", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 357, in entrypoint
    main(commands=args)
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 262, in main
    engine: ICudaEngine = build_engine(
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/backends/trt_utils.py", line 126, in build_engine
    engine: ICudaEngine = runtime.deserialize_cuda_engine(trt_engine)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7fe431b73a30>, None
```

## Environment

**TensorRT Version**: 8.2.2-1
**ONNX-TensorRT Version / Branch**: 8.2.2.1
**GPU Type**: V100
**Nvidia Driver Version**: 495.29.05
**CUDA Version**: 11.5
**CUDNN Version**: 
**Operating System + Version**: Ubuntu 20.04.3 LTS
**Python Version (if applicable)**: 3.8.10
**TensorFlow + TF2ONNX Version (if applicable)**:  NA
**PyTorch Version (if applicable)**: 1.10.2+cu113
**Baremetal or Container (if container which image + tag)**:  `ghcr.io/els-rd/transformer-deploy:0.4.0` which is based on `nvcr.io/nvidia/tritonserver:22.01-py3`

## Relevant Files

NA

## Steps To Reproduce

Small (works):
```bash
docker run -it --rm --gpus device=6 \
    --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
    -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
    bash -c "cd /project && \
        convert_model -m distilgpt2 \
        --backend tensorrt \
        --seq-len 1 128 128 \
        --task text-generation"
```

Large (doesnt work):
```bash
docker run -it --rm --gpus device=6 \
    --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
    -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
    bash -c "cd /project && \
        convert_model -m gpt2-large \
        --backend tensorrt \
        --seq-len 1 128 128 \
        --task text-generation"
```

**Comment by kevinch-nv** [comment]
TensorRT is able to handle models that have their weights stored externally in files. There may be an API mis-usage somewhere in the conversion code in that repo. I'll take a look at the conversion process there.

**Comment by oborchers** [comment]
@kevinch-nv thanks! If I need to add additional info for reproduction please let me knowy

**Comment by yuanyao-nv** [comment]
@oborchers When loading external data, the `path` argument should be supplied [here](https://github.com/ELS-RD/transformer-deploy/blob/05d5cab6cb38cd9bee59d4c98af9de9f27f9cfca/src/transformer_deploy/backends/trt_utils.py#L168) (should be '/project/triton_models' in this case). See API doc [here](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/parsers/Onnx/pyOnnx.html#tensorrt.OnnxParser.parse). 
Adding it in the source code in the container seems to solve the problem.

**Comment by oborchers** [comment]
I can confirm that this fixes the issue @yuanyao-nv! Many thanks for helping. I will create a PR on that specific repo.
