### ISSUE TITLE
FP16 as the model input

### ISSUE THREAD

**Issue by c90mkl** [onnx/onnx-tensorrt#831]
Hi,

fp16 mode is on in my trt engine. And I have fp16 data as the onnx input, do I need to explicitly convert fp16 to fp32 before feeding it into engine? Or just directly feeding fp16?

Thanks.

**Comment by kevinch-nv** [comment]
If the ONNX inputs are in FP16, TensorRT will mark the input bindings as FP16 as well. You can feed FP16 inputs directly.
