### ISSUE TITLE
Is GatherElements supported in version v7.2?

### ISSUE THREAD

**Issue by bescks** [onnx/onnx-tensorrt#834]
## Description

The v7.2 onnx operators docs shows that GatherElements is suppored. -> https://github.com/onnx/onnx-tensorrt/blob/7.2.1/docs/operators.md
but the API docs only shows Gather opeartor. -> https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-723/api/c_api/classnvinfer1_1_1_i_gather_layer.html
I am confused by the conflict. Is GatherElements supported in version v7.2 or not?

## Environment

**TensorRT Version**: 
**ONNX-TensorRT Version / Branch**:
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by kevinch-nv** [comment]
Yes it's supported. There is a difference between the ONNX support matrix and the TensorRT layer support matrix. For ONNX operator support, you can refer solely to the operators.md doc.
