### ISSUE TITLE
解析onnx文件，Topk算子出现问题。

### ISSUE THREAD

**Issue by scuizhibin** [onnx/onnx-tensorrt#839]
In the function file builtin_op_importers.cpp, input nvinfer1::ITensor* tensorPtr = &convertToTensor(inputs.at(0), ctx) to convert. The error message I get is Assertion failed: tensorPtr->getType() != nvinfer1::DataType::kINT3

**Comment by kevinch-nv** [comment]
This is a known limitation - see https://github.com/onnx/onnx-tensorrt/issues/450. 

Closing as duplciate.
