### ISSUE TITLE
No rule to make target  -onnx.in.proto  - Split.cu

### ISSUE THREAD

**Issue by PETGreen** [onnx/onnx-tensorrt#84]
ubuntu 16.04, GTX 980M
onnx (1.3.0) installed by pip.
I have installed CUDA 10.0 to avoid 'compute_75' error, and it worked.
but meet some error after  Generating done:

Configuring done
-- Generating done
-- Build files have been written to: /home/various/onnx-tensorrt/build
make[2]: *** No rule to make target '../Split.cu', needed by 'CMakeFiles/nvonnxparser_plugin.dir/nvonnxparser_plugin_generated_Split.cu.o'。 停止。
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
make[2]: *** No rule to make target '../third_party/onnx/onnx/onnx.in.proto', needed by 'third_party/onnx/onnx/onnx_onnx2trt_onnx.proto'。 停止。
CMakeFiles/Makefile2:424: recipe for target 'third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all' failed
make[1]: *** [third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

what's wrong here ? tks

**Comment by yinghai** [comment]
Have you installed protobuf? 
```
protoc --version
```

**Comment by PETGreen** [comment]
> Have you installed protobuf?
> 
> ```
> protoc --version
> ```
Yes
protoc --version
libprotoc 3.6.1

Can you compile onnx-tensorrt with CUDA 9.0? I met  "not support compute_75" error. 
你能用CUDA9.0编译最新版的onnx-tensorrt吗？我编译一直遇到 "不支持compute_75"错误。

**Comment by goldgeisser** [comment]
@PETGreen If your issues has not been resolved yet, could you please compile it with 
make VERBOSE=1
Also, please capture the output of invoking cmake (and all command arguments when you invoke it).

**Comment by Morgan-117** [comment]
do you mean the error: nvcc fatal : Unsupported gpu architecture 'compute_75'
in ubuntu 16.04 cuda 9.0 with libprotoc 3.6.1?

**Comment by sanpreet** [comment]
@PETGreen
I also got the similar type of error like you got

`tensorrt-object-detection/Tensorflow-TensorRT/yolov3_medium/onnx-tensorrt/build/CMakeFiles/nvonnxparser_plugin.dir/depend.make.tmp
CMake Error: : System Error: Permission denied
CMake Error: Cannot open file for write: /home/gpu/Desktop/Date/Month_Wise_Data/5_months/2019_months/June_2019/Installing_TensorRT/tensorrt-object-detection/Tensorflow-TensorRT/yolov3_medium/onnx-tensorrt/build/third_party/onnx/CMakeFiles/gen_onnx_proto.dir/depend.make.tmp
CMake Error: : System Error: Permission denied
CMakeFiles/nvonnxparser_plugin.dir/build.make:157: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/depend' failed
make[2]: *** [CMakeFiles/nvonnxparser_plugin.dir/depend] Error 2
third_party/onnx/CMakeFiles/gen_onnx_proto.dir/build.make:89: recipe for target 'third_party/onnx/CMakeFiles/gen_onnx_proto.dir/depend' failed
make[2]: *** [third_party/onnx/CMakeFiles/gen_onnx_proto.dir/depend] Error 2
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/nvonnxparser_plugin.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:560: recipe for target 'third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all' failed
make[1]: *** [third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

I tried many solution but none of the solutions works.  In the end, I have upgraded tensorrt to the version **5.1.5.0-1+cuda10.0  GA version**. I have followed the following link to download the latest version of tensorrt 
https://developer.nvidia.com/tensorrt

Please see the below screenshot to see the new version of tensorrt. Please run the below command to see this output
`dpkg -l | grep TensorRT`

![image_installling_tensorrt](https://user-images.githubusercontent.com/3431730/60709633-88909700-9f2e-11e9-98a4-94693f230820.png)

Now I have tried with building onnx-tensorrt using the command 
make -j8

Build was successful. Please see the below screenshot to see the final output.
![ONXX_build](https://user-images.githubusercontent.com/3431730/60709742-c7bee800-9f2e-11e9-8398-9a87eb0589c0.png)

I hope I was able to help you out. 
With regards
https://ersanpreet.wordpress.com/

**Comment by kevinch-nv** [comment]
For later versions of TensorRT, we've deprecated the use of this plugin and now support the split operator natively. Closing this issue.
