### ISSUE TITLE
onnx-tensorrt/third_party/onnx    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by minho8849** [onnx/onnx-tensorrt#844]
When I did cmake ..
I got this error below
Can anybody help me to solve this problem?
Thanks.

CMake Error at CMakeLists.txt:80 (add_subdirectory):
  The source directory
    /home/civeh/onnx-tensorrt/third_party/onnx
  does not contain a CMakeLists.txt file.

-- Found CUDA headers at /usr/local/cuda/include
-- Found TensorRT headers at TENSORRT_INCLUDE_DIR-NOTFOUND
-- Find TensorRT libs at TENSORRT_LIBRARY_INFER-NOTFOUND;TENSORRT_LIBRARY_INFER_PLUGIN-NOTFOUND
-- Could NOT find TENSORRT (missing: TENSORRT_INCLUDE_DIR TENSORRT_LIBRARY) 
ERRORCannot find TensorRT library.
-- Configuring incomplete, errors occurred!
See also "/home/civeh/onnx-tensorrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/civeh/onnx-tensorrt/build/CMakeFiles/CMakeError.log".

**Comment by konrad966** [comment]
try to clone repo with --recursive option - the third-part/onnx directory includes a submodule

**Comment by kevinch-nv** [comment]
As mentioned by @konrad966, this occurs if the submodule was not cloned. Please run `git submodule update --init --recursive` in the root clone directory and try building again.
