### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by hxyucas** [onnx/onnx-tensorrt#864]
## Environment

**TensorRT Version**: 
**ONNX-TensorRT Version / Branch**:
**GPU Type**: 
**Nvidia Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by jackwish** [comment]
This should be a duplicate with https://github.com/onnx/onnx-tensorrt/issues/865
