### ISSUE TITLE
Fail to load Salesforce Codegen 6B model

### ISSUE THREAD

**Issue by PoodleWang** [onnx/onnx-tensorrt#888]
## Description

I believe it is because that onnx cannot load the model which is large then 2GB.  
For example, https://github.com/onnx/onnx-tensorrt/issues/818 have the similar issues with me

onnx is the latest branch. 

## Environment

**TensorRT Version**: 
8.0.3
**ONNX-TensorRT Version / Branch**:
**GPU Type**: 
A100-80G
**Nvidia Driver Version**: 
**CUDA Version**: 
11.3
**CUDNN Version**: 
**Operating System + Version**: 
**Python Version (if applicable)**: 
**TensorFlow + TF2ONNX Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

    
    I successfully convert the salesforce 6B to onnx file and check it successfully too. 

    trt_logger: Logger = trt.Logger(trt.Logger.ERROR)
    runtime: Runtime = trt.Runtime(trt_logger)
    trt_model_name = "/opt/tiger/genius/checkpoints/codegen-6B-mono-tr/model.plan"
    # create only of does not exist because it's slow to run...
    if not Path(trt_model_name).exists():
        engine: ICudaEngine = build_engine(
            runtime=runtime,
            onnx_file_path="/opt/tiger/genius/checkpoints/codegen-6B-mono-onnx-new/model.onnx",
            logger=trt_logger,
            min_shape=(1, 1),
            optimal_shape=(1, 128),
            max_shape=(1, 384),
            workspace_size=10000 * 1024 ** 2,
            fp16=True,
            int8=False,
        )
        save_engine(engine, trt_model_name)

**Comment by zhenhuaw-me** [comment]
Hi @PoodleWang , do you have any log about the failure? Could you try the latest 8.5 release to see if still fail?

**Comment by PoodleWang** [comment]
> Hi @PoodleWang , do you have any log about the failure? Could you try the latest 8.5 release to see if still fail?

solved
