### ISSUE TITLE
does tensorrt-7.1 support int8 quantization for dynamic input model with custom plugins?

### ISSUE THREAD

**Issue by elliotzheng** [onnx/onnx-tensorrt#905]
1. tensorrt-7.1 
2. c++
3. dynamic input
4. tow custom plugins by cuda
my onnx model was sucessfully transformed to tensorrt engine with fp16 quantization, now i want to try with int8 quantization.
i write a calibrator class, add it to config with setInt8Calibrator, and setFlag(nvinfer1::BuilderFlag::kINT8). then i  try to print something in getBatch(), but nothing is printed out. the tensorrt engine is successfully created, but with no int8 quantization.
so does tensorrt-7.1 support int8 quantization for dynamic input model with custom plugins?
any help will be appreciated

**Comment by zhenhuaw-me** [comment]
@elliotzheng What do you mean by "dynamic input"? It seems you are trying a FP model with INT8 precision?

**Comment by elliotzheng** [comment]
> @elliotzheng What do you mean by "dynamic input"? It seems you are trying a FP model with INT8 precision?

The shape of input is dynmic, like the number of point cloud [N, c], where N varies. 

I have found a solution. Thanks any way.

**Comment by zhenhuaw-me** [comment]
Glad to hear that. Close this now. Please feel free to reopen if any further issue.
