### ISSUE TITLE
Is "bilinear" mode supported in upsample layer

### ISSUE THREAD

**Issue by lixuefeng810** [onnx/onnx-tensorrt#96]
I have converted a pytorch model(contains some upsample layers with "bilinear" operation) to a onnx file, but when I tried to transfer onnx to tensorRT file using onnx2trt, some errors appeared:
```
----------------------------------------------------------------
Input filename:   ../data/BiSeNet.proto
ONNX IR version:  0.0.3
Opset version:    6
Producer name:    pytorch
Producer version: 0.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
While parsing node number 364 [Upsample -> "1663"]:
ERROR: /home/lee/Project/onnx-tensorrt/builtin_op_importers.cpp:1858 In function importUpsample:
[8] Assertion failed: mode == "nearest"
```
so just "nearest" mode is supported? If I want to edit "bilinear" operation, how to implement it?

My environment:
ubuntu16.04
cuda9.0 + cudnn7.1
tensorRT4

**Comment by liuchang8am** [comment]
Bump. @lixuefeng810 Have you solved your problem?
