### ISSUE TITLE
python onnx_backend_test.py Failure

### ISSUE THREAD

**Issue by LukeAI** [onnx/onnx-tensorrt#98]
Both the Python and Python3 onnx backend tests fail in an identical fashion, I include the output for python3 below as this is probably better supported? Can anybody help me to resolve and get a working onnx-tensorrt install?

Ubuntu 16.04, CUDA 10, CuDNN 7.4.2, tensorrt 5.0.3

I installed tensorrt using the debian nvidia guide: https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#installing-debian
All CUDA, CuDNN and tensorrt tests have passed.

This is the failed test output:

```
python3 onnx_backend_test.py OnnxBackendRealModelTest
Traceback (most recent call last):
  File "onnx_backend_test.py", line 31, in <module>
    import onnx_tensorrt.backend as trt
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/__init__.py", line 23, in <module>
    from . import backend
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 22, in <module>
    from . import parser
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/parser/__init__.py", line 23, in <module>
    from ._nv_onnx_parser_bindings import *
ImportError: No module named _nv_onnx_parser_bindings
```

If I copy+paste the contents of test.py into ipython, it runs as far as downloading the test models but then fails like:

```
ERROR: test_single_relu_model_cuda (__main__.OnnxBackendSimpleModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 178, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 60, in __init__
    self._logger = trt.infer.ConsoleLogger(trt.infer.LogSeverity.WARNING)
AttributeError: 'module' object has no attribute 'infer'

----------------------------------------------------------------------
Ran 548 tests in 551.829s

FAILED (errors=185, skipped=363)
```

(most output abridged for clarity, but all of the failures are: AttributeError: 'module' object has no attribute 'infer'

I have installed onnx-tensorrt as follows (not the non-standard location of -DTENSORRT_ROOT - possibly related?)
```
mkdir build
cd build
cmake .. -DTENSORRT_ROOT=/usr/src/tensorrt
```

Edit /usr/include/cudnn.h to change the line:
`#include "driver_types.h"`
to:
`#include <driver_types.h>`
(required for successful build, see: https://github.com/onnx/onnx-tensorrt/issues/97)

```
make -j8
sudo make install

```
Having done this I have run:
```
python3 setup.py build
sudo python3 setup.py install
```

and had a successful build and install with some warnings.

**Comment by LukeAI** [comment]
It has been suggested on the Nvidia forums that:

**Comment by LukeAI** [comment]
Using the latest code - this now fails in a different way:
https://github.com/onnx/onnx-tensorrt/issues/110

**Comment by kevinch-nv** [comment]
Thanks for the report, we've made some updates in the latest TensorRT release (7.2.1) that fixes a lot of these issues. Please try with the latest version and open a new issue if you are still having trouble.
